---
sidebar: sidebar 
permalink: concept_forensic.html 
keywords: Forensic, user, entity, community 
summary: 포렌식 개요 
---
= 포렌식 정보
:toc: macro
:hardbreaks:
:toclevels: 1
:history: Review 1/17,
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Forensic 보기에서는 사용자, 엔티티, 커뮤니티 및 사용자 활동 정보에 액세스할 수 있습니다.



== 사용자 정보 검사

Forensic > User * 를 클릭하여 User 뷰에 액세스합니다.

이 보기에는 일반 사용자 정보가 표시됩니다.

* 사용자에 대한 자세한 정보를 볼 수 있는 링크가 있는 사용자의 이름입니다.
* 사용자의 작업에 의해 발생한 알림입니다
* 사용자가 속한 커뮤니티 수 커뮤니티 페이지에 대한 링크가 있는 커뮤니티
* 사용자의 위치입니다
* 사용자가 마지막으로 액세스한 엔티티입니다


사용자 이름을 클릭하여 에서 보다 자세한 정보에 액세스합니다 link:forensic_user_detail.html["사용자 개요"]



== 엔터티 정보 검사

Forensic > Entity * 를 클릭하여 Entity 뷰에 액세스합니다.

이 페이지에는 사용자가 액세스하는 엔터티에 대한 일반 정보가 표시됩니다.

에서는 다음을 포함한 세부 정보를 설명합니다.

* 엔터티 이름
* 요소 유형


* 엔티티와의 커뮤니티 관계
* 도면요소 경로
* 마지막 액세스 시간입니다
* 요소 크기


엔터티 이름 을 클릭하여 의 자세한 정보에 액세스합니다 link:forensic_entity_detail.html["요소 개요"]

엔티티가 포함된 커뮤니티를 표시하려면 커뮤니티 수를 클릭합니다.



== 커뮤니티 정보 검토

커뮤니티 페이지에 액세스하려면 * Forensic > Communities * 를 클릭합니다.

이 보기는 다음을 제공합니다.

* 커뮤니티 이름
* 커뮤니티와 관련된 알림입니다
* 커뮤니티에 대한 사용자 수입니다
* 커뮤니티에는 엔티티가 포함됩니다


커뮤니티 이름을 클릭하거나 검색하여 커뮤니티 세부 정보 페이지에 액세스합니다.

커뮤니티 프로필:: 커뮤니티 사용자 위치 및 기타 가장 가까운 커뮤니티를 나열합니다.
커뮤니티 행동:: 에는 액세스한 엔터티의 수가 나와 있으며 읽기, 쓰기 및 Metea 데이터 액세스 작업을 보여 줍니다.
사용자 및 요소:: 커뮤니티의 전체 사용자 및 전체 엔티티를 식별합니다.
커뮤니티 분석::
+
--
* 커뮤니티 사용자 경향
* 요소에 대해 수행되는 작업입니다
* 경고 추세


--


커뮤니티 이름을 클릭하여 에서 자세한 정보를 확인하십시오 link:forensic_community_detail.html["커뮤니티 세부 정보"]



== 사용자 활동 정보 검토

Forensic > User Activity * 를 클릭하여 User Activity 뷰에 액세스합니다.

모니터링 중인 각 사용자에 대해 이 보기에서는 다음 사항을 설명합니다.

* 엔티티 액세스 시간입니다
* 사용자 개요에 대한 링크를 사용하여 엔티티에 액세스한 사용자입니다
* 수행된 활동:
+
** 읽기
** 쓰기
** 생성
** 이름 바꾸기


* 도면요소 경로
* 요소 유형
* 액세스 위치 사용자 이름을 클릭하여 의 자세한 정보에 액세스합니다 link:forensic_user_detail.html["엔터티 세부 정보"]

