---
sidebar: sidebar 
permalink: concept_searching_assets.html 
summary: 고급 검색 기술 검색을 통해 원하는 자산을 찾을 수 있습니다. 
keywords: asset page, objects, search, advanced, alerts 
---
= 자산 및 경고 검색을 위한 힌트 및 팁
:allow-uri-read: 


[role="lead"]
모니터링되는 환경에서 데이터 또는 개체를 검색하는 데 여러 검색 기술을 사용할 수 있습니다.

* * 와일드카드 검색 *
+
문자를 사용하여 여러 문자 와일드카드 검색을 수행할 수 있습니다. 예를 들어, _applic*n_은 _application_을 반환합니다.

* * 검색에 사용되는 구 *
+
구문은 "VNX LUN 5"와 같이 큰따옴표로 묶은 단어 그룹입니다. 큰따옴표를 사용하여 이름이나 속성에 공백이 포함된 문서를 검색할 수 있습니다.

* * 부울 연산자 *
+
부울 연산자 또는 AND, NOT를 사용하면 여러 용어를 결합하여 보다 복잡한 쿼리를 만들 수 있습니다.

+
또는

+
또는 연산자는 기본 결합 연산자입니다.

+
두 용어 사이에 부울 연산자가 없으면 OR 연산자가 사용됩니다.

+
OR 연산자는 두 용어를 연결하고 문서에 일치하는 용어가 있는 경우 일치하는 문서를 찾습니다.

+
예를 들어, _ storage 또는 netapp _ 은(는) _ storage _ 또는 _ NetApp _ 이(가) 포함된 문서를 검색합니다.

+
대부분의 조건과 일치하는 문서에 높은 점수가 부여됩니다.

+
및

+
AND 연산자를 사용하여 두 검색어가 모두 하나의 문서에 있는 문서를 찾을 수 있습니다. 예를 들어, _storage 및 netapp_은 _storage_와 _NetApp_이 둘 다 포함된 문서를 검색합니다.

+
단어 및 대신 * & * 기호를 사용할 수 있습니다.

+
아닙니다

+
NOT 연산자를 사용하면 NOT가 포함된 모든 문서가 검색 결과에서 제외됩니다. 예를 들어, _storage not NetApp_ 은(는) _storage_만 포함되어 있고 _NetApp_은 포함하지 않는 문서를 검색합니다.

+
NOT 단어 대신 *! * 기호를 사용할 수 있습니다.



검색은 대/소문자를 구분하지 않습니다.



== 인덱싱된 용어를 사용하여 검색합니다

인덱싱된 용어 중 더 많은 조건과 일치하는 검색을 수행하면 더 높은 점수를 얻을 수 있습니다.

검색 문자열은 스페이스를 기준으로 별도의 검색어로 분할됩니다. 예를 들어, 검색 문자열 "storage aurora NetApp"은 "storage", "aurora", "NetApp"의 세 가지 키워드로 분할됩니다. 검색은 세 가지 용어를 모두 사용하여 수행됩니다. 이 용어 중 대부분과 일치하는 문서의 점수가 가장 높습니다. 더 많은 정보를 제공할수록 검색 결과가 더 좋습니다. 예를 들어 이름 및 모델별로 스토리지를 검색할 수 있습니다.

UI는 범주 별로 검색 결과를 표시하며 범주 당 상위 3개 결과를 표시합니다. 예상한 개체를 찾지 못한 경우 검색 문자열에 더 많은 용어를 포함해서 검색 결과를 개선할 수 있습니다.

다음 표에서는 검색 문자열에 추가할 수 있는 인덱싱된 용어 목록을 제공합니다.

|===
| 범주 | 인덱싱된 용어 


| 스토리지 | "스토리지" 네임 공급업체 모델 


| 스토리지 풀 | "storagepool" 이름 스토리지 공급업체 스토리지 모델 이름에 대한 스토리지 일련 번호의 스토리지 IP 주소 모든 연결된 디스크의 모든 내부 볼륨 이름에 대한 이름입니다 


| 내부 볼륨 | 스토리지 공급업체의 스토리지 일련 번호 스토리지 풀 이름에 대한 스토리지 IP 주소의 "내부 볼륨" 이름입니다. 연결된 모든 애플리케이션의 모든 공유 이름에 대한 스토리지 풀 이름입니다 


| 볼륨 | 스토리지 공급업체 스토리지 모델의 스토리지 IP 주소에 대한 스토리지 풀 이름의 모든 내부 볼륨 이름 "volume" 이름 레이블 이름입니다 


| 스토리지 노드 | 스토리지 공급업체 스토리지 모델의 스토리지 일련 번호에 대한 스토리지 IP 주소의 "storagenode" 이름입니다 


| 호스트 | "호스트" 이름 IP는 연결된 모든 애플리케이션의 이름을 지정합니다 


| 데이터 저장소 | "datastore" name virtual center IP name of all volumes names of all internal volumes 


| 가상 머신 | "VirtualMachine" 이름 DNS 이름 IP 주소 모든 연결된 응용 프로그램의 모든 데이터 저장소 이름에 대한 호스트 IP 주소의 이름입니다 


| 스위치(일반 및 NPV) | "스위치" IP 주소 WWN 이름 일련 번호 모델 Fabric의 도메인 ID 이름입니다 


| 응용 프로그램 | "애플리케이션" 이름 부서 프로젝트의 테넌트 라인 


| 테이프 | "테이프" IP 주소 이름 일련 번호 공급업체 


| 포트 | "포트" WWN 이름입니다 


| 패브릭 | "fabric" WWN 이름입니다 


| 스토리지 가상 시스템(SVM) | "storagevirtualmachine" 이름 UUID 
|===