---
sidebar: sidebar 
permalink: concept_asset_page_overview.html 
summary: 대부분의 개체 유형에 대해 자산 페이지를 표시할 수 있습니다. 
keywords: asset page, objects, landing page, Virtual machine, VM, Storage Virtual Machine, SVM, Volume, Internal volume, Host, Hypervisor, pool, Storage, Datastore, Application, node, Qtree, Disk, VMDK, Port, Switch, Fabric 
---
= 자산 페이지 개요
:allow-uri-read: 


[role="lead"]
자산 페이지는 자산의 현재 상태를 요약하고 자산 및 관련 자산에 대한 추가 정보에 대한 링크를 포함합니다.



== 자산 페이지 유형

Cloud Insights는 다음 자산에 대한 자산 페이지를 제공합니다.

* 가상 머신
* 스토리지 가상 시스템(SVM)
* 볼륨
* 내부 볼륨
* 호스트(하이퍼바이저 포함)
* 스토리지 풀
* 스토리지
* 데이터 저장소
* 응용 프로그램
* 스토리지 노드
* qtree입니다
* 디스크
* VMDK입니다
* 포트
* 스위치
* 패브릭




== 표시된 데이터의 시간 범위를 변경합니다

기본적으로 자산 페이지에는 지난 24시간 동안의 데이터가 표시되지만 표시되는 데이터 세그먼트는 다른 고정 시간 범위 또는 사용자 지정 시간 범위를 선택하여 변경하거나 더 적은 데이터 또는 더 많은 데이터를 볼 수 있습니다.

자산 유형에 관계없이 모든 자산 페이지에 있는 옵션을 사용하여 표시된 데이터의 시간 세그먼트를 변경할 수 있습니다. 시간 범위를 변경하려면 상단 표시줄에 표시된 시간 범위를 클릭하고 다음 시간 세그먼트 중에서 선택합니다.

* 최근 15분
* 마지막 30분
* 마지막 60분
* 최근 2시간
* 최근 3시간(기본값)
* 최근 6시간
* 최근 12시간
* 최근 24시간
* 최근 2일
* 지난 3일
* 최근 7일
* 지난 30일
* 사용자 지정 시간 범위


사용자 지정 시간 범위를 사용하면 최대 31일 연속 선택할 수 있습니다. 이 범위에 대한 시작 시간 및 종료 시간을 설정할 수도 있습니다. 기본 시작 시간은 선택한 첫 번째 날짜의 오전 12:00이고 기본 종료 시간은 선택한 마지막 날짜의 오후 11:59입니다. 적용 을 클릭하면 자산 페이지에 사용자 지정 시간 범위가 적용됩니다.



== 사용자 지정 위젯을 추가합니다

자체 위젯을 모든 자산 페이지에 추가할 수 있습니다. 추가한 위젯은 해당 유형의 모든 객체에 대한 자산 페이지에 표시됩니다. 예를 들어 스토리지 자산 페이지에 사용자 지정 위젯을 추가하면 모든 스토리지 자산에 대한 자산 페이지에 해당 위젯이 표시됩니다.
