---
sidebar: sidebar 
permalink: concept_cs_event_rate_checker.html 
summary: ONTAP SVM DSC를 설치하기 전에 이 스크립트를 실행하여 SVM의 이벤트 속도를 확인할 수 있습니다 
keywords: event, checker, rate, sizing 
---
= SVM 이벤트 속도 검사기


[role="lead"]
이벤트 속도 검사기는 ONTAP SVM 데이터 수집기를 설치하기 전에 SVM에서 NFS/SMB의 결합된 이벤트 속도를 확인하여 에이전트 시스템 한 대를 모니터링할 수 있는 SVM의 수를 확인하는 데 사용됩니다.

요구 사항:

* 클러스터 IP
* 클러스터 관리자 사용자 이름 및 암호입니다



NOTE: 이 스크립트를 실행할 때 이벤트 속도를 확인할 SVM을 위해 ONTAP SVM Data Collector를 실행해야 합니다.

단계:

. CloudSecure의 지침에 따라 Agent를 설치합니다.
. 에이전트가 설치되면 sudo 사용자로 _server_data_rate_checker.sh_script를 실행합니다.
+
 /opt/netapp/cloudsecure/agent/install/svm_event_rate_checker.sh
. 이 스크립트를 사용하려면 Linux 시스템에 _sshpass_를 설치해야 합니다. 두 가지 방법으로 설치할 수 있습니다.
+
.. 다음 명령을 실행합니다.
+
 linux_prompt> yum install sshpass
.. 그렇지 않으면 웹에서 Linux 시스템으로 _sshpass_를 다운로드하고 다음 명령을 실행합니다.
+
 linux_prompt> rpm -i sshpass


. 메시지가 표시되면 올바른 값을 입력합니다. 예를 보려면 아래를 참조하십시오.
. 스크립트는 약 5분 정도 소요됩니다.
. 실행이 완료되면 스크립트가 SVM의 이벤트 속도를 인쇄합니다. 콘솔 출력에서 SVM당 이벤트 속도를 확인할 수 있습니다.
+
 “Svm svm_rate is generating 100 events/sec”.


. 각 ONTAP SVM Data Collector를 단일 SVM과 연결할 수 있습니다. 즉, 각 데이터 수집기에서 단일 SVM에서 생성되는 이벤트 수를 받을 수 있습니다.


다음 사항에 유의하십시오.

a) 단일 Agent 시스템에서 다음 작업을 처리할 수 있습니다.

|===


| 에이전트 시스템 구성 | SVM 데이터 수집기 수 | Agent Machine이 처리할 수 있는 최대 이벤트 속도 


| 4코어, 16GB | 10개의 데이터 수집기 | 초당 20,000개의 이벤트 


| 4코어, 32GB | 20개의 데이터 수집기 | 초당 20,000개의 이벤트 
|===
b) 총 이벤트를 계산하려면 해당 에이전트에 대해 생성된 모든 SVM에 대해 생성된 이벤트를 추가합니다.

c) 피크 시간 동안 스크립트가 실행되지 않거나 피크 트래픽을 예측하기 어려운 경우 이벤트 속도 버퍼를 30%로 유지합니다.

B+C는 A보다 작아야 합니다. 그렇지 않으면 Agent 시스템이 모니터링하지 못합니다.

즉, 단일 에이전트 시스템에 추가할 수 있는 데이터 수집기의 수는 아래 공식을 준수해야 합니다.

 Sum of all Event rate of all Data Source Collectors + Buffer Event rate of 30% < 20000 events/second


=== 예

SVM이 각각 100개, 200개, 300개의 이벤트를 생성한다고 가정해 보겠습니다.

다음 수식을 적용합니다.

....
 (100+200+300) + [(100+200+300)*30%] = 600+180 = 780events/sec
780 events/second is < 20000 events/second, so the 3 SVMs can be monitored via one agent box.
....
콘솔 출력은 현재 작업 디렉토리의 파일 이름 __FPolicy_stat_<SVM 이름>.log__에서 Agent 시스템에서 사용할 수 있습니다.

스크립트는 다음과 같은 경우에 잘못된 결과를 제공할 수 있습니다.

* 잘못된 자격 증명, IP 또는 SVM 이름이 제공됩니다.
* 이름, 시퀀스 번호 등이 동일한 기존 FPolicy에서 오류가 발생합니다.
* 실행 중에 스크립트가 갑자기 중지됩니다.


스크립트 실행의 예는 다음과 같습니다.

 [root@ci-cs-data agent]# /opt/netapp/cloudsecure/agent/install/svm_event_rate_checker.sh
....
Enter the cluster ip: 10.192.139.166
Enter the username to SSH: admin
Enter the password:
Getting event rate for NFS and SMB events.
Available SVMs in the Cluster
-----------------------------
QA_SVM
Stage_SVM
Qa-fas8020
Qa-fas8020-01
Qa-fas8020-02
audit_svm
svm_rate
vs_new
vs_new2
....
....
-----------------------------
Enter [1/5] SVM name to check (press enter to skip): svm_rate
Enter [2/5] SVM name to check (press enter to skip): audit_svm
Enter [3/5] SVM name to check (press enter to skip):
Enter [4/5] SVM name to check (press enter to skip):
Enter [5/5] SVM name to check (press enter to skip):
Running check for svm svm_rate...
Running check for svm audit_svm...
Waiting 5 minutes for stat collection
Stopping sample svm_rate_sample
Stopping sample audit_svm_sample
fpolicy stats of svm svm_rate is saved in fpolicy_stat_svm_rate.log
Svm svm_rate is generating 100 SMB events/sec and 100 NFS events/sec
Overall svm svm_rate is generating 200 events/sec
fpolicy stats of svm audit_svm is saved in fpolicy_stat_audit_svm.log
Svm audit_svm is generating 200 SMB events/sec and 100 NFS events/sec
Overall svm audit_svm is generating 300 events/sec
....
 [root@ci-cs-data agent]#


== 문제 해결

|===


| 질문: 이미 Cloud Secure용으로 구성된 SVM에서 이 스크립트를 실행하면 SVM에서 기존 FPolicy 구성을 사용하기만 합니까, 아니면 임시 FPolicy 구성을 설정하고 프로세스를 실행합니까? 


| 답변: Cloud Secure용으로 이미 구성된 SVM에 대해서도 이벤트 속도 검사기를 실행할 수 있습니다. 아무런 영향도 미치지 않아야 합니다. 


| 질문: 스크립트를 실행할 수 있는 SVM의 수를 늘릴 수 있습니까? 


| 답변: 예. 스크립트를 편집하고 SVM의 최대 수를 5개에서 원하는 수로 변경하면 됩니다. 


| 질문: SVM 수를 늘릴 경우 스크립트 실행 시간이 늘어집니까? 


| 답변: 아니요 이 스크립트는 SVM 수가 증가하더라도 최대 5분 동안 실행됩니다. 


| 질문: 스크립트를 실행할 수 있는 SVM의 수를 늘릴 수 있습니까? 


| 답변: 예. 스크립트를 편집하고 SVM의 최대 수를 5개에서 원하는 수로 변경해야 합니다. 


| 질문: SVM 수를 늘릴 경우 스크립트 실행 시간이 늘어집니까? 


| 답변: 아니요 이 스크립트는 SVM 수가 증가하더라도 최대 5분 동안 실행됩니다. 
|===