---
sidebar: sidebar 
permalink: concept_about_applications.html 
keywords: applications, asset, cost 
summary: 회사 환경에서 사용되는 애플리케이션을 이해하면 자산 사용량과 비용을 추적할 수 있습니다. 
---
= 애플리케이션별로 자산 사용 추적
:allow-uri-read: 


[role="lead"]
회사 환경에서 사용되는 애플리케이션을 이해하면 자산 사용량과 비용을 추적할 수 있습니다.

사용자 환경에서 실행 중인 애플리케이션과 관련된 데이터를 추적하려면 먼저 해당 애플리케이션을 정의하고 적절한 자산과 연결해야 합니다. 호스트, 가상 머신, 볼륨, 내부 볼륨, qtree, 공유 및 하이퍼바이저.

이 항목에서는 마케팅 팀이 Exchange 전자 메일에 사용하는 가상 시스템의 사용을 추적하는 예를 제공합니다.

사용자 환경에서 사용되는 애플리케이션을 식별하고 각 애플리케이션을 사용하여 그룹 또는 사업부를 메모하기 위해 다음과 유사한 테이블을 만들 수 있습니다.

[cols="5*"]
|===


| 테넌트 | 사업 부문 | 사업부 | 프로젝트 | 응용 프로그램 


| 넷엡 | 데이터 스토리지 | 법적 고지 | 특허 | Oracle Identity Manager, Oracle On Demand, Patentg마법사 


| 넷엡 | 데이터 스토리지 | 마케팅 | 영업 이벤트 | Exchange, Oracle Shared database, Blastoff Event Planner 
|===
이 표는 마케팅 팀이 Exchange 애플리케이션을 사용한다는 것을 보여줍니다. Exchange의 가상 시스템 활용률을 추적하여 스토리지를 추가해야 하는 시기를 예측할 수 있습니다. Exchange 애플리케이션을 모든 마케팅 가상 머신에 연결할 수 있습니다.

. 이름이 _Exchange_인 응용 프로그램을 만듭니다
. 쿼리 > + 새 쿼리 * 로 이동하여 가상 머신에 대한 새 쿼리를 만들거나 기존 VM 쿼리를 선택합니다(해당하는 경우).
+
마케팅 팀의 VM에 모두 "* Mkt*" 문자열이 포함된 이름이 있다고 가정하면 쿼리를 만들어 VM 이름을 “Mkt”로 필터링합니다.

. VM을 선택합니다.
. Bulk Actions > Add Applications * 를 사용하여 VM을 _Exchange_응용 프로그램과 연결합니다.
. 원하는 응용 프로그램을 선택하고 * Save * (저장 *)를 클릭합니다.
. 완료되면 * 쿼리를 * 저장 * 합니다.

