---
sidebar: sidebar 
permalink: concept_acquisition_unit_requirements.html 
summary: 획득 장치로 사용하는 서버 또는 VM은 최소 요구 사항을 충족해야 합니다 
keywords: AU, acquisition unit, RAU, requirements, sizing 
---
= 획득 장치 요구 사항
:allow-uri-read: 


[role="lead"]
인프라스트럭처 데이터 수집기(스토리지, VM, 포트, EC2 등)로부터 정보를 가져오려면 획득 장치(AU)를 설치해야 합니다. 획득 장치를 설치하기 전에 운영 체제, CPU, 메모리 및 디스크 공간 요구 사항을 충족하는지 확인해야 합니다.



=== 요구 사항

|===


| 구성 요소 | Linux 요구 사항 | Windows 요구 사항 


| 운영 체제 | 라이센스 버전 중 하나를 실행하는 컴퓨터 * CentOS(64비트): 7.2 - 7.9, 8.1 - 8.4 * Debian(64비트): 9 및 10 * Oracle Enterprise Linux(64비트): 7.5 - 7.9, 8.1 - 8.4 * Red Hat Enterprise Linux(64비트): 7.2 ~ 7.9, 8.1 ~ 8.4 * Ubuntu 서버: 18.04 및 20.04 LTS 이 컴퓨터는 다른 응용 프로그램 수준 소프트웨어를 실행하지 않아야 합니다. 전용 서버가 권장됩니다. | 다음 중 하나의 라이센스 버전을 실행하는 컴퓨터: * Microsoft Windows 10 64비트 * Microsoft Windows Server 2012 * Microsoft Windows Server 2012 R2 * Microsoft Windows Server 2016 * Microsoft Windows Server 2019 이 컴퓨터는 다른 응용 프로그램 수준 소프트웨어를 실행하지 않아야 합니다. 전용 서버가 권장됩니다. 


| CPU | CPU 코어 2개 | 동일합니다 


| 메모리 | 8GB RAM | 동일합니다 


| 사용 가능한 디스크 공간입니다 | Linux의 경우 50GB, 디스크 공간은 /opt/NetApp 10GB/var/log/NetApp 40GB로 할당해야 합니다 | 50GB 


| 네트워크 | 100Mbps/1Gbps 이더넷 연결, 정적 IP 주소, 모든 FC 디바이스에 대한 IP 연결 및 Cloud Insights 인스턴스에 대한 필수 포트(80 또는 443). | 동일합니다 


| 권한 | 획득 장치 서버의 sudo 권한. /tmp는 Exec 기능과 함께 마운트되어야 합니다. | 획득 장치 서버에 대한 관리자 권한 


| 바이러스 검사 |  | 설치하는 동안 모든 바이러스 스캐너를 완전히 비활성화해야 합니다. 설치 후 획득 장치 소프트웨어에서 사용하는 경로는 바이러스 검사에서 제외되어야 합니다. 
|===


=== 추가 권장 사항

* 정확한 감사 및 데이터 보고를 위해 * NTP(Network Time Protocol) * 또는 * SNTP(Simple Network Time Protocol) * 를 사용하여 획득 장치 시스템의 시간을 동기화하는 것이 좋습니다.




=== 사이징 관련

8GB 메모리와 50GB의 디스크 공간으로 Cloud Insights 획득 장치를 시작할 수 있지만, 대규모 환경에서는 다음과 같은 질문을 스스로에게 해야 합니다.

다음 사항을 예상하십니까?

* 이 획득 장치에서 2,500개 이상의 가상 머신 또는 10개의 대규모(>2개 노드) ONTAP 클러스터, Symmetrix 또는 HDS/HPE VSP/XP 스토리지를 검색합니까?
* 이 획득 장치에 75개 이상의 총 데이터 수집기를 배포하시겠습니까?


위의 "예"로 답할 때마다 AU에 8GB의 메모리와 50GB의 디스크 공간을 추가하는 것이 좋습니다. 예를 들어, 둘 다에 "예"를 선택한 경우 150GB 이상의 디스크 공간이 있는 24GB 메모리 시스템을 구축해야 합니다. Linux에서 로그 위치에 추가할 디스크 공간입니다.

사이징에 대한 추가 질문은 NetApp 지원에 문의하십시오.
