---
sidebar: sidebar 
permalink: concept_asset_user_data_section.html 
summary: 자산 페이지의 사용자 데이터 섹션에서 현재 자산에 주석 또는 애플리케이션을 할당할 수 있습니다. 
keywords: asset page, user data, applications, annotations 
---
= 사용자 데이터 섹션
:allow-uri-read: 


[role="lead"]
자산 페이지의 사용자 데이터 섹션이 표시되고 응용 프로그램 및 주석과 같은 사용자 정의 데이터를 변경할 수 있습니다.



== 사용자 데이터 섹션을 사용하여 응용 프로그램을 할당하거나 수정합니다

사용자 환경에서 실행 중인 애플리케이션을 특정 자산(호스트, 가상 머신, 볼륨, 내부 볼륨, Qtree, 있습니다. 사용자 데이터 섹션을 사용하면 자산에 할당된 애플리케이션을 추가, 변경 또는 제거할 수 있습니다. 볼륨을 제외한 이러한 모든 자산 유형에 대해 둘 이상의 애플리케이션을 할당할 수 있습니다.

.단계
. 다음 중 하나를 수행하여 자산 페이지를 찾습니다.
+
.. 자산 목록을 쿼리한 다음 목록에서 하나를 선택합니다.
.. 대시보드에서 자산 이름을 찾아 클릭합니다.
.. 검색을 수행하고 결과에서 자산을 선택합니다.
+
자산 페이지가 표시됩니다. 페이지의 사용자 데이터 섹션에는 현재 할당된 응용 프로그램 또는 주석이 표시됩니다.





할당된 응용 프로그램을 변경하거나 응용 프로그램 또는 추가 응용 프로그램을 할당하려면 * 응용 프로그램 * 목록을 드롭다운하여 자산에 할당할 응용 프로그램을 선택합니다. 을 입력하여 응용 프로그램을 검색하거나 목록에서 하나를 선택할 수 있습니다.

응용 프로그램을 제거하려면 응용 프로그램 목록을 드롭다운하고 응용 프로그램을 선택 취소합니다.



== User Data(사용자 데이터) 섹션을 사용하여 주석을 할당하거나 수정합니다

Cloud Insights를 사용자 지정하여 회사 요구 사항에 맞는 데이터를 추적할 때 주석이라는 특수 메모를 정의하고 자산에 할당할 수 있습니다. 자산 페이지의 사용자 데이터 섹션에는 자산에 할당된 주석이 표시되며 해당 자산에 할당된 주석을 변경할 수도 있습니다.

.단계
. 자산에 주석을 추가하려면 자산 페이지의 사용자 데이터 섹션에서 * + 주석 * 을 클릭합니다.
. 목록에서 주석을 선택합니다.
. 값을 클릭하고 선택한 주석 유형에 따라 다음 중 하나를 수행합니다.
+
.. 주석 유형이 목록, 날짜 또는 부울인 경우 목록에서 값을 선택합니다.
.. 주석 유형이 텍스트인 경우 값을 입력합니다.


. 저장 을 클릭합니다.


주석이 자산에 할당됩니다. 나중에 쿼리를 사용하여 주석을 기준으로 자산을 필터링할 수 있습니다.

주석을 지정한 후 주석 값을 변경하려면 주석 목록을 드롭다운하고 다른 값을 입력합니다.

fly_option에서 _Add new values를 선택한 목록 유형의 주석인 경우 기존 값을 선택하는 것 외에도 새 값을 추가하도록 입력할 수 있습니다.
