---
sidebar: sidebar 
permalink: faq-config-support.html 
keywords: FAQ, Frequently asked questions, questions, configuration, 
summary:  
---
= 구성 및 지원 장치


[role="lead"]
이 FAQ는 Cloud Insights 구성 및 지원되는 장치에 대한 일반적인 질문에 대한 답변을 제공합니다.



== Cloud Insights가 환경을 변경합니까?

아니요 Cloud Insights는 사용자 환경에 대한 정보를 수집하는 읽기 전용 툴입니다. Cloud Insights은 자산 또는 구성을 변경하지 않습니다.



== Cloud Insights가 내 장치에 필요한 권한 수준 액세스는 무엇입니까?

장치가 지원하는 대부분의 경우 읽기 전용 액세스만 있으면 됩니다. 읽기 전용 액세스를 허용하지 않으므로 적절한 상승된 권한이 필요한 솔루션이 있습니다.



== Cloud Insights는 얼마나 자주 정보를 수집합니까?

Cloud Insights는 일반적으로 5분마다 성능 데이터를 수집하고 30분마다 논리적 및 물리적 구조를 검색합니다 Cloud Insights는 제안된 모범 사례와 확장성에 따라 기본 폴링 간격을 설정하지만 사용자가 이러한 간격을 완전히 제어할 수 있습니다.



== Cloud Insights는 내 환경에 어떤 영향을 미칩니까?

Cloud Insights의 에이전트 없는 대역외 및 수동 IP 통신은 설정, 유지 관리 및 데이터 센터 에코시스템에 대한 영향을 최소화합니다. Cloud Insights의 성능 개발 팀은 성능 모니터링 활동에서 데이터 센터의 성능에 미치는 영향을 최소화하기 위해 훌륭한 조치를 취합니다. 일반적인 운영 환경에서는 영향이 거의 없는 것으로 간주되며, 사용률이 높거나 성능이 떨어지는 기술 플랫폼에서는 완화하거나 강화될 수 있습니다. 자세한 내용은 Cloud Insights 설치 가이드를 참조하십시오.



== Cloud Insights에서 모든 호스트/VM을 나열하려면 어떻게 해야 합니까?

Cloud Insights의 위젯 및 쿼리 목록 가능성을 보완하여 데이터 센터 자산에 대한 인벤토리 스타일 목록을 제공하는 데 사용할 수 있습니다. 스핀들 아래에 있는 가상 머신 목록과 그 사이에 있는 다양한 구문을 쿼리, 위젯, 대시보드, 데이터 웨어하우스 보고 등에 사용할 수 있으며 RESTful API를 통해 액세스할 수 있습니다.



== Cloud Insights는 관련된 비 하이퍼바이저 호스트(예: 물리적 서버)에 대해 동일한 유형의 지원을 제공합니까?

VMware와 같은 하이퍼바이저에서는 ESXi 호스트 및 해당 VM(가상 머신)에 대한 자세한 정보를 제공합니다. 물리적 서버의 경우 Cloud Insights는 호스트 HBA까지 메트릭을 수집합니다. Cloud Insights는 특허 출원 중인 기술을 사용하여 물리적 서버를 검색하는 고유한 방법을 사용합니다. 스토리지 및/또는 스위치가 검색되면 물리적 서버의 호스트 이름이 Fabric 별칭 정보에 포함됩니다. Cloud Insights는 이러한 호스트 이름을 선택하여 DNS에서 일치시키고 자동으로 호스트를 Cloud Insights로 가져옵니다. 이 기술은 수동 입력 업데이트 및 공구 재고 유지 관리의 필요성을 크게 최소화합니다.



== Cloud Insights는 이기종 환경에서 동일한 장치 메트릭 수준(패리티)을 제공합니까?

타사 플랫폼 및 공급업체 기술 전반에 걸쳐 표준화, 공통성 및 명명도의 정도가 다양합니다. Cloud Insights은 용량 및 성능 정보를 일관된 프레임워크로 정규화하려고 합니다. IOPS, 지연 시간, 물리적 용량 등의 일부 용량 및 성능 메트릭이 디바이스의 카운터로부터 기본적으로 제공됩니다. 카운터가 제공되지 않으면 Cloud Insights는 값을 요약하려고 시도할 수 있으며(예: 기본 볼륨의 IOPS 또는 용량을 합산하여), 두 가지 모두 사용할 수 없는 경우 Cloud Insights는 다양한 계산 알고리즘을 통해 메트릭 값을 도출하려고 시도합니다. Cloud Insights는 현재 Cloud Insights에서 수집하지 않은 추가 메트릭을 통합할 수 있는 일반 SNMP 통합 기능을 제공합니다.



== Cloud Insights는 파이버 채널 스위치를 지원합니까?

예. Cloud Insights는 스토리지 자산에서 데이터를 수집하는 것 외에도 사용자 환경의 Cisco, Brocade 및 QLogic 스위치로부터 인벤토리 및 성능 데이터를 가져옵니다.

== 전체 인프라의 토폴로지 뷰를 사용할 수 있습니까? Cloud Insights에 "엔드 투 엔드 가시성"이 표시됩니까?

예. Cloud Insights는 논리적 및 물리적 구조를 동적으로 검색 및 매핑하여 컴퓨팅, 패브릭, 가상자 및 백엔드 스토리지에 대한 대화형 종단 간 토폴로지 뷰를 제공합니다. 토폴로지 아이콘을 사용하면 영향을 받는 리소스를 빠르게 탐색할 수 있으며 공유 스토리지 환경에서 워크로드 및 위반 사항을 쉽게 식별할 수 있습니다.
