---
sidebar: sidebar 
permalink: io_density_nonroot.html 
keywords: notifications, annotations, queries, applications, 
summary: IO 밀도 
---
= 입출력 밀도 데이터가 내부 데이터 볼륨만 기술하도록 보장


[role="lead"]
NetApp 스토리지 시스템에서 루트 애그리게이트에는 루트 볼륨이 포함되어 있으며 스토리지 시스템을 관리 및 제어하기 위한 특수 디렉토리와 구성 파일이 포함되어 있습니다. 이러한 작업은 루트 집계에서 많은 양의 작업을 초래할 수 있습니다. IO 밀도가 가장 높은 상위 10개 내부 볼륨에 대해 Cloud Insights을 쿼리하면 상위 10개의 멤버로 NetApp 루트 애그리게이트를 포함할 수 있습니다.

환경을 모니터링할 때 높은 I/O 밀도를 생성하는 내부 데이터 볼륨을 확인하는 것이 더 중요합니다. 데이터 볼륨만 정확하게 식별하려면 NetApp 내부 볼륨을 I/O 밀도를 모니터링하는 데 사용하는 쿼리와 격리해야 합니다.

이 가이드에서는 NetApp 루트 애그리게이트를 쉽게 식별하고, 내부 볼륨 쿼리 결과에서 해당 애그리게이트를 파악하고, 새 NetApp 루트 애그리게이트를 시스템에 추가할 때 제외하는 규칙을 생성하는 방법에 대해 설명합니다. 다음 Cloud Insights 기능은 I/O 밀도 보고서가 내부 데이터 볼륨에서 파생되도록 하는 데 사용됩니다.

* 쿼리가 생성되어 Cloud Insights에서 모니터링하는 모든 NetApp 루트 애그리게이트를 식별합니다.
* 각 NetApp 루트 애그리게이트에 하나의 주석이 할당됩니다.
* NetApp 루트 애그리게이트를 제외할 주석 규칙이 생성됩니다.




== 사용자 환경에서 NetApp 루트 애그리게이트를 식별하는 쿼리를 생성합니다

쿼리는 사용자가 선택한 기준에 따라 세분화된 수준으로 검색을 제공합니다. 쿼리를 사용하여 NetApp 루트 애그리게이트가 포함된 환경에서 내부 볼륨을 검색할 수 있습니다.

.단계
. Cloud Insights에서 쿼리를 생성하여 * 쿼리 > + 새 쿼리 > 스토리지 풀 * 에서 NetApp 루트 애그리게이트를 식별합니다
. 루트 애그리게이트의 이름을 입력합니다
+
이 예제에서는 이름에 "aggr0"을 사용합니다. Aggregate를 생성할 때 이름의 다음 요구 사항만을 따라야 합니다.

+
** 문자 또는 밑줄(_)으로 시작해야 합니다.
** 문자, 숫자 및 밑줄만 포함할 수 있습니다.
** 250자 이하일 수 있습니다.




대부분의 경우 Aggregate는 aggr0, aggr_0 또는 이와 유사한 이름을 사용합니다. 사용자 환경에서 모든 NetApp 루트 애그리게이트를 식별하려면 반복적인 프로세스가 필요할 수 있습니다.

. 저장 * 을 클릭하고 새 쿼리의 이름을 입력합니다.
+
앞에서 설명한 대로 이 프로세스는 반복 프로세스이며 모든 NetApp 루트 애그리게이트를 확인하기 위해 여러 쿼리가 필요합니다.





== 쿼리에서 반환된 루트 볼륨에 대한 주석을 생성합니다

주석은 자산에 할당하는 특수 노트로서 주석을 기준으로 자산을 필터링할 수 있습니다. 생성하는 주석은 사용자 환경에서 NetApp 루트 애그리게이트를 파악하고, IO 밀도가 가장 높은 내부 볼륨 목록에 포함되지 않도록 하는 데 사용됩니다.

"높은 I/O 밀도" 보고서에서 제외할 루트 애그리게이트를 모두 식별해야 합니다.

.단계
. 쿼리로 식별된 모든 NetApp 루트 애그리게이트를 연결하는 주석을 생성합니다. * 관리 > 주석 *
+
.. 주석의 이름을 * RootAggregr * 로 입력합니다
.. 주석에 대한 설명을 입력합니다. * "높은 I/O 밀도" 목록에서 루트 애그리게이트 제거 *
.. 주석 유형 * 부울 * 을 입력합니다


. 저장 * 을 클릭합니다




== I/O 밀도 보고서에서 특정 애그리게이트를 제외하도록 주석 규칙을 생성합니다

개별 자산에 주석을 수동으로 적용하는 대신 주석 규칙을 사용하여 여러 자산에 주석을 자동으로 적용할 수 있습니다. 주석 규칙은 사용자가 만든 쿼리를 기반으로 하며 시스템에서 실행할 때 기존 자산 집합에 새 자산을 추가합니다. 이러한 자산 세트를 포함에서 제외하면 새 자산도 자동으로 제외됩니다.

사용자 환경에서 식별한 NetApp 루트 애그리게이트를 식별하는 쿼리를 작성하여 저장해야 합니다.

.단계
. Cloud Insights 메뉴에서 * 관리 > 주석 * 을 클릭합니다
. 추가 * 를 클릭합니다
. 다음을 수행합니다.
+
.. 이름 상자에 규칙을 설명하는 고유한 이름 * RootAggrExclude * 를 입력합니다
.. Query를 클릭하고 Cloud Insights가 주석 규칙을 적용할 때 사용해야 하는 Query를 * Aggregate0 * 으로 선택합니다
.. 주석 을 클릭하고 * Root agg exclude * 를 선택합니다
.. 값 * 을 클릭하고 * True * 를 입력합니다



