---
sidebar: sidebar 
permalink: index.html 
summary: Cloud Insights 설명서 포털에 오신 것을 환영합니다. 
---
= Cloud Insights 설명서


[role="lead"]
NetApp Cloud Insights는 전체 인프라에 대한 가시성을 제공하는 클라우드 인프라 모니터링 툴입니다. Cloud Insights를 사용하면 퍼블릭 클라우드 및 프라이빗 데이터 센터를 비롯한 모든 리소스에 대한 모니터링, 문제 해결 및 최적화 등이 가능합니다.

Cloud Insights는 다음과 같은 이점을 제공합니다.

* * 평균 해결 시간을 최대 90% 단축 *
+
며칠 동안 로그 헌팅을 중지하고 인프라를 수동으로 상호 분석하지 않음: 동적 토폴로지 및 상관 관계 분석을 사용하여 문제 영역을 즉시 파악합니다.

* * 클라우드 인프라 비용을 평균 33% 절감합니다 *
+
버려진 사용되지 않는 리소스와 최적화된 성능 및 비용 계층에 적합한 크기의 워크로드를 식별하여 비효율성을 제거합니다.

* * 최종 사용자에게 영향을 미치는 클라우드 문제의 최대 80%를 차단합니다 *
+
고급 분석 및 머신 러닝을 사용하여 심각한 운영 중단이 발생하기 전에 문제를 파악함으로써 방대한 양의 데이터를 분석하여 관련 자료를 찾아냅니다.





== 시작하기

* 신규 고객: link:task_cloud_insights_onboarding_1.html["온보딩"]
* 가입했습니다. 이제 어떻게 해야 합니까?link:task_getting_started_with_cloud_insights.html["데이터 획득"]

* Cloud Insights를 최대한 활용하려면 어떻게 해야 합니까?link:task_defining_annotations.html["자산 준비:주석 달기"]



* Cloud Insights를 사용해 보았는데 이제 준비가 되었습니다 link:concept_subscribing_to_cloud_insights.html["* 가입 *"].

