---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, flexgroup, ontap s3, s3 configuration, svm dr, svm disaster recovery, disaster recovery, storage vm dr, BlueXP, cloud manager 
summary: 알려진 제한 사항은 이 제품 릴리스에서 지원하지 않거나 올바르게 상호 운용되지 않는 플랫폼, 장치 또는 기능을 식별합니다. 이러한 제한 사항을 주의 깊게 검토하십시오. 
---
= 알려진 제한 사항
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
알려진 제한 사항은 이 제품 릴리스에서 지원하지 않거나 올바르게 상호 운용되지 않는 플랫폼, 장치 또는 기능을 식별합니다. 이러한 제한 사항을 주의 깊게 검토하십시오.

이러한 제한은 BlueXP의 Cloud Volumes ONTAP 관리에만 적용됩니다. Cloud Volumes ONTAP 소프트웨어 자체의 제한 사항을 보려면 https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-limitations.html["Cloud Volumes ONTAP 릴리즈 노트 로 이동합니다"^]



== BlueXP는 FlexGroup 볼륨 생성을 지원하지 않습니다

Cloud Volumes ONTAP는 FlexGroup 볼륨을 지원하지만 BlueXP는 현재 FlexGroup 볼륨 생성을 지원하지 않습니다. 시스템 관리자 또는 CLI에서 FlexGroup 볼륨을 생성하는 경우 BlueXP의 용량 관리 모드를 수동으로 설정해야 합니다. FlexGroup 볼륨에서 자동 모드가 제대로 작동하지 않을 수 있습니다.


NOTE: BlueXP에서 FlexGroup 볼륨을 생성할 수 있는 기능은 향후 릴리스에 제공될 예정입니다.



== BlueXP는 Cloud Volumes ONTAP에서 S3을 지원하지 않습니다

Cloud Volumes ONTAP는 S3를 스케일 아웃 스토리지 옵션으로 지원하지만 BlueXP는 이 기능에 대한 관리 기능을 제공하지 않습니다. CLI를 사용하는 것이 Cloud Volumes ONTAP에서 S3 클라이언트 액세스를 구성하는 모범 사례입니다. 자세한 내용은 를 참조하십시오 http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-s3-cg/home.html["S3 구성 전원 가이드"^].

link:concept-client-protocols.html["S3 및 기타 클라이언트 프로토콜에 대한 Cloud Volumes ONTAP 지원에 대해 자세히 알아보십시오"].



== BlueXP는 스토리지 VM의 재해 복구를 지원하지 않습니다

BlueXP는 스토리지 VM(SVM) 재해 복구에 대한 설정 또는 오케스트레이션 지원을 제공하지 않습니다. System Manager 또는 CLI를 사용해야 합니다.

link:task-manage-svm-dr.html["SVM 재해 복구에 대해 자세히 알아보십시오"].



== AsciiDoc 문자 교체 및 내장 속성 테스트

모든 언어의 현지화 및 게시를 통해 종단 간 테스트

.별표
{별표}
텍스트 {Asterisk}
텍스트 {Asterisk}
텍스트 {별표} 텍스트

.이중 콜론
{two-colons}
텍스트 {two-colons}
텍스트 {two-colons}
텍스트 {two-colons} 텍스트입니다

.세로 막대
{vbar}
텍스트 {vbar}
텍스트 {vbar}
텍스트 {vbar} 텍스트

.또한
{plus}
텍스트 {plus}
텍스트 {plus}
텍스트 {plus} 텍스트

.대괄호
{startsb} 및 {endsb}
텍스트 {startsb} 및 텍스트 {endsb}
텍스트 {startsb} 및 텍스트 {endsb}
텍스트 {startsb} 및 텍스트 {endsb} 텍스트입니다

.줄 바꿈하지 않는 공간
{nbsp} 이전

.너비가 0인 공간
{zwsp} 이전
