---
sidebar: sidebar 
permalink: reporting_creating_custom_reports.html 
summary: '보고서 작성 도구를 사용하여 사용자 지정("임시") 보고서를 만듭니다' 
keywords: reporting, cognos, data warehouse, dwh, ad-hoc, custom 
---
= 사용자 정의 보고서 작성
:allow-uri-read: 


[role="lead"]
보고서 작성 도구를 사용하여 사용자 정의 보고서를 만들 수 있습니다. 보고서를 만든 후에는 보고서를 저장하고 정기적으로 실행할 수 있습니다. 보고서 결과는 사용자 자신 및 다른 사람에게 이메일로 자동 전송될 수 있습니다.


NOTE: 보고 기능은 Cloud Insights에서 사용할 수 있습니다 link:concept_subscribing_to_cloud_insights.html["Premium Edition을 참조하십시오"].

이 섹션의 예에서는 Cloud Insights 보고 데이터 모델에 사용할 수 있는 다음 프로세스를 보여 줍니다.

* 보고서로 답할 질문 식별
* 결과를 지원하는 데 필요한 데이터 결정
* 보고서의 데이터 요소 선택


사용자 지정 보고서를 디자인하기 전에 몇 가지 필수 작업을 완료해야 합니다. 이 작업을 완료하지 않으면 보고서가 부정확하거나 불완전할 수 있습니다.

예를 들어, 디바이스 식별 프로세스를 완료하지 않으면 용량 보고서가 정확하지 않게 됩니다. 또는 주석 설정(예: 계층, 사업부 및 데이터 센터)을 완료하지 않으면 사용자 지정 보고서가 도메인 전체의 데이터를 정확하게 보고하지 않거나 일부 데이터 요소에 대해 "N/A"가 표시될 수 있습니다.

보고서를 디자인하기 전에 다음 작업을 완료합니다.

* 모두 구성 link:task_configure_data_collectors.html["데이터 수집기"] 있습니다.
* 사용자 환경의 장치 및 리소스에 대한 주석(예: 계층, 데이터 센터 및 부서)을 입력합니다. Cloud Insights 보고 기능은 기록 정보를 수집하므로 보고서를 생성하기 전에 주석을 안정적으로 만드는 것이 좋습니다.




=== 보고서 작성 프로세스

사용자 지정("임시") 보고서를 만드는 프로세스에는 여러 작업이 포함됩니다.

* 보고서 결과를 계획합니다.
* 결과를 지원하는 데이터를 식별합니다.
* 데이터가 포함된 데이터 모델(예: 차지백 데이터 모델, 재고 데이터 모델 등)을 선택합니다.
* 보고서의 데이터 요소를 선택합니다.
* 보고서 결과의 서식 지정, 정렬 및 필터링 옵션을 선택할 수 있습니다.




==== 사용자 지정 보고서의 결과 계획

보고서 작성 도구를 열기 전에 보고서에서 원하는 결과를 계획할 수 있습니다. 보고서 작성 도구를 사용하면 보고서를 쉽게 만들 수 있으며 많은 계획을 세울 필요가 없을 수도 있습니다. 그러나 보고서 요청자로부터 보고서 요구 사항에 대한 설명을 받는 것이 좋습니다.

* 답변하려는 정확한 질문을 식별합니다. 예를 들면 다음과 같습니다.
+
** 남은 용량은 얼마나 됩니까?
** 사업부당 차지백 비용은 얼마입니까?
** 비즈니스 유닛이 적절한 스토리지 계층에 맞춰 정렬되도록 하는 계층별 용량은 얼마입니까?
** 전력 및 냉각 요구 사항을 어떻게 예측할 수 있습니까? (리소스에 주석을 추가하여 사용자 지정된 메타데이터를 추가합니다.)


* 답변을 지원하는 데 필요한 데이터 요소를 식별합니다.
* 답안에 표시할 데이터 간의 관계를 식별합니다. "용량과 관련된 포트를 보고 싶습니다."와 같은 비논리적 관계는 질문에 포함하지 마십시오.
* 데이터에 필요한 계산을 식별합니다.
* 결과를 제한하는 데 필요한 필터링 유형을 결정합니다.
* 현재 또는 과거 데이터를 사용해야 하는지 확인합니다.
* 보고서에 대한 액세스 권한을 설정하여 데이터를 특정 대상에게 제한해야 하는지 확인합니다.
* 보고서를 배포하는 방법을 식별합니다. 예를 들어, 설정된 일정에 따라 전자 메일로 보내거나 팀 콘텐츠 폴더 영역에 포함되어 있어야 합니까?
* 보고서를 유지 관리할 사람을 결정합니다. 이는 설계의 복잡성에 영향을 줄 수 있습니다.
* 보고서 모형을 만듭니다.




==== 보고서 디자인 팁

보고서를 디자인할 때 몇 가지 팁이 도움이 될 수 있습니다.

* 현재 데이터 또는 기간별 데이터를 사용해야 하는지 여부를 결정합니다.
+
대부분의 보고서는 Cloud Insights에서 사용 가능한 최신 데이터만 보고하면 됩니다.

* Cloud Insights 보고 기능은 용량 및 성능에 대한 기간별 정보를 제공하지만 인벤토리에 대한 정보는 제공하지 않습니다.
* 모든 사람이 모든 데이터를 볼 수 있지만 특정 대상에만 데이터를 제한해야 할 수 있습니다.
+
서로 다른 사용자에 대한 정보를 분할하려면 보고서를 만들고 이에 대한 액세스 권한을 설정할 수 있습니다.





== 보고 데이터 모델

Cloud Insights에는 미리 정의된 보고서를 선택하거나 사용자 지정 보고서를 만들 수 있는 여러 데이터 모델이 포함되어 있습니다.

각 데이터 모델에는 간단한 데이터 마트와 고급 데이터 마트가 포함되어 있습니다.

* Simple Data Mart는 가장 일반적으로 사용되는 데이터 요소에 빠르게 액세스할 수 있도록 하며 데이터 웨어하우스 데이터의 마지막 스냅샷만 포함하고 기록 데이터는 포함하지 않습니다.
* 고급 데이터 마트는 단순 데이터 마트에서 사용할 수 있는 모든 값과 세부 정보를 제공하며 기록 데이터 값에 대한 액세스를 포함합니다.




=== 용량 데이터 모델

스토리지 용량, 파일 시스템 활용률, 내부 볼륨 용량, 포트 용량, qtree 용량, 가상 머신(VM) 용량을 제공합니다. 용량 데이터 모델은 여러 용량 데이터 모델의 컨테이너입니다. 이 데이터 모델을 사용하여 다양한 유형의 질문에 대한 답변을 작성할 수 있습니다.



=== 스토리지 및 스토리지 풀 용량 데이터 모델입니다

스토리지 및 스토리지 풀을 비롯하여 스토리지 용량 리소스 계획에 대한 질문에 답변하고 물리적 및 가상 스토리지 풀 데이터를 모두 포함할 수 있습니다. 이 간단한 데이터 모델을 통해 설치 현장의 용량 및 시간에 따른 계층 및 데이터 센터별 스토리지 풀의 용량 사용과 관련된 질문에 답할 수 있습니다. 용량 보고를 처음 사용하는 경우, 이 데이터 모델은 단순한 타겟 데이터 모델이기 때문에 먼저 시작해야 합니다. 이 데이터 모델을 사용하여 다음과 유사한 질문에 답할 수 있습니다.

* 물리적 스토리지의 용량 임계값 80%에 도달할 것으로 예상되는 날짜는 언제입니까?
* 특정 계층의 스토리지에 있는 물리적 스토리지 용량은 얼마입니까?
* 데이터 센터뿐 아니라 제조업체 및 제품군별 스토리지 용량은 얼마나 됩니까?
* 모든 계층의 스토리지 사용률 추세는 무엇입니까?
* 사용률이 가장 높은 상위 10개 스토리지 시스템은 무엇입니까?
* 스토리지 풀의 스토리지 활용률 동향은 무엇입니까?
* 이미 할당된 용량은 어느 정도입니까?
* 할당에 사용할 수 있는 용량은 무엇입니까?




=== 파일 시스템 활용률 데이터 모델

이 데이터 모델을 사용하면 파일 시스템 레벨에서 호스트의 용량 활용도를 파악할 수 있습니다. 관리자는 파일 시스템당 할당 및 사용 용량을 확인하고, 파일 시스템 유형을 결정하고, 파일 시스템 유형별로 추세 통계를 식별할 수 있습니다. 이 데이터 모델을 사용하여 다음 질문에 답할 수 있습니다.

* 파일 시스템의 크기는 얼마입니까?
* 데이터는 어디에 보관되며 로컬 또는 SAN과 같은 액세스 방법은 무엇입니까?
* 파일 시스템 용량에 대한 기간별 동향은 무엇입니까? 그런 다음, 이를 토대로 향후 요구 사항에 대해 무엇을 예상할 수 있습니까?




=== 내부 볼륨 용량 데이터 모델

시간이 지남에 따라 내부 볼륨 사용 용량, 할당된 용량 및 용량 사용량에 대한 질문에 답할 수 있습니다.

* 활용률이 사전 정의된 임계값보다 높은 내부 볼륨은 무엇입니까?
* 추세에 따라 용량이 부족해질 위험이 있는 내부 볼륨은 무엇입니까? 8 내부 볼륨에서 할당된 용량과 사용된 용량은 어떻게 됩니까?




=== Port Capacity 데이터 모델입니다

스위치 포트 연결, 포트 상태 및 포트 속도에 대한 질문에 시간 경과에 따른 답변을 얻을 수 있습니다. 새 스위치 구입을 계획하는 데 도움이 되는 다음과 같은 질문에 답할 수 있습니다. 데이터 센터, 스위치 공급업체 및 포트 속도에 따라 리소스(포트) 가용성을 예측하는 포트 소비 예측을 생성하려면 어떻게 해야 합니까?

* 용량이 부족해 데이터 속도, 데이터 센터, 공급업체, 호스트 및 스토리지 포트 수를 제공하는 포트는 무엇입니까?
* 시간에 따른 스위치 포트 용량 동향은 무엇입니까?
* 포트 속도는 어떻게 됩니까?
* 어떤 유형의 포트 용량이 필요하며 특정 포트 유형 또는 공급업체에서 부족하게 될 조직은 무엇입니까?
* 해당 용량을 구매하여 사용할 수 있는 최적의 시간은 언제입니까?




=== Qtree 용량 데이터 모델

시간이 지남에 따라 사용된 용량과 할당된 용량 등의 데이터를 사용하여 qtree 사용률을 추세를 파악할 수 있습니다. 사업체, 애플리케이션, 계층, 서비스 수준 등 다양한 차원에서 정보를 볼 수 있습니다. 이 데이터 모델을 사용하여 다음 질문에 답할 수 있습니다.

* Qtree에서 사용되는 용량과 애플리케이션 또는 비즈니스 엔터티별 설정된 제한 용량은 얼마나 됩니까?
* 용량 계획을 위해 사용되는 용량과 가용 용량의 동향은 무엇입니까?
* 어떤 비즈니스 엔터티가 용량을 가장 많이 사용하고 있습니까?
* 어떤 애플리케이션이 가장 많은 용량을 소비하고 있습니까?




=== VM 용량 데이터 모델

가상 환경 및 용량 사용을 보고할 수 있습니다. 이 데이터 모델을 사용하면 VM 및 데이터 저장소에 대한 시간 경과에 따른 용량 사용량 변화를 보고할 수 있습니다. 또한 데이터 모델은 씬 프로비저닝 및 가상 머신 차지백 데이터를 제공합니다.

* VM 및 데이터 저장소에 프로비저닝된 용량을 기준으로 용량 비용 청구를 어떻게 결정할 수 있습니까?
* VM에서 사용되지 않는 용량과 사용되지 않는 부분, 분리된 용량 또는 기타 공간 중 어느 것이 있습니까?
* 소비 동향을 기반으로 무엇을 구입해야 합니까?
* 스토리지 씬 프로비저닝 및 중복제거 기술을 사용하여 얻을 수 있는 스토리지 효율성 절감액은 무엇입니까?


VM 용량 데이터 모델의 용량은 VMDK(가상 디스크)에서 가져옵니다. 즉, VM 용량 데이터 모델을 사용하는 VM의 프로비저닝된 크기가 해당 가상 디스크의 크기입니다. 이 용량은 Cloud Insights의 가상 머신 보기에 있는 프로비저닝된 용량과 다르며, 이 보기에는 VM 자체의 프로비저닝된 크기가 표시됩니다.



=== 볼륨 용량 데이터 모델

사용자 환경에서 볼륨의 모든 측면을 분석하고 공급업체, 모델, 계층, 서비스 수준 및 데이터 센터별로 데이터를 구성할 수 있습니다.

분리된 볼륨, 미사용 볼륨 및 보호 볼륨(복제에 사용됨)과 관련된 용량을 볼 수 있습니다. 또한 다양한 볼륨 기술(iSCSI 또는 FC)을 확인하고 스토리지 가상화 문제에 대해 가상 볼륨을 비가상 볼륨과 비교할 수 있습니다.

이 데이터 모델을 사용하여 다음과 유사한 질문에 답할 수 있습니다.

* 활용률이 사전 정의된 임계값보다 높은 볼륨은 무엇입니까?
* 데이터 센터에서 거의 사용되지 않는 볼륨 용량에 대한 추세가 어떻게 됩니까?
* 가상화 또는 씬 프로비저닝된 데이터 센터 용량은 어느 정도입니까?
* 복제용으로 예약해야 하는 데이터 센터 용량은 얼마나 됩니까?




=== 차지백 데이터 모델

스토리지 리소스(볼륨, 내부 볼륨 및 Qtree)에서 사용된 용량 및 할당된 용량에 대한 질문에 답변할 수 있습니다. 이 데이터 모델은 호스트, 애플리케이션 및 업무 엔티티별로 스토리지 용량 차지백 및 책임 정보 정보를 제공하며 현재 데이터와 기간별 데이터를 모두 포함합니다. 보고서 데이터는 서비스 수준 및 스토리지 계층별로 분류할 수 있습니다.

이 데이터 모델을 사용하여 업무 엔티티가 사용하는 용량을 찾아서 비용청구 보고서를 생성할 수 있습니다. 이 데이터 모델을 사용하면 여러 프로토콜(NAS, SAN, FC 및 iSCSI 포함)에 대한 통합 보고를 생성할 수 있습니다.

* 내부 볼륨이 없는 스토리지의 경우 차지백 보고서는 볼륨별 차지백을 표시합니다.
* 내부 볼륨이 있는 스토리지의 경우:
+
** 업무 엔티티가 볼륨에 할당된 경우 비용 청구 보고서는 볼륨별 비용 청구를 표시합니다.
** 비즈니스 엔터티가 볼륨에 할당되지 않고 qtree에 할당된 경우, 차지백 보고서는 qtree에 따른 차지백을 표시합니다.
** 비즈니스 엔터티가 볼륨에 할당되지 않고 Qtree에 할당되지 않은 경우, 비용청구 보고서는 내부 볼륨을 표시합니다.
** 각 내부 볼륨별로 볼륨, qtree 또는 내부 볼륨별로 차지백을 표시할지 여부를 결정하므로 동일한 스토리지 풀에 있는 서로 다른 내부 볼륨에서 차지백을 서로 다른 레벨로 표시할 수 있습니다.




용량 팩트는 기본 시간 간격 후에 삭제됩니다. 자세한 내용은 데이터 웨어하우스 프로세스 를 참조하십시오.

Chargeback 데이터 모델을 사용하는 보고서에는 Storage Capacity 데이터 모델을 사용하는 보고서와 다른 값이 표시될 수 있습니다.

* NetApp 스토리지 시스템이 아닌 스토리지 어레이의 경우 두 데이터 모델의 데이터는 동일합니다.
* NetApp 및 Celerra 스토리지 시스템의 경우 Chargeback 데이터 모델은 단일 계층(볼륨, 내부 볼륨 또는 qtree)을 사용하여 요금을 내지만 Storage Capacity 데이터 모델은 여러 계층(볼륨 및 내부 볼륨)을 사용하여 요금을 기준으로 합니다.




=== 재고 데이터 모델

호스트, 스토리지 시스템, 스위치, 디스크, 테이프, 디스크 및 기타 리소스 등 인벤토리 리소스에 대한 Qtree, 할당량, 가상 머신 및 서버, 일반 디바이스 인벤토리 데이터 모델에는 복제, FC 경로, iSCSI 경로, NFS 경로 및 위반 사항에 대한 정보를 볼 수 있는 여러 하위 마트가 포함되어 있습니다. 재고 데이터 모델에는 내역 데이터가 포함되어 있지 않습니다. 이 데이터로 답변할 수 있는 질문입니다

* 보유하고 있는 자산은 무엇이며 어디에 있습니까?
* 누가 자산을 사용하고 있습니까?
* 어떤 유형의 장치가 있고 이러한 장치의 구성 요소는 무엇입니까?
* OS당 호스트 수와 해당 호스트에 몇 개의 포트가 있습니까?
* 각 데이터 센터에 공급업체당 어떤 스토리지 어레이가 있습니까?
* 각 데이터 센터에 공급업체 당 몇 개의 스위치가 있습니까?
* 라이센스가 부여되지 않은 포트 수는 몇 개입니까?
* 어떤 공급업체 테이프를 사용하고 있으며 각 테이프에는 몇 개의 포트가 있습니까?보고서 작업을 시작하기 전에 모든 일반 디바이스를 식별합니까?
* 호스트와 스토리지 볼륨 또는 테이프 사이의 경로는 무엇입니까?
* 일반 디바이스와 스토리지 볼륨 또는 테이프 간의 경로는 무엇입니까?
* 데이터 센터당 각 유형 위반은 몇 개입니까?
* 복제된 각 볼륨에 대해 소스 볼륨과 타겟 볼륨은 무엇입니까?
* Fibre Channel 호스트 HBA와 스위치 간에 펌웨어 비호환성 또는 포트 속도가 일치하지 않습니까?




=== 성능 데이터 모델

볼륨, 애플리케이션 볼륨, 내부 볼륨, 스위치, 애플리케이션 및 성능에 대한 질문에 VM, VMDK, ESX 대 VM, 호스트 및 애플리케이션 노드 이 데이터 모델을 사용하면 다음과 같은 여러 유형의 성과 관리 질문에 대한 답변을 제공하는 보고서를 작성할 수 있습니다.

* 특정 기간 동안 사용 또는 액세스하지 않은 볼륨 또는 내부 볼륨은 무엇입니까?
* 애플리케이션에 대한 스토리지의 구성 오류를 찾아낼 수 있습니까(미사용)?
* 애플리케이션의 전반적인 액세스 동작 패턴은 무엇이었습니까?
* 특정 애플리케이션에 대해 계층형 볼륨이 적절하게 할당됩니까?
* 애플리케이션 성능에 영향을 주지 않고 현재 실행 중인 애플리케이션에 더 저렴한 스토리지를 사용할 수 있습니까?
* 현재 구성된 스토리지에 더 많은 액세스를 생성하는 애플리케이션은 무엇입니까?


스위치 성능 표를 사용할 때 다음 정보를 얻을 수 있습니다.

* 연결된 포트를 통한 호스트 트래픽의 균형이 조정됩니까?
* 많은 오류가 발생하는 스위치 또는 포트는 무엇입니까?
* 포트 성능에 따라 가장 많이 사용되는 스위치는 무엇입니까?
* 포트 성능에 따라 활용도가 낮은 스위치는 무엇입니까?
* 포트 성능을 기반으로 하는 호스트 추세 처리량은 얼마입니까?
* 지정된 호스트, 스토리지 시스템, 테이프 또는 스위치 하나에 대한 마지막 X일 동안의 성능 사용률은 어떻습니까?
* 특정 스위치에서 트래픽을 생성하는 장치(예: 활용도가 높은 스위치를 사용하는 장치)는 무엇입니까?
* 우리 환경에서 특정 사업부의 처리량은 어떻습니까?


디스크 성능 테이블을 사용할 때 다음 정보를 얻을 수 있습니다.

* 디스크 성능 데이터를 기반으로 지정된 스토리지 풀의 처리량은 얼마입니까?
* 가장 많이 사용되는 스토리지 풀은 무엇입니까?
* 특정 스토리지의 평균 디스크 사용률은 어떻습니까?
* 디스크 성능 데이터를 기반으로 스토리지 시스템 또는 스토리지 풀을 사용하는 추세가 어떻게 됩니까?
* 특정 스토리지 풀에 대한 디스크 사용 동향은 무엇입니까?


VM 및 VMDK 성능 표를 사용하는 경우 다음 정보를 얻을 수 있습니다.

* 가상 환경이 최적의 성능을 발휘하고 있습니까?
* 가장 높은 워크로드를 보고하는 VMDK는 무엇입니까?
* 다른 데이터 저장소에 매핑된 VMD에서 보고된 성능을 사용하여 재계층화에 대한 결정을 내리는 방법


성능 데이터 모델에는 계층의 적절성, 애플리케이션의 스토리지 구성 오류, 볼륨 및 내부 볼륨의 마지막 액세스 시간을 결정하는 데 도움이 되는 정보가 포함되어 있습니다. 이 데이터 모델은 응답 시간, IOPS, 처리량, 보류 중인 쓰기 수 및 액세스 상태와 같은 데이터를 제공합니다.



=== 스토리지 효율성 데이터 모델

시간의 경과에 따른 스토리지 효율성 점수 및 잠재 가치를 추적할 수 있습니다. 이 데이터 모델은 프로비저닝된 용량뿐만 아니라 사용 또는 사용된 용량(물리적 측정)의 측정치도 저장합니다. 예를 들어, 씬 프로비저닝이 설정된 경우 Cloud Insights는 디바이스에서 얼마나 많은 용량을 가져가는지를 나타냅니다. 또한 이 모델을 사용하여 중복제거가 활성화되어 있는 경우의 효율성을 확인할 수 있습니다. Storage Efficiency Data Mart:

* 씬 프로비저닝 및 중복제거 기술 구현 시 NetApp의 스토리지 효율성이 어떻게 절감됩니까?
* 데이터 센터 전체에서 스토리지 비용이 얼마나 절감됩니까?
* 과거 용량 추세를 기준으로 추가 스토리지를 언제 구입해야 합니까?
* 씬 프로비저닝 및 중복 제거와 같은 기술을 사용할 경우 얻게 되는 용량 이득은 무엇입니까?
* 스토리지 용량과 관련하여 현재 제가 위험에 노출되어 있습니까?




=== 데이터 모델 팩트 및 차원 테이블

각 데이터 모델에는 팩트 테이블과 차원 테이블이 모두 포함됩니다.

* 팩트 테이블: 수량, 원시 용량 및 가용 용량과 같이 측정된 데이터를 포함합니다. 테이블에 대한 외래 키를 포함합니다.
* 차원 테이블: 데이터 센터 및 사업부 등의 팩트에 대한 설명 정보를 포함합니다. 차원은 데이터를 범주화하는 계층 구조로 구성되는 구조입니다. 차원 특성은 차원 값을 설명하는 데 도움이 됩니다.


보고서에서 열로 표시되는 여러 차원 속성 또는 여러 차원 속성을 사용하면 데이터 모델에 설명된 각 차원의 데이터에 액세스하는 보고서를 작성할 수 있습니다.



=== 데이터 모델 요소에 사용된 색상

데이터 모델 요소의 색상은 서로 다른 표시를 가집니다.

* 노란색 자산: 측정값을 나타냅니다.
* 노란색이 아닌 자산: 속성을 나타냅니다. 이러한 값은 집계되지 않습니다.




=== 하나의 보고서에서 여러 데이터 모델 사용

일반적으로 보고서당 하나의 데이터 모델을 사용합니다. 그러나 여러 데이터 모델의 데이터를 결합하는 보고서를 작성할 수 있습니다.

여러 데이터 모델의 데이터를 결합하는 보고서를 작성하려면 기반으로 사용할 데이터 모델 중 하나를 선택한 다음 SQL 쿼리를 작성하여 추가 데이터 마트에서 데이터에 액세스합니다. SQL 조인 기능을 사용하여 다른 쿼리의 데이터를 보고서 쓰기에 사용할 수 있는 단일 쿼리로 결합할 수 있습니다.

예를 들어, 각 스토리지 배열의 현재 용량을 원하는 경우 배열에 사용자 지정 주석을 캡처하려는 경우를 가정해 봅니다. 스토리지 용량 데이터 모델을 사용하여 보고서를 생성할 수 있습니다. 현재 용량 및 차원 테이블의 요소를 사용하고 별도의 SQL 쿼리를 추가하여 인벤토리 데이터 모델의 주석 정보에 액세스할 수 있습니다. 마지막으로 저장소 이름 및 연결 조건을 사용하여 재고 저장소 데이터를 저장소 차원 테이블에 연결하여 데이터를 결합할 수 있습니다.
