---
sidebar: sidebar 
permalink: reporting_user_roles.html 
summary: Cloud Insights 보고를 사용하여 수행할 수 있는 작업은 사용자 역할에 따라 다릅니다. 
keywords: reporting, cognos, data warehouse, dwh, users, roles, user roles 
---
= Cloud Insights 보고 사용자 역할
:allow-uri-read: 


[role="lead"]
보고 기능이 있는 Cloud Insights 프리미엄 에디션이 있는 경우 사용자 환경의 모든 Cloud Insights 사용자는 보고 응용 프로그램(즉 Cognos)를 참조하십시오. 메뉴에서 * Reports * 링크를 클릭하면 자동으로 Reporting에 로그인됩니다.

Cloud Insights의 사용자 역할에 따라 보고 사용자 역할이 결정됩니다.

|===


| Cloud Insights 역할 | 보고 역할 | 보고 권한 


| 게스트 | 소비자 | 에서는 보고서를 보고 일정을 잡고 실행할 수 있으며 언어 및 표준 시간대와 같은 개인 기본 설정을 설정할 수 있습니다. 소비자는 보고서를 만들거나 관리 작업을 수행할 수 없습니다. 


| 사용자 | 저자 | 는 모든 소비자 기능을 수행할 뿐 아니라 보고서 및 대시보드를 생성 및 관리할 수 있습니다. 


| 관리자 | 관리자 | 보고서 구성, 보고 작업 종료 및 재시작 등의 모든 관리 작업과 모든 작성자 기능을 수행할 수 있습니다. 
|===
다음 표에서는 각 보고 역할에 사용할 수 있는 기능을 보여 줍니다.

|===


| 피처 | 소비자 | 저자 | 관리자 


| 팀 콘텐츠 탭에서 보고서를 봅니다 | 예 | 예 | 예 


| 보고서를 실행합니다 | 예 | 예 | 예 


| 보고서 예약 | 예 | 예 | 예 


| 외부 파일을 업로드합니다 | 아니요 | 예 | 예 


| 작업을 생성합니다 | 아니요 | 예 | 예 


| 스토리 만들기 | 아니요 | 예 | 예 


| 보고서 작성 | 아니요 | 예 | 예 


| 패키지 및 데이터 모듈을 생성합니다 | 아니요 | 예 | 예 


| 관리 작업을 수행합니다 | 아니요 | 아니요 | 예 
|===


== 보고(Cognos) 전자 메일 기본 설정 지정


NOTE: Cloud Insights 보고(예: Cognos 응용 프로그램) 내에서 사용자 전자 메일 기본 설정을 변경하는 경우 해당 기본 설정은 현재 세션 _ 에 대해서만 활성화됩니다. Cognos에서 로그아웃했다가 다시 로그인하면 이메일 기본 설정이 재설정됩니다.



== 기존 고객을 위한 중요 참고 사항

보고 기능이 있는 Cloud Insights를 처음 사용하는 경우 환영합니다! 더 이상 보고 기능을 즐기기 위해 해야 할 일은 없습니다.

현재 Premium Edition 고객인 경우 사용자 환경에 SSO가 자동으로 활성화되지 않습니다. SSO를 활성화하면 보고 포털(Cognos)의 관리자 사용자가 더 이상 존재하지 않습니다. 즉, _My Content_폴더에 있는 모든 보고서가 제거되므로 _Team Content_에서 다시 설치하거나 다시 작성해야 합니다. 또한 SSO가 활성화되면 예약된 보고서를 구성해야 합니다.



=== SSO를 활성화하기 위해 기존 환경을 준비하기 위해 어떤 단계를 수행해야 합니까?

보고서가 보존되도록 하려면 다음 단계를 사용하여 모든 보고서를 _My Content_to_Team Content_에서 마이그레이션합니다. 이 작업은 사용자 환경에서 SSO를 활성화하기 전에 수행해야 합니다.

. 팀 내용 _ 에서 새 폴더를 만듭니다
+
.. 여러 사용자가 생성된 경우, 중복된 이름으로 보고서를 덮어쓰지 않도록 각 사용자에 대해 별도의 폴더를 만드십시오


. My Content_로 이동합니다
. 보존하려는 모든 보고서를 선택합니다.
. 메뉴 오른쪽 상단에서 "복사 또는 이동"을 선택합니다.
. 팀 내용 _ 에서 새로 만든 폴더로 이동합니다
. "복사 대상" 또는 "이동 대상" 버튼을 사용하여 새로 만든 폴더에 보고서를 붙여 넣습니다
. Cognos에서 SSO가 활성화되면 계정을 만드는 데 사용되는 전자 메일 주소를 사용하여 Cloud Insights에 로그인합니다.
. Cognos 내의 _Team Content_폴더로 이동하고 이전에 저장된 보고서를 다시 _My Content_로 복사 또는 이동합니다.

