---
sidebar: sidebar 
permalink: task_create_annotation.html 
keywords: annotations, annotation rules, manual annotations, 
summary: 주석을 작성하는 방법. 
---
= 주석 사용
:allow-uri-read: 


[role="lead"]
주석을 작성하고 모니터하는 자산에 할당할 수 있습니다. 주석은 물리적 위치, 수명 종료, 스토리지 계층 또는 볼륨 서비스 수준과 같은 자산에 대한 정보를 제공하는 메모입니다.



== 주석 정의

주석을 사용하여 비즈니스 요구에 맞는 맞춤형 비즈니스 관련 데이터를 자산에 추가할 수 있습니다. Cloud Insights에서는 자산 수명 주기(생일 또는 수명 종료), 건물 또는 데이터 센터 위치, 계층 등 기본 주석 집합을 제공하지만 다른 방법으로 데이터를 보려는 경우도 있습니다.

사용자 지정 주석의 데이터는 스위치 제조업체, 포트 수 및 성능 통계와 같이 이미 수집된 장치 데이터를 보완합니다. 주석을 사용하여 추가하는 데이터는 Cloud Insights에서 검색되지 않습니다.

.시작하기 전에
* 환경 데이터를 연결해야 하는 업계 용어를 나열하십시오.
* 환경 데이터를 연결해야 하는 기업 용어를 나열하십시오.
* 사용할 수 있는 기본 주석 유형을 식별합니다.
* 만들어야 하는 사용자 지정 주석을 식별합니다. 주석을 자산에 할당하려면 먼저 주석을 작성해야 합니다.


주석을 작성하려면 다음 단계를 따르십시오.

.단계
. Cloud Insights 메뉴에서 * 관리 > 주석 * 을 클릭합니다
. 새 주석을 만들려면 * + Annotation * (주석 *)을 클릭합니다.
. 이름, 설명 및 새 주석의 유형을 입력합니다.
+
예를 들어, 다음을 입력하여 데이터 센터 4에서 자산의 물리적 위치를 정의하는 텍스트 주석을 작성합니다.

+
** "Location(위치)"과 같은 주석 이름을 입력합니다.
** "Physical location is Data Center 4"와 같이 주석이 설명하는 내용을 입력합니다.
** "텍스트"와 같이 주석의 '유형'을 입력합니다.






== 자산에 주석 수동 할당

자산에 주석을 지정하면 비즈니스와 관련된 방식으로 자산을 정렬, 그룹화 및 보고할 수 있습니다. 주석 규칙을 사용하여 특정 유형의 자산에 주석을 자동으로 할당할 수 있지만 자산 페이지를 사용하여 개별 자산에 주석을 할당할 수 있습니다.

.시작하기 전에
* 지정할 주석을 만들어야 합니다.


.단계
. Cloud Insights 환경에 로그인합니다.
. 주석을 적용할 자산을 찾습니다.
+
** 쿼리, dashard 위젯에서 선택 또는 검색을 통해 자산을 찾을 수 있습니다. 원하는 자산을 찾았으면 링크를 클릭하여 자산의 랜딩 페이지를 엽니다.


. 자산 페이지의 사용자 데이터 섹션에서 * + 주석 * 을 클릭합니다.
. 주석 추가 대화 상자가 표시됩니다.
. 목록에서 주석을 선택합니다.
. 값을 클릭하고 선택한 주석 유형에 따라 다음 중 하나를 수행합니다.
+
** 주석 유형이 목록, 날짜 또는 부울인 경우 목록에서 값을 선택합니다.
** 주석 유형이 텍스트인 경우 값을 입력합니다.


. 저장 * 을 클릭합니다.


주석을 지정한 후 주석 값을 변경하려면 주석 필드를 클릭하고 다른 값을 선택합니다. fly_option에서 _Add new values를 선택한 목록 유형의 주석인 경우 기존 값을 선택하는 것 외에도 새 값을 입력할 수 있습니다.



== 주석 규칙을 사용하여 주석 지정

사용자가 정의한 기준에 따라 자산에 주석을 자동으로 할당하려면 주석 규칙을 구성합니다. Cloud Insights는 이러한 규칙에 따라 자산에 주석을 할당합니다. 또한 Cloud Insights에서는 두 가지 기본 주석 규칙을 제공합니다. 이 규칙은 필요에 맞게 수정하거나 사용하지 않으려는 경우 제거할 수 있습니다.



=== 주석 규칙 작성

개별 자산에 주석을 수동으로 적용하는 대신 주석 규칙을 사용하여 여러 자산에 주석을 자동으로 적용할 수 있습니다. Insight에서 주석 규칙을 평가할 때 개별 자산 페이지에 수동으로 설정된 주석이 규칙 기반 주석보다 우선합니다.

.시작하기 전에
주석 규칙에 대한 쿼리를 만들어야 합니다.

.이 작업에 대해
규칙을 만드는 동안 주석 유형을 편집할 수 있지만, 미리 유형을 정의해야 합니다.

.단계
. 관리 > 주석 규칙 * 을 클릭합니다
+
주석 규칙 페이지에는 기존 주석 규칙 목록이 표시됩니다.

. 추가 * 를 클릭합니다.
. 다음을 수행합니다.
+
.. 이름 * 상자에 규칙을 설명하는 고유한 이름을 입력합니다.
+
이 이름은 주석 규칙 페이지에 표시됩니다.

.. Query * 를 클릭하고 에셋에 주석을 적용하는 데 사용되는 쿼리를 선택합니다.
.. Annotation(주석) * 을 클릭하고 적용할 주석을 선택합니다.
.. 값 * 을 클릭하고 주석 값을 선택합니다.
+
예를 들어 주석으로 생일 을 선택한 경우 값의 날짜를 지정합니다.

.. 저장 * 을 클릭합니다
.. 모든 규칙을 즉시 실행하려면 * 모든 규칙 실행 * 을 클릭합니다. 그렇지 않으면 규칙들이 정기적으로 예약된 간격으로 실행됩니다.



