---
sidebar: sidebar 
permalink: task_dc_hds_hcp.html 
keywords: data collector, Hitachi HDS, HCP 
summary: HDS 데이터 수집기 구성. 
---
= Hitachi HCP 데이터 수집기입니다


[role="lead"]
이 데이터 수집기는 HCP 관리 API를 사용하는 HCP(Hitachi Content Platform)를 지원합니다.



== 용어

Cloud Insights는 Hitachi HCP 데이터 수집기에서 다음과 같은 재고 정보를 가져옵니다. Cloud Insights에서 획득한 각 자산 유형에 대해 이 자산에 가장 일반적으로 사용되는 용어가 표시됩니다. 이 데이터 수집기를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

[cols="2*"]
|===
| 공급업체/모델 기간 | Cloud Insights 용어입니다 


| HCP 클러스터 | 스토리지 


| 테넌트 | 스토리지 풀 


|  | 네임스페이스 


| 내부 볼륨 | 노드 
|===
참고: 이러한 용어 매핑은 일반적인 용어 매핑일 뿐이며 이 데이터 수집기의 모든 경우를 나타내는 것은 아닙니다.



== 재고 요건

재고 데이터를 수집하려면 다음이 있어야 합니다.

* HCP 서버의 IP 주소입니다
* HCP 소프트웨어 및 피어 권한에 대한 읽기 전용 사용자 이름 및 암호입니다




== 구성

[cols="2*"]
|===
| 필드에 입력합니다 | 설명 


| HCP 호스트 | HCP 호스트의 IP 주소 또는 정규화된 도메인 이름입니다 


| HCP 포트 | 기본값은 9090입니다 


| HCP 사용자 ID | HCP 호스트의 사용자 이름입니다. 


| HCP 암호 | HCP 호스트에 사용되는 암호입니다. 


| HCP 인증 유형 | HCP_LOCAL 또는 ACTIVE_DIRECTORY 를 선택합니다 
|===


== 고급 구성

|===


| 필드에 입력합니다 | 설명 


| 재고 폴링 간격(분) | 재고 조사 사이의 간격입니다. 기본값은 60입니다. 


| 성능 폴링 간격(초) | 성능 폴링 간격입니다. 기본값은 900입니다. 
|===
추가 정보는 에서 찾을 수 있습니다 link:concept_requesting_support.html["지원"] 페이지 또는 에 있습니다 link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Data Collector 지원 매트릭스"].
