---
sidebar: sidebar 
permalink: task_business_entity_annotations.html 
keywords: annotations, business entity 
summary: 업무 엔티티 주석은 업무 계층 구조의 자산을 모니터링하고 보고하는 데 사용할 수 있습니다 
---
= 업무 엔티티 주석
:allow-uri-read: 


[role="lead"]
업무 엔티티 * 주석 유형을 사용하여 기업 환경의 업무 엔티티를 만들고 관리합니다.



== 업무 엔티티 만들기

업무 엔티티를 만들려면 다음을 수행합니다.

. 관리 > 주석 * 을 클릭하고 _Business Entity_링크를 클릭합니다.
+
현재 정의된 업무 엔티티 목록이 표시됩니다.

. 업무 엔티티 * 를 클릭합니다.
. Tenant *, * 사업 부문 *, * 사업 단위 * 및 * 프로젝트 * 필드의 값을 입력합니다.
+
업무 엔티티에 적용되지 않는 필드는 비워 둘 수 있습니다.

. 이전에 필드에 값을 입력한 경우 드롭다운에서 해당 값을 선택할 수 있습니다. 다시 입력할 필요가 없습니다.



NOTE: 선택한 값은 고유한 총 업무 엔티티를 작성해야 합니다. 예를 들어, 해당 순서로 _A/B/C/D_ 값을 가진 업무 엔티티가 이미 있는 경우 해당 값을 가진 다른 업무 엔티티를 만들 수 없습니다. 그러나 이러한 값을 다른 순서로 사용하여 업무 엔티티를 만들 수 있습니다.



== 객체에 업무 엔티티 적용

개체 또는 개체에 비즈니스 엔터티를 적용하는 가장 쉬운 방법은 쿼리를 사용하는 것입니다.

. 쿼리 > + 새 쿼리 * 를 클릭하고 원하는 개체 유형을 선택합니다. 필터를 적용하여 결과를 더 좁힐 수 있습니다.
. 확인란을 클릭하여 업무 엔티티를 적용할 개체를 선택합니다.
. 대량 작업 * 을 클릭하고 * 주석 추가 * 를 선택합니다.
. Business Entity_annotation을 선택하고 목록에서 원하는 업무 엔티티 값을 선택합니다.
. 객체에 업무 엔티티를 적용하려면 * 저장 * 을 클릭합니다.


또한 개체의 자산 랜딩 페이지로 이동하고 사용자 데이터 섹션에서 * + 주석 을 클릭하여 개별 개체에 비즈니스 엔터티를 적용할 수도 있습니다.

을 구성할 수도 있습니다 link:task_create_annotation_rules.html["주석 규칙"] 오브젝트에 업무 엔티티 적용


NOTE: 오브젝트에는 하나의 업무 엔티티만 연결될 수 있습니다.



== 개체에서 업무 엔티티 제거

개체 또는 개체에서 업무 엔티티를 제거하려면 객체를 쿼리하고 선택하고 * Bulk Actions * 를 클릭한 다음 _ Remove Annotation _ 을 선택합니다. 업무 엔티티 주석을 선택하고 * 삭제 * 를 클릭합니다.
