---
sidebar: sidebar 
permalink: task_dc_hpe_nimble.html 
keywords: data collector, HP Nimble, HP, HPE, Alletra 6000 
summary: 'HP Enterprise Alletra 6000(이전의 Nimble) 데이터 수집기 구성' 
---
= HPE Alletra 6000 데이터 수집기


[role="lead"]
HP Enterprise Alletra 6000(이전의 Nimble) 데이터 수집기는 Alletra 6000 스토리지 어레이의 인벤토리 및 성능 데이터를 지원합니다.



== 용어

Cloud Insights는 이 수집기에서 다음 재고 정보를 가져옵니다. Cloud Insights에서 획득한 각 자산 유형에 대해 이 자산에 가장 일반적으로 사용되는 용어가 표시됩니다. 이 데이터 수집기를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

[cols="2*"]
|===
| 공급업체/모델 기간 | Cloud Insights 용어입니다 


| 스토리지 | 스토리지 


| 디스크 | 디스크 


| 볼륨 | 볼륨 


| 수영장 | 스토리지 풀 


| 이니시에이터 | 스토리지 호스트 별칭입니다 


| 컨트롤러 | 스토리지 노드 


| Fibre Channel 인터페이스 | 컨트롤러 
|===
참고: 이러한 용어 매핑은 일반적인 용어 매핑일 뿐이며 이 데이터 수집기의 모든 경우를 나타내는 것은 아닙니다.



== 요구 사항

스토리지 시스템에서 인벤토리 및 구성 데이터를 수집하려면 다음이 있어야 합니다.

* 스토리지를 설치하고 구성해야 하며 FQDN(정규화된 도메인 이름) 또는 스토리지 관리 IP 주소를 통해 클라이언트에서 연결할 수 있어야 합니다.
* 스토리지에서 NimbleOS 2.3.x 이상을 실행해야 합니다.
* "Operator" 수준 이상의 역할을 가진 어레이에 대한 유효한 사용자 이름과 암호가 있어야 합니다. "게스트" 역할에 이니시에이터 구성을 이해할 수 있는 충분한 액세스 권한이 없습니다.
* 포트 5392가 어레이에서 열려 있어야 합니다.


스토리지 어레이에서 성능 데이터를 수집하려면 다음이 있어야 합니다.

* 스토리지에서 NimbleOS 4.0.0 이상을 실행해야 합니다
* 어레이에 볼륨이 구성되어 있어야 합니다. 통계 Cloud Insights 보고서는 볼륨에 대한 유일한 성능 API NimbleOS의 것으로, 볼륨에 대한 통계에서 파생됩니다




== 구성

[cols="2*"]
|===
| 필드에 입력합니다 | 설명 


| 스토리지 관리 IP 주소입니다 | FQDN(정규화된 도메인 이름) 또는 스토리지 관리 IP 주소입니다. 


| 사용자 이름 | 스토리지의 사용자 이름입니다 


| 암호 | 어레이의 암호입니다 
|===


== 고급 구성

|===


| 필드에 입력합니다 | 설명 


| 포트 | Nimble REST API에서 사용하는 포트입니다. 기본값은 5392입니다. 


| 재고 폴링 간격(분) | 재고 조사 사이의 간격입니다. 기본값은 60분입니다. 
|===
참고: 기본 성능 폴링 간격은 300초이며 변경할 수 없습니다. 이 간격은 HPE Alletra 6000에서 유일하게 지원됩니다.
