---
sidebar: sidebar 
permalink: task_device_resolution_preferences.html 
keywords: Automatic, AR, AHR, Host, automatic device resolution, FC, Identify 
summary:  
---
= 기본 설정 탭에서 옵션 설정


[role="lead"]
장치 해상도 기본 설정 탭에서는 자동 해결 일정을 생성하고, 식별에서 포함하거나 제외할 스토리지 및 테이프 벤더 를 지정하고, DNS 조회 옵션을 설정할 수 있습니다.



=== 자동 해결 일정

자동 해상도 스케줄은 자동 장치 해상도 실행 시기를 지정할 수 있습니다.

|===


| 옵션을 선택합니다 | 설명 


| 모든 | 일, 시간 또는 분 간격으로 자동 장치 해상도를 실행하려면 이 옵션을 사용합니다. 


| 매일 | 이 옵션을 사용하여 매일 특정 시간에 자동 장치 해상도를 실행할 수 있습니다. 


| 수동 | 이 옵션은 자동 장치 해상도만 수동으로 실행할 때 사용합니다. 


| 모든 환경은 변동합니다 | 이 옵션을 사용하면 환경에 변화가 있을 때마다 자동 장치 해상도를 실행할 수 있습니다. 
|===
_manually_를 지정하면 야간 자동 장치 해결이 비활성화됩니다.



=== DNS 처리 옵션

DNS 처리 옵션을 사용하여 다음 기능을 선택할 수 있습니다.

* DNS 조회 결과 처리가 활성화되면 DNS 이름 목록을 추가하여 확인된 장치에 추가할 수 있습니다.
* IP 자동 확인: 을 선택하여 DNS 조회를 사용하여 NFS 공유에 액세스하는 iSCSI 이니시에이터 및 호스트에 대해 자동 호스트 확인을 활성화할 수 있습니다. 이 옵션을 지정하지 않으면 FC 기반 해상도만 수행됩니다.
* 호스트 이름에 밑줄을 허용하고 결과에 표준 포트 별칭 대신 "연결됨" 별칭을 사용하도록 선택할 수 있습니다.




=== 특정 스토리지 및 테이프 공급업체 포함 또는 제외

자동 해결을 위해 특정 스토리지 및 테이프 공급업체를 포함하거나 제외할 수 있습니다. 예를 들어 특정 호스트가 기존 호스트가 되어 새 환경에서 제외되어야 한다는 것을 알고 있는 경우 특정 공급업체를 제외할 수 있습니다. 이전에 제외했지만 더 이상 제외하지 않으려는 공급업체를 다시 추가할 수도 있습니다.


NOTE: 테이프에 대한 디바이스 확인 규칙은 해당 WWN의 공급업체가 공급업체 기본 설정에서 _Tape Only_로_로 설정된 WWN에만 적용됩니다.

참고 항목: link:concept_device_resolution_regex_examples.html["정규식 예제"]
