---
sidebar: sidebar 
permalink: task_dc_emc_ecs.html 
keywords: data collector, ecs, EMC 
summary: ECS 데이터 수집기 구성. 
---
= EMC ECS 데이터 수집기 구성


[role="lead"]
이 데이터 수집기는 EMC ECS 스토리지 시스템에서 인벤토리 및 성능 데이터를 가져옵니다. 구성을 위해 데이터 수집기는 ECS 서버의 IP 주소와 관리 수준 도메인 계정을 필요로 합니다.



== 용어

Cloud Insights는 ECS 데이터 수집기에서 다음과 같은 인벤토리 정보를 가져옵니다. 획득한 각 자산 유형에 대해 이 자산에 가장 일반적으로 사용되는 용어가 표시됩니다. 이 데이터 수집기를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

[cols="2*"]
|===
| 공급업체/모델 기간 | Cloud Insights 용어입니다 


| 클러스터 | 스토리지 


| 테넌트 | 스토리지 풀 


| 버킷 | 내부 볼륨 


| 디스크 | 디스크 
|===
참고: 이러한 용어 매핑은 일반적인 용어 매핑일 뿐이며 이 데이터 수집기의 모든 경우를 나타내는 것은 아닙니다.



== 요구 사항

* ECS Management Console의 IP 주소입니다
* ECS 시스템의 관리 수준 도메인 계정입니다
* 포트 443(HTTPS). ECS 시스템에서 TCP 포트 443에 대한 아웃바운드 연결이 필요합니다.
* 성능을 위해 ssh/scp 액세스를 위한 읽기 전용 사용자 이름과 암호를 사용합니다.
* 성능을 위해서는 포트 22가 필요합니다.




== 구성

[cols="2*"]
|===
| 필드에 입력합니다 | 설명 


| ECS 호스트 | ECS 시스템의 IP 주소 또는 정규화된 도메인 이름입니다 


| ECS 호스트 포트 | ECS 호스트와 통신하는 데 사용되는 포트입니다 


| ECS 공급업체 ID입니다 | ECS의 공급업체 ID입니다 


| 암호 | ECS에 사용되는 암호입니다 
|===


== 고급 구성

[cols="2*"]
|===
| 필드에 입력합니다 | 설명 


| 재고 폴링 간격(분) | 기본값은 360분입니다. 
|===


== 문제 해결

추가 정보는 에서 찾을 수 있습니다 link:concept_requesting_support.html["지원"] 페이지 또는 에 있습니다 link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Data Collector 지원 매트릭스"].
