---
sidebar: sidebar 
permalink: task_dc_amazon_ec2.html 
keywords: data collector, EC2, 
summary: Amazon EC2 데이터 수집기 구성. 
---
= Amazon EC2 데이터 수집기 구성


[role="lead"]
Cloud Insights는 Amazon EC2 데이터 수집기를 사용하여 EC2 인스턴스에서 인벤토리 및 성능 데이터를 가져옵니다.



== 요구 사항

Amazon EC2 장치에서 데이터를 수집하려면 다음 정보가 있어야 합니다.

* 다음 중 하나가 있어야 합니다.
+
** IAM 역할 인증을 사용하는 경우 Amazon EC2 클라우드 계정에 대한 * IAM Role * 입니다. IAM Role은 AWS 인스턴스에 획득 장치가 설치된 경우에만 적용됩니다.
** IAM 액세스 키 인증을 사용하는 경우 Amazon EC2 클라우드 계정의 * IAM 액세스 키 * ID 및 비밀 액세스 키


* "조직 목록" 권한이 있어야 합니다
* 포트 443 HTTPS
* EC2 인스턴스는 가상 머신 또는 (비교적 자연스럽게) 호스트로 보고할 수 있습니다. EBS 볼륨은 VM에서 사용하는 가상 디스크와 가상 디스크의 용량을 제공하는 데이터 저장소로 보고될 수 있습니다.


액세스 키는 액세스 키 ID(예: AKIAIOSFODN7EXAMPLE)와 비밀 액세스 키(예: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY)로 구성됩니다. Amazon EC2 SDK, REST 또는 쿼리 API 작업을 사용하는 경우 액세스 키를 사용하여 EC2에 만드는 프로그래밍 방식 요청에 서명할 수 있습니다. 이러한 키는 아마존에서 귀하의 계약과 함께 제공됩니다.



== 구성

아래 표에 따라 데이터 수집기 필드에 데이터를 입력합니다.

[cols="2*"]
|===
| 필드에 입력합니다 | 설명 


| AWS 지역 | AWS 지역을 선택하십시오 


| IAM 역할 | AWS의 AU에서 획득한 경우에만 사용합니다. 에 대한 자세한 내용은 아래를 참조하십시오 link:task_dc_amazon_ec2.html#iam-roles["IAM 역할"]. 


| AWS IAM 액세스 키 ID | AWS IAM 액세스 키 ID를 입력합니다. IAM Role을 사용하지 않는 경우 필수입니다. 


| AWS IAM 비밀 액세스 키 | AWS IAM 비밀 액세스 키를 입력합니다. IAM Role을 사용하지 않는 경우 필수입니다. 


| API 요청에 대한 AWS 청구 내용을 알고 있습니다 | 이 확인란을 선택하여 AWS에서 Cloud Insights 폴링으로 수행한 API 요청 비용을 청구하는지 확인하십시오. 
|===


== 고급 구성

[cols="2*"]
|===
| 필드에 입력합니다 | 설명 


| 추가 지역 포함 | 폴링에 포함할 추가 영역을 지정합니다. 


| 교차 계정 역할 | 서로 다른 AWS 계정의 리소스에 액세스하는 역할입니다. 


| 재고 폴링 간격(분) | 기본값은 60입니다 


| 태그별로 VM 필터링에 적용하려면 '제외' 또는 '포함'을 선택합니다 | 데이터를 수집할 때 태그별로 VM을 포함할지 제외할지 여부를 지정합니다. '포함'을 선택한 경우 태그 키 필드를 비워 둘 수 없습니다. 


| 태그 키 및 VM을 필터링할 값 | VM의 키 및 태그 값과 일치하는 키 및 값을 필터링하여 포함/제외할 VM(및 관련 디스크)을 선택하려면 * + 필터 태그 * 를 클릭합니다. 태그 키는 필수이며 태그 값은 선택 사항입니다. 태그 값이 비어 있으면 태그 키와 일치하는 한 VM이 필터링됩니다. 


| 성능 폴링 간격(초) | 기본값은 1800입니다 


| CloudWatch Agent 메트릭 네임스페이스 | 데이터를 수집할 EC2/EBS의 네임스페이스입니다. 이 네임스페이스에 있는 기본 메트릭의 이름이 변경되면 Cloud Insights에서 이름이 변경된 데이터를 수집하지 못할 수 있습니다. 기본 메트릭 이름은 그대로 두는 것이 좋습니다. 
|===


== IAM 액세스 키

액세스 키는 IAM 사용자 또는 AWS 계정 루트 사용자에 대한 장기 자격 증명입니다. 액세스 키는 AWS CLI 또는 AWS API(직접 또는 AWS SDK 사용)에 프로그래밍 방식으로 요청을 서명하는 데 사용됩니다.

액세스 키는 액세스 키 ID와 비밀 액세스 키의 두 부분으로 구성됩니다. IAM Role_authentication과 달리 _IAM Access Key_authentication을 사용할 때는 요청 인증을 위해 액세스 키 ID와 비밀 액세스 키를 함께 사용해야 합니다. 자세한 내용은 의 아마존 문서를 참조하십시오 link:https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html["액세스 키"].



== IAM 역할

IAM Access Key 인증과 달리 _IAM Role_authentication을 사용할 때는 생성하거나 지정하는 역할에 리소스에 액세스하는 데 필요한 적절한 권한이 있는지 확인해야 합니다.

예를 들어, 이름이 _InstanceE2ReadOnly_인 IAM 역할을 생성하는 경우 이 IAM 역할에 대한 모든 EC2 리소스에 EC2 읽기 전용 목록 액세스 권한을 부여하도록 정책을 설정해야 합니다. 또한 이 역할이 계정 간에 역할을 수행할 수 있도록 STS(보안 토큰 서비스) 액세스를 부여해야 합니다.

IAM 역할을 생성한 후 새 EC2 인스턴스 또는 기존 EC2 인스턴스를 생성할 때 연결할 수 있습니다.

IAM role_InstanceE2ReadOnly_를 EC2 인스턴스에 연결하면 IAM 역할 이름으로 인스턴스 메타데이터를 통해 임시 자격 증명을 검색하고 이 EC2 인스턴스에서 실행되는 모든 애플리케이션에서 이 자격 증명을 사용하여 AWS 리소스에 액세스할 수 있습니다.

자세한 내용은 아마존 문서를 참조하십시오 link:https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles.html["IAM 역할"].

참고: IAM 역할은 획득 장치가 AWS 인스턴스에서 실행 중인 경우에만 사용할 수 있습니다.



== Cloud Insights 주석에 아마존 태그 매핑

Amazon EC2 데이터 수집기에는 EC2에 구성된 태그로 Cloud Insights 주석을 채울 수 있는 옵션이 포함되어 있습니다. 주석 이름은 EC2 태그로 정확하게 지정해야 합니다. Cloud Insights는 항상 같은 이름의 텍스트 유형 주석을 채우고 다른 유형의 주석(숫자, 부울 등)을 채우기 위한 "최선의 시도"를 만듭니다. 주석이 다른 유형이고 데이터 수집기가 주석을 채우지 못할 경우 주석을 제거하고 텍스트 유형으로 다시 생성해야 할 수 있습니다.

AWS는 대소문자를 구분하며, Cloud Insights는 대/소문자를 구분합니다. 따라서 Cloud Insights에서 "owner"라는 주석을 생성하고 EC2에서 "owner", "Owner" 및 "owner"라는 태그를 생성하면 "owner"의 모든 EC2 변형이 Cloud Insight의 "owner" 주석에 매핑됩니다.



== 추가 지역 포함

AWS Data Collector * 고급 구성 * 섹션에서 추가 영역을 포함하도록 * 추가 영역 포함 * 필드를 쉼표 또는 세미콜론으로 구분하여 설정할 수 있습니다. 기본적으로 이 필드는 모든 미국 AWS 지역에서 수집하는 *_us-. * _ * 로 설정됩니다. on_all_regions를 수집하려면 이 필드를 * _. * _ * 로 설정합니다. 추가 영역 포함 * 필드가 비어 있으면 * 구성 * 섹션에 지정된 * AWS 지역 * 필드에 지정된 자산에 대한 데이터 수집기가 수집됩니다.



== AWS 하위 계정에서 수집 중

Cloud Insights는 단일 AWS 데이터 수집기 내에서 AWS에 대한 하위 계정 수집을 지원합니다. 이 컬렉션에 대한 구성은 AWS 환경에서 수행됩니다.

* 기본 계정 ID가 하위 계정에서 EC2 세부 정보에 액세스할 수 있도록 각 하위 계정에 AWS 역할을 구성해야 합니다.
* 각 하위 계정에는 동일한 문자열로 구성된 역할 이름이 있어야 합니다.
* Cloud Insights AWS 데이터 수집기 * 고급 구성 * 섹션의 * 교차 계정 역할 * 필드에 이 역할 이름 문자열을 입력합니다.


모범 사례: ECS 기본 계정에 AWS Predefined_AmazonEC2ReadOnlyAccess_policy를 할당하는 것이 좋습니다. 또한 데이터 소스에서 구성된 사용자는 AWS를 쿼리하기 위해 미리 정의된 _AWSOrganizationReadOnlyAccess_policy 이상을 할당해야 합니다.

Cloud Insights가 AWS 하위 계정에서 수집하도록 환경을 구성하는 방법에 대한 자세한 내용은 다음을 참조하십시오.

link:https://docs.aws.amazon.com/IAM/latest/UserGuide/tutorial_cross-account-with-roles.html["자습서: IAM 역할을 사용하여 AWS 계정 전체에서 대리인 액세스"]

link:https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_common-scenarios_aws-accounts.html["AWS 설정: 사용자가 소유한 다른 AWS 계정에서 IAM 사용자에 대한 액세스 제공"]

link:https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-user.html["IAM 사용자에 대한 권한을 위임하기 위한 역할 생성"]



== 문제 해결

이 Data Collector에 대한 추가 정보는 에서 확인할 수 있습니다 link:concept_requesting_support.html["지원"] 페이지 또는 에 있습니다 link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Data Collector 지원 매트릭스"].
