---
sidebar: sidebar 
permalink: task_cloud_insights_onboarding_1.html 
summary: Cloud Insights에 등록하고 환경을 만듭니다. 
---
= Cloud Insights 온보딩
:allow-uri-read: 


[role="lead"]
Cloud Insights로 작업하기 전에 * NetApp Cloud Central * 포털에 가입해야 합니다. NetApp Cloud Central에 이미 로그인한 경우 몇 가지 간단한 단계를 통해 Cloud Insights 무료 평가판을 시작할 수 있습니다.


toc::[]


== NetApp Cloud Central 계정 생성

NetApp 클라우드 서비스에 등록하려면 로 이동하십시오 https://cloud.netapp.com["* NetApp Cloud Central *"^] 을 클릭하고 * 가입 * 을 클릭합니다.

* 유효한 업무용 전자 메일 주소를 입력하고 암호를 선택하십시오.
* 회사 이름과 전체 이름을 입력합니다.
* 약관에 동의하고 * 등록 * 을 클릭합니다.


그런 다음 NetApp의 클라우드 오퍼링 페이지로 이동합니다.

Cloud Insights 를 선택합니다.



=== NetApp Cloud에 이미 로그인되어 있는 경우, 어떻게 해야 합니까?

NetApp Cloud Central 계정이 이미 있는 경우 에서 * 로그인 * 을 선택하면 됩니다 https://cloud.netapp.com["* NetApp Cloud Central *"^] 포털 페이지.

이메일 주소와 비밀번호를 입력합니다. 그런 다음 NetApp의 클라우드 오퍼링 페이지로 이동합니다.

Cloud Insights 를 선택합니다.



== Cloud Insights 무료 평가판을 시작합니다

Cloud Insights에 처음 로그인하는 경우 Cloud Insights 서비스 아래에서 * 무료 평가판 시작 * 을 클릭합니다. 그러면 Cloud Insights에서 회사 환경을 만듭니다.

환경 생성이 완료되면 Cloud Central 자격 증명을 사용하여 로그인하고 Cloud Insights 30일 무료 평가판을 시작할 수 있습니다. 이 평가판에서 Cloud Insights Standard Edition이 제공하는 모든 기능을 살펴볼 수 있습니다.

무료 평가판 사용 시 가능합니다 link:concept_subscribing_to_cloud_insights.html["구독을 시작합니다"] Cloud Insights에 언제든지. 구독하면 현재 구독에 따라 Cloud Insights 기능을 사용할 수 있습니다.



== 로그인 후 이동

테넌트가 생성되면 언제든지 NetApp Cloud Portal에 로그인하여 * Go to Cloud Insights * 를 클릭하면 됩니다. Cloud Insights 환경으로 바로 이동합니다.

브라우저를 Cloud Insights 환경 URL로 직접 열 수도 있습니다. 예를 들면 다음과 같습니다.

 https://<environment-name>.c01.cloudinsights.netapp.com/
URL은 각 사용자의 초대 이메일에도 포함되어 있어 간단한 액세스와 북마크 기능을 제공합니다. 사용자가 Cloud Central에 아직 로그인하지 않은 경우 로그인하라는 메시지가 표시됩니다.


NOTE: 새 사용자는 계속해서 Cloud Central에 등록하여 해당 환경 URL에 액세스할 수 있어야 합니다.

새 환경에 처음 로그인할 때 에서 로 설정하는 과정을 안내합니다 link:task_getting_started_with_cloud_insights.html["* 데이터 수집 시작 *"].



== 로그아웃하는 중입니다

Cloud Insights에서 로그아웃하려면 * 사용자 이름 * 을 클릭하고 * 로그아웃 * 을 선택합니다. Cloud Central 로그인 화면으로 돌아갑니다.


NOTE: Cloud Insights에서 로그아웃하면 Cloud Central에서 로그아웃됩니다. Cloud Central 로그인을 사용하는 다른 NetApp Cloud 서비스에서도 로그아웃됩니다.
