---
sidebar: sidebar 
permalink: task_dc_emc_scaleio.html 
keywords: data collector, scaleIO, EMC, DELL 
summary: Dell EMC ScaleIO 데이터 수집기 구성 
---
= Dell EMC ScaleIO 데이터 수집기


[role="lead"]
ScaleIO 데이터 수집기는 ScaleIO 스토리지로부터 인벤토리 정보를 수집합니다. 구성을 위해 이 데이터 수집기는 ScaleIO 게이트웨이 주소와 관리자 사용자 이름 및 암호가 필요합니다.



== 용어

Cloud Insights는 ScaleIO 데이터 수집기에서 다음 인벤토리 정보를 가져옵니다. Cloud Insights에서 획득한 각 자산 유형에 대해 이 자산에 가장 일반적으로 사용되는 용어가 표시됩니다. 이 데이터 수집기를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

[cols="2*"]
|===
| 공급업체/모델 기간 | Cloud Insights 용어입니다 


| MDM(Meta Data Manager) 클러스터 | 스토리지 


| SDS(ScaleIO 데이터 서버) | 스토리지 노드 


| 스토리지 풀 | 스토리지 풀 


| 볼륨 | 볼륨 


| 장치 | 디스크 
|===
참고: 이러한 용어 매핑은 일반적인 용어 매핑일 뿐이며 이 데이터 수집기의 모든 경우를 나타내는 것은 아닙니다.



== 요구 사항

* Admin 사용자 계정에 대한 읽기 전용 액세스
* 포트 요구 사항: HTTPS 포트 443




== 구성

[cols="2*"]
|===
| 필드에 입력합니다 | 설명 


| ScaleIO 게이트웨이 | 쉼표(,) 또는 세미콜론(;)으로 구분된 ScaleIO 게이트웨이의 IP 주소 또는 FQDN 


| 사용자 이름 | ScaleIO 디바이스에 로그인하는 데 사용되는 관리자 이름입니다 


| 암호 | ScaleIO 디바이스에 로그인하는 데 사용되는 암호입니다 
|===


== 고급 구성

인벤토리 확인란을 클릭하여 인벤토리 수집을 활성화합니다.

[cols="2*"]
|===
| 필드에 입력합니다 | 설명 


| HTTPS 포트 | 443 


| 재고 폴링 간격(분) | 기본값은 60입니다. 


| 연결 시간 초과(초) | 기본값은 60입니다. 
|===


== 문제 해결

추가 정보는 에서 찾을 수 있습니다 link:concept_requesting_support.html["지원"] 페이지 또는 에 있습니다 link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Data Collector 지원 매트릭스"].
