---
sidebar: sidebar 
permalink: task_dc_emc_datadomain.html 
keywords: data collector, Data Domain, EMC, DELL 
summary: Dell EMC Data Domain 데이터 수집기 구성 
---
= Dell EMC Data Domain 데이터 수집기


[role="lead"]
이 데이터 수집기는 Dell EMC Data Domain 중복 제거 스토리지 시스템에서 인벤토리 및 성능 정보를 수집합니다. 이 데이터 수집기를 구성하려면 따라야 하는 특정 구성 지침 및 사용 권장 사항이 있습니다.



== 용어

Cloud Insights는 Data Domain 데이터 수집기에서 다음과 같은 인벤토리 정보를 가져옵니다. Cloud Insights에서 획득한 각 자산 유형에 대해 이 자산에 가장 일반적으로 사용되는 용어가 표시됩니다. 이 데이터 수집기를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

[cols="2*"]
|===
| 공급업체/모델 기간 | Cloud Insights 용어입니다 


| 디스크 | 디스크 


| 스토리지 | 스토리지 


| FC 포트 | 포트 


| 파일 시스템 | 내부 볼륨 


| 할당량 | 할당량 


| NFS 및 CIFS 공유 | 파일 공유 
|===
참고: 이러한 용어 매핑은 일반적인 용어 매핑일 뿐이며 이 데이터 콜릿의 모든 경우를 나타내는 것은 아닙니다.



== 요구 사항

이 데이터 수집기를 구성하려면 다음 정보가 필요합니다.

* Data Domain 디바이스의 IP 주소입니다
* Data Domain 스토리지에 대한 읽기 전용 사용자 이름 및 암호
* SSH 포트 22




== 구성

[cols="2*"]
|===
| 필드에 입력합니다 | 설명 


| IP 주소입니다 | Data Domain 스토리지 시스템의 IP 주소 또는 정규화된 도메인 이름입니다 


| 사용자 이름입니다 | Data Domain 스토리지 시스템의 사용자 이름입니다 


| 암호 | Data Domain 스토리지 시스템의 암호입니다 
|===


== 고급 구성

[cols="2*"]
|===
| 필드에 입력합니다 | 설명 


| 재고 폴링 간격(분) | 재고 조사 사이의 간격입니다. 기본값은 20입니다. 


| SSH 포트 | SSH 서비스 포트입니다 
|===


== 문제 해결

이 Data Collector에 대한 추가 정보는 에서 확인할 수 있습니다 link:concept_requesting_support.html["지원"] 페이지 또는 에 있습니다 link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Data Collector 지원 매트릭스"].
