---
sidebar: sidebar 
permalink: task_dc_emc_powerstore.html 
keywords: data collector, PowerStore, EMC, DELL 
summary: Dell EMC PowerStore 데이터 수집기 구성. 
---
= Dell EMC PowerStore 데이터 수집기


[role="lead"]
EMC PowerStore 데이터 수집기는 EMC PowerStore 스토리지에서 인벤토리 정보를 수집합니다. 구성을 위해 데이터 수집기는 스토리지 프로세서의 IP 주소와 읽기 전용 사용자 이름 및 암호를 필요로 합니다.

EMC PowerStore 데이터 수집기는 PowerStore가 다른 스토리지 시스템 간에 조정하는 볼륨 간 복제 관계를 수집합니다. Cloud Insights는 각 PowerStore 클러스터에 대한 스토리지 어레이를 표시하고 해당 클러스터의 노드 및 스토리지 포트에 대한 인벤토리 데이터를 수집합니다. 스토리지 풀 또는 볼륨 데이터가 수집되지 않습니다.



== 용어

Cloud Insights는 이 데이터 수집기에서 다음 인벤토리 정보를 가져옵니다. Cloud Insights에서 획득한 각 자산 유형에 대해 이 자산에 가장 일반적으로 사용되는 용어가 표시됩니다. 이 데이터 수집기를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

[cols="2*"]
|===
| 공급업체/모델 기간 | Cloud Insights 용어입니다 


| 호스트 | 호스트 


| host_volume_mapping을 선택합니다 | host_volume_mapping을 선택합니다 


| 하드웨어("extra_details" 객체 아래에 드라이브가 있음): 드라이브 | 디스크 


| 어플라이언스 | 스토리지 풀 


| 클러스터 | 스토리지 


| 노드 | 스토리지노드 


| fc_port 를 선택합니다 | 포트 


| 볼륨 | 볼륨 


| 내부 볼륨 | 파일 시스템 
|===
참고: 이러한 용어 매핑은 일반적인 용어 매핑일 뿐이며 이 데이터 수집기의 모든 경우를 나타내는 것은 아닙니다.



== 요구 사항

이 데이터 수집기를 구성하려면 다음 정보가 필요합니다.

* 스토리지 프로세서의 IP 주소 또는 정규화된 도메인 이름입니다
* 읽기 전용 사용자 이름 및 암호




== 구성

[cols="2*"]
|===
| 필드에 입력합니다 | 설명 


| PowerStore 게이트웨이 | PowerStore 스토리지의 IP 주소 또는 정규화된 도메인 이름입니다 


| 사용자 이름 | PowerStore의 사용자 이름입니다 


| 암호 | PowerStore에 사용되는 암호입니다 
|===


== 고급 구성

[cols="2*"]
|===
| 필드에 입력합니다 | 설명 


| HTTPS 포트 | 기본값은 443입니다 


| 재고 폴링 간격(분) | 재고 조사 사이의 간격입니다. 기본값은 60분입니다. 
|===
Cloud Insight의 PowerStore 성능 수집을 통해 PowerStore의 5분 단위 소스 데이터를 사용할 수 있습니다. 따라서 Cloud Insights는 5분마다 해당 데이터를 폴링하므로 이를 구성할 수 없습니다.



== 문제 해결

이 Data Collector에 대한 추가 정보는 에서 확인할 수 있습니다 link:concept_requesting_support.html["지원"] 페이지 또는 에 있습니다 link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Data Collector 지원 매트릭스"].
