---
sidebar: sidebar 
permalink: task_dc_infinidat_infinibox.html 
keywords: data collector, infinidat, InfiniBox 
summary: Infinidat .Box 데이터 수집기 구성 중. 
---
= Infinidat .Box 데이터 수집기


[role="lead"]
Infinidat .NET(HTTP) 데이터 수집기는 Infinidat Microsoft .Box 스토리지 시스템에서 인벤토리 정보를 수집하는 데 사용됩니다.



== 용어

Cloud Insights는 Infinidat™ 서비스 목록 데이터 수집기에서 다음과 같은 인벤토리 정보를 가져옵니다. Cloud Insights에서 획득한 각 자산 유형에 대해 이 자산에 가장 일반적으로 사용되는 용어가 표시됩니다. 이 데이터 수집기를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

[cols="2*"]
|===
| 공급업체/모델 기간 | Cloud Insights 용어입니다 


| 스토리지 풀 | 스토리지 풀 


| 노드 | 컨트롤러 


| 파일 시스템 | 내부 볼륨 


| 파일 시스템 | 파일 공유 


| 파일 시스템 내보내기 | 공유 
|===


== 요구 사항

다음은 이 데이터 수집기를 구성할 때 필요한 요구 사항입니다.

* IP 주소 또는 FQDN이 필요합니다
* 관리자 사용자 ID 및 암호
* REST API를 통한 포트 443




== 구성

[cols="2*"]
|===
| 필드에 입력합니다 | 설명 


| 서비스 박스 호스트 | IP 주소 또는 Management Node의 정규화된 도메인 이름입니다 


| 사용자 이름 | 작업 영역 관리 노드에 대한 사용자 이름입니다 


| 암호 | 작업 영역 관리 노드에 대한 암호입니다 
|===


== 고급 구성

[cols="2*"]
|===
| 필드에 입력합니다 | 설명 


| TCP 포트 | TCP 포트는 Microsoft Windows Server에 연결하는 데 사용됩니다. 기본값은 443입니다. 


| 재고 폴링 간격입니다 | 재고 조사 사이의 간격입니다. 기본값은 60분입니다. 
|===


== 문제 해결

이 Data Collector에 대한 추가 정보는 에서 확인할 수 있습니다 link:concept_requesting_support.html["지원"] 페이지 또는 에 있습니다 link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Data Collector 지원 매트릭스"].
