---
sidebar: sidebar 
permalink: task_dc_emc_isilon.html 
keywords: data collector, isilon, EMC, DELL, PowerScale 
summary: 'Dell EMC PowerScale(이전의 Isilon) 데이터 수집기 구성' 
---
= Dell EMC PowerScale 데이터 수집기


[role="lead"]
Cloud Insights는 Dell EMC PowerScale(이전의 Isilon) SSH 데이터 수집기를 사용하여 PowerScale 스케일 아웃 NAS 스토리지에서 인벤토리 및 성능 데이터를 수집합니다.



== 용어

Cloud Insights는 이 데이터 수집기에서 다음 인벤토리 정보를 가져옵니다. Cloud Insights에서 획득한 각 자산 유형에 대해 이 자산에 가장 일반적으로 사용되는 용어가 표시됩니다. 이 데이터 수집기를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

[cols="2*"]
|===
| 공급업체/모델 기간 | Cloud Insights 용어입니다 


| 드라이브 | 디스크 


| 클러스터 | 스토리지 


| 노드 | 스토리지 노드 


| 파일 시스템 | 내부 볼륨 
|===
참고: 이러한 용어 매핑은 일반적인 용어 매핑일 뿐이며 이 데이터 수집기의 모든 경우를 나타내는 것은 아닙니다.



== 요구 사항

이 데이터 수집기를 구성하려면 다음 정보가 필요합니다.

* PowerScale 스토리지에 대한 관리자 권한
* PowerScale 클러스터의 IP 주소입니다
* 포트 22에 대한 SSH 액세스




== 구성

[cols="2*"]
|===
| 필드에 입력합니다 | 설명 


| IP 주소입니다 | PowerScale 클러스터의 IP 주소 또는 정규화된 도메인 이름입니다 


| 사용자 이름 | PowerScale 클러스터의 사용자 이름입니다 


| 암호 | PowerScale 클러스터에 사용되는 암호입니다 
|===


== 고급 구성

[cols="2*"]
|===
| 필드에 입력합니다 | 설명 


| 재고 폴링 간격(분) | 재고 조사 사이의 간격입니다. 기본값은 20입니다. 


| 성능 폴링 간격(초) | 성능 폴링 간격입니다. 기본값은 300입니다. 


| SSH 포트 | SSH 서비스 포트입니다. 기본값은 22입니다. 
|===


== 문제 해결

이 데이터 수집기에서 문제가 발생할 경우 다음과 같은 방법을 시도해 보십시오.



==== 인벤토리

[cols="2*"]
|===
| 문제: | 다음을 시도해 보십시오. 


| "유효하지 않은 로그인 자격 증명" 오류 메시지 "역할 기반 관리를 위해 명령이 활성화되지 않았습니다. 루트 사용자 액세스가 필요합니다." | * 사용자가 장치에서 다음 명령을 실행할 수 있는 권한이 있는지 확인합니다. > isi version osrelease > isi status -q > isi status -n > isi devices -d %s > isi license * 마법사에 사용된 자격 증명이 장치 자격 증명과 일치하는지 확인합니다 


| "내부 오류" 오류 메시지와 함께 "명령 <사용자 명령> 실행이 <현재 권한>과(와) 함께 실패했습니다. sudo 명령 실행 권한 문제" | 사용자에게 장치에서 다음 명령을 실행할 수 있는 sudo 권한이 있는지 확인합니다 
|===
추가 정보는 에서 찾을 수 있습니다 link:concept_requesting_support.html["지원"] 페이지 또는 에 있습니다 link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Data Collector 지원 매트릭스"].
