---
sidebar: sidebar 
permalink: task_dc_ibm_svc.html 
keywords: IBM, SVC,SAN 
summary: IBM SAN Volume Controller 데이터 수집기 구성. 
---
= IBM SAN Volume Controller 데이터 수집기 구성
:allow-uri-read: 


[role="lead"]
IBM SVC(SAN Volume Controller) 데이터 수집기는 SSH를 사용하여 인벤토리 및 성능 데이터를 수집하여 SVC 운영 체제를 실행하는 다양한 디바이스를 지원합니다.

지원되는 디바이스 목록에는 SVC, V7000, V5000 및 V3700과 같은 모델이 포함됩니다. 지원되는 모델 및 펌웨어 버전은 Cloud Insights 지원 매트릭스를 참조하십시오.



== 용어

Cloud Insights는 IBM SVC 데이터 수집기에서 다음 인벤토리 정보를 가져옵니다. Cloud Insights에서 획득한 각 자산 유형에 대해 이 자산에 가장 일반적으로 사용되는 용어가 표시됩니다. 이 데이터 수집기를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

[cols="2*"]
|===
| 공급업체/모델 기간 | Cloud Insights 용어입니다 


| 드라이브 | 디스크 


| 클러스터 | 스토리지 


| 노드 | 스토리지 노드 


| Mdisk 그룹 | 스토리지 풀 


| vDisk를 선택합니다 | 볼륨 


| Mdisk | 백엔드 LUN 및 경로입니다 
|===
참고: 이러한 용어 매핑은 일반적인 용어 매핑일 뿐이며 이 데이터 수집기의 모든 경우를 나타내는 것은 아닙니다.



=== 재고 요건

* 각 SVC 클러스터의 IP 주소입니다
* 포트 22를 사용할 수 있습니다
* 읽기 전용 사용자 이름 및 암호




=== 성능 요구사항

* SVC 콘솔은 모든 SVC 클러스터에 필수이며 SVC 검색 기반 패키지에 필요합니다.
* 자격 증명은 클러스터 노드에서 구성 노드로 성능 파일을 복사하는 경우에만 관리 액세스 레벨이 필요합니다.
* SSH를 통해 SVC 클러스터에 연결하고 _svctask startstats -interval 1_을 실행하여 데이터 수집을 활성화합니다
+
참고: 또는 SVC 관리 사용자 인터페이스를 사용하여 데이터 수집을 사용하도록 설정합니다.





== 구성

[cols="2*"]
|===
| 필드에 입력합니다 | 설명 


| 클러스터 IP 주소 | SVC 스토리지의 IP 주소 또는 정규화된 도메인 이름입니다 


| 재고 사용자 이름입니다 | SVC CLI의 사용자 이름입니다 


| 재고 암호 | SVC CLI의 암호입니다 
|===


== 고급 구성

[cols="2*"]
|===
| 필드에 입력합니다 | 설명 


| 재고 폴링 간격(분) | 재고 조사 사이의 간격입니다. 기본값은 40분입니다. 


| 성능 폴링 간격(초) | 성능 폴링 간격입니다. 기본값은 300초입니다. 


| 덤프된 통계 파일 정리 | 덤프된 통계 파일을 정리하려면 이 확인란을 선택합니다 
|===


== 문제 해결

이 데이터 수집기에서 문제가 발생할 경우 다음과 같은 방법을 시도해 보십시오.

[cols="2*"]
|===
| 문제: | 다음을 시도해 보십시오. 


| 오류: "구성 노드에서 실행되지 않아 명령을 시작할 수 없습니다." | 명령은 구성 노드에서 실행해야 합니다. 
|===
이 데이터 수집기에서 문제가 발생할 경우 다음과 같은 방법을 시도해 보십시오.

[cols="2*"]
|===
| 문제: | 다음을 시도해 보십시오. 


| 오류: "구성 노드에서 실행되지 않아 명령을 시작할 수 없습니다." | 명령은 구성 노드에서 실행해야 합니다. 
|===
이 Data Collector에 대한 추가 정보는 에서 확인할 수 있습니다 link:concept_requesting_support.html["지원"] 페이지 또는 에 있습니다 link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Data Collector 지원 매트릭스"].
