---
sidebar: sidebar 
permalink: task_dc_na_solidfire.html 
summary: NetApp SolidFire 데이터 수집기를 구성합니다 
keywords: data collector, queries, create 
---
= NetApp SolidFire All-Flash 어레이 데이터 수집기입니다


[role="lead"]
NetApp SolidFire All-Flash 어레이 데이터 수집기는 iSCSI 및 파이버 채널 SolidFire 구성 모두에서 인벤토리 및 성능 수집을 지원합니다.

SolidFire 데이터 수집기는 SolidFire REST API를 사용합니다. 데이터 수집기가 상주하는 수집 장치는 SolidFire 클러스터 관리 IP 주소의 TCP 포트 443에 대한 HTTPS 연결을 시작할 수 있어야 합니다. 데이터 수집기는 SolidFire 클러스터에서 REST API 쿼리를 수행할 수 있는 자격 증명이 필요합니다.



== 용어

Cloud Insights는 NetApp SolidFire All-Flash 어레이 데이터 수집기에서 다음 인벤토리 정보를 수집합니다. Cloud Insights에서 획득한 각 자산 유형에 대해 이 자산에 가장 일반적으로 사용되는 용어가 표시됩니다. 이 데이터 수집기를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

[cols="2*"]
|===
| 공급업체/모델 기간 | Cloud Insights 용어입니다 


| 드라이브 | 디스크 


| 클러스터 | 스토리지 


| 노드 | 스토리지 노드 


| 볼륨 | 볼륨 


| Fibre Channel 포트입니다 | 포트 


| 볼륨 액세스 그룹, LUN 할당 | 볼륨 맵 


| iSCSI 세션 | 볼륨 마스크 
|===
참고: 이러한 용어 매핑은 일반적인 용어 매핑일 뿐이며 이 데이터 수집기의 모든 경우를 나타내는 것은 아닙니다.



== 요구 사항

다음은 이 데이터 수집기를 구성하기 위한 요구 사항입니다.

* 관리 가상 IP 주소
* 읽기 전용 사용자 이름 및 자격 증명
* 포트 443




== 구성

[cols="2*"]
|===
| 필드에 입력합니다 | 설명 


| 관리 가상 IP 주소(MVIP) | SolidFire 클러스터의 관리 가상 IP 주소입니다 


| 사용자 이름 | SolidFire 클러스터에 로그인하는 데 사용되는 이름입니다 


| 암호 | SolidFire 클러스터에 로그인하는 데 사용되는 암호입니다 
|===


== 고급 구성

[cols="2*"]
|===
| 필드에 입력합니다 | 설명 


| 연결 유형 | 연결 유형을 선택합니다 


| 통신 포트 | NetApp API에 사용되는 포트입니다 


| 재고 폴링 간격(분) | 기본값은 20분입니다 


| 성능 폴링 간격(초) | 기본값은 300초입니다 
|===


== 문제 해결

SolidFire에서 오류를 보고하면 다음과 같이 Cloud Insights에 표시됩니다.

_ 데이터 검색을 시도하는 동안 SolidFire 장치로부터 오류 메시지가 수신되었습니다. 호출은 <method>(<parameterString> )이었습니다. 장치의 오류 메시지는 다음과 같습니다(장치 설명서 확인). <MESSAGE> _

여기서,

* 메소드>는 GET 또는 PUT와 같은 HTTP 메소드 입니다.
* parameterString>은 REST 호출에 포함된 쉼표로 구분된 매개 변수 목록입니다.
* message>는 오류 메시지로 반환된 장치와 상관없이 표시됩니다.


이 Data Collector에 대한 추가 정보는 에서 확인할 수 있습니다 link:concept_requesting_support.html["지원"] 페이지 또는 에 있습니다 link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Data Collector 지원 매트릭스"].
