---
sidebar: sidebar 
permalink: task_dc_emc_vnx_unified.html 
keywords: data collector, VNX, EMC, Dell 
summary: VNX Data Collector 구성 
---
= Dell EMC VNX Unified 데이터 수집기 구성


[role="lead"]
구성을 위해 Dell EMC VNX Unified(SSH) 데이터 수집기는 Control Station의 IP 주소와 읽기 전용 사용자 이름 및 암호를 필요로 합니다.



== 용어

Cloud Insights는 이 데이터 수집기에서 다음 인벤토리 정보를 가져옵니다. Cloud Insights에서 획득한 각 자산 유형에 대해 이 자산에 가장 일반적으로 사용되는 용어가 표시됩니다. 이 데이터 수집기를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

[cols="2*"]
|===
| 공급업체/모델 기간 | Cloud Insights 용어입니다 


| 디스크 | 디스크 


| 디스크 폴더 | 디스크 그룹 


| 파일 시스템 | 내부 볼륨 


| 스토리지 | 스토리지 


| 스토리지 프로세서 | 스토리지 노드 


| 스토리지 풀, RAID 그룹 | 스토리지 풀 


| LUN을 클릭합니다 | 볼륨 


| Data Mover입니다 | 컨트롤러 


| Data Mover에 마운트된 파일 시스템입니다 | 파일 공유 


| CIFS 및 NFS 엑스포트 | 공유 


| 디스크 볼륨 | 백엔드 LUN 
|===


== 요구 사항

VNX(SSH) 데이터 수집기를 구성하려면 다음이 필요합니다.

* Celerra Control Station에 대한 VNX IP 주소 및 자격 증명
* 읽기 전용 사용자 이름 및 암호.
* 데이터 수집기는 DART OS NAS 헤드를 활용하여 백엔드 스토리지에 대해 NaviCLI/NaviSecCLI 명령을 실행할 수 있습니다




== 구성

[cols="2*"]
|===
| 필드에 입력합니다 | 설명 


| VNX IP 주소입니다 | VNX Control Station의 IP 주소 또는 정규화된 도메인 이름입니다 


| 사용자 이름 | VNX Control Station의 사용자 이름입니다 


| 암호 | VNX Control Station의 암호입니다 
|===


== 고급 구성

[cols="2*"]
|===
| 필드에 입력합니다 | 설명 


| 재고 폴링 간격(분) | 재고 조사 사이의 간격입니다. 기본값은 40분입니다. 


| 성능 폴링 간격(초). | 성능 폴링 간격입니다. 기본값은 300초입니다. 
|===


== 문제 해결

이 Data Collector에 대한 추가 정보는 에서 확인할 수 있습니다 link:concept_requesting_support.html["지원"] 페이지 또는 에 있습니다 link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Data Collector 지원 매트릭스"].
