---
sidebar: sidebar 
permalink: task_dc_na_cdot.html 
keywords: data collector, ontap, ontap, CDOT 
summary: ONTAP 데이터 수집기 
---
= NetApp ONTAP 데이터 관리 소프트웨어 데이터 수집기


[role="lead"]
이 데이터 수집기는 ONTAP 계정에서 읽기 전용 API 호출을 사용하여 ONTAP를 실행하는 스토리지 시스템에서 인벤토리 및 성능 데이터를 가져옵니다. 또한 이 데이터 수집기는 지원을 가속화하기 위해 클러스터 응용 프로그램 레지스트리에 레코드를 만듭니다.



== 용어

Cloud Insights는 ONTAP 데이터 수집기에서 인벤토리 및 성능 데이터를 가져옵니다. 획득한 각 자산 유형에 대해 자산에 가장 일반적으로 사용되는 용어가 표시됩니다. 이 데이터 수집기를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

[cols="2*"]
|===
| 공급업체/모델 기간 | Cloud Insights 용어입니다 


| 디스크 | 디스크 


| RAID 그룹 | 디스크 그룹 


| 클러스터 | 스토리지 


| 노드 | 스토리지 노드 


| 집계 | 스토리지 풀 


| LUN을 클릭합니다 | 볼륨 


| 볼륨 | 내부 볼륨 
|===


== ONTAP 데이터 관리 용어

다음 용어는 ONTAP 데이터 관리 스토리지 자산 랜딩 페이지에서 찾을 수 있는 오브젝트 또는 참조에 적용됩니다. 이러한 용어 중 다수는 다른 데이터 수집기에도 적용됩니다.



=== 스토리지

* 모델 – 이 클러스터 내에서 쉼표로 구분된 고유한 개별 노드 모델 이름의 목록입니다. 클러스터의 모든 노드가 동일한 모델 유형인 경우 하나의 모델 이름만 표시됩니다.
* 공급업체 - 동일한 공급업체 이름 새 데이터 소스를 구성하는 경우 표시됩니다.
* 일련 번호 – 스토리지 일련 번호입니다. ONTAP 데이터 관리와 같은 클러스터 아키텍처 스토리지 시스템에서 이 일련 번호는 개별 "스토리지 노드" 일련 번호보다 덜 유용할 수 있습니다.
* IP – 일반적으로 데이터 소스에 구성된 IP 또는 호스트 이름이 됩니다.
* 마이크로코드 버전 – 펌웨어.
* 물리적 용량 – 역할에 관계없이 시스템의 모든 물리적 디스크에 대한 기본 2의 합계.
* 지연 시간 – 읽기 및 쓰기 모두에서 호스트에서 발생하는 워크로드를 나타냅니다. Cloud Insights는 이러한 가치를 직접 소싱하는 것이 가장 바람직하지만, 이는 종종 그렇지 않습니다. 이러한 기능을 제공하는 스토리지 대신 Cloud Insights는 일반적으로 개별 내부 볼륨의 통계에서 파생된 IOP 가중 계산을 수행합니다.
* 처리량 – 내부 볼륨에서 집계됩니다. 관리 - 장치의 관리 인터페이스에 대한 하이퍼링크가 포함될 수 있습니다. 인벤토리 보고의 일부로 Cloud Insights 데이터 소스에서 프로그래밍 방식으로 만듭니다.




=== 스토리지 풀

* 스토리지 – 이 풀이 상주하는 스토리지 시스템입니다. 필수입니다.
* 형식 - 가능성 목록 목록의 설명 값입니다. 일반적으로 "집계" 또는 "RAID 그룹"이 됩니다.
* 노드 – 이 스토리지 배열의 아키텍처가 특정 스토리지 노드에 속해 있는 경우, 이 스토리지 배열의 이름은 해당 랜딩 페이지의 하이퍼링크로 표시됩니다.
* Flash Pool 사용 – 예/아니요 가치 – 이 SATA/SAS 기반 풀에 캐싱 가속화에 SSD가 사용됩니까?
* 중복 – RAID 레벨 또는 보호 체계. RAID_DP는 이중 패리티이고, RAID_TP는 삼중 패리티입니다.
* 용량 – 이 값은 논리적 사용 용량, 가용 용량 및 총 논리적 용량, 그리고 이 용량 전체에서 사용된 비율입니다.
* 과도하게 커밋된 용량 – 효율성 기술을 사용하여 스토리지 풀의 논리적 용량보다 큰 볼륨 또는 내부 볼륨 용량의 합계를 할당한 경우 여기에 있는 백분율 값은 0%보다 큽니다.
* 스냅샷 – 스토리지 풀 아키텍처가 스냅샷 전용 영역에 해당 용량의 일부를 할당하는 경우 사용된 스냅샷 용량 및 총 용량입니다. MetroCluster 구성의 ONTAP는 이 문제를 나타낼 가능성이 높지만, 다른 ONTAP 구성은 더 적습니다.
* 사용률 – 이 스토리지 풀에 용량을 제공하는 모든 디스크의 사용 중 가장 높은 비율을 나타내는 백분율 값입니다. 디스크 사용률이 반드시 스토리지 성능과 강력한 상관 관계가 있는 것은 아닙니다. 호스트 기반 워크로드가 없을 경우 디스크 재구축, 중복 제거 작업 등으로 인해 사용률이 높을 수 있습니다. 또한 많은 스토리지의 복제 구현으로 인해 디스크 사용률이 높아지고 내부 볼륨 또는 볼륨 작업 부하로 표시되지 않을 수 있습니다.
* IOPS – 이 스토리지 풀에 용량을 제공하는 모든 디스크의 IOPS 합계입니다. 처리량 – 이 스토리지 풀에 용량을 제공하는 모든 디스크의 총 처리량입니다.




=== 스토리지 노드

* 스토리지 – 이 노드가 속한 스토리지 시스템입니다. 필수입니다.
* HA 파트너 – 노드가 1개 노드로 페일오버되고 다른 1개 노드만 페일오버되는 플랫폼에서는 일반적으로 이 노드에 표시됩니다.
* 상태 - 노드의 상태입니다. 배열이 데이터 소스에 의해 인벤토리를 작성할 수 있을 만큼 양호한 경우에만 사용할 수 있습니다.
* 모델 - 노드의 모델 이름입니다.
* 버전 - 디바이스의 버전 이름입니다.
* 일련 번호 - 노드 일련 번호입니다.
* 메모리 – 사용 가능한 경우 베이스 2 메모리.
* 사용률 – ONTAP에서는 독점 알고리즘의 컨트롤러 스트레스 인덱스입니다. 성능 폴링이 발생할 때마다 WAFL 디스크 경합 또는 평균 CPU 사용률의 증가인 0에서 100% 사이의 숫자가 보고됩니다. 값이 50%를 넘는 지속적인 값이 관찰될 경우, 이는 낮은 크기 조정을 나타내는 것입니다. 컨트롤러/노드가 충분히 크지 않거나 회전 디스크가 부족하여 쓰기 워크로드를 흡수할 수 없습니다.
* IOPS – 노드 개체의 ONTAP ZAPI 호출에서 직접 파생됩니다.
* 지연 시간 – 노드 개체의 ONTAP ZAPI 호출에서 직접 파생됩니다.
* 처리량 – 노드 개체의 ONTAP ZAPI 호출에서 직접 파생됩니다.
* 프로세서 - CPU 수입니다.




== 요구 사항

다음은 이 데이터 수집기를 구성하고 사용하기 위한 요구 사항입니다.

* 읽기 전용 API 호출에 대해 구성된 관리자 계정에 대한 액세스 권한이 있어야 합니다.
* 계정 세부 정보에는 사용자 이름 및 암호가 포함됩니다.
* 포트 요구 사항: 80 또는 443
* 계정 권한:
+
** 기본 SVM에 대해 ontapi 애플리케이션에 대한 읽기 전용 역할 이름
** 추가적인 선택적 쓰기 권한이 필요할 수 있습니다. 아래의 사용 권한에 대한 참고 사항을 참조하십시오.


* ONTAP 라이센스 요구 사항:
+
** 파이버 채널 검색에 필요한 FCP 라이센스 및 매핑/마스킹된 볼륨






== 구성

[cols="2*"]
|===
| 필드에 입력합니다 | 설명 


| NetApp 관리 IP | NetApp 클러스터의 IP 주소 또는 정규화된 도메인 이름입니다 


| 사용자 이름 | NetApp 클러스터의 사용자 이름입니다 


| 암호 | NetApp 클러스터의 암호입니다 
|===


== 고급 구성

[cols="2*"]
|===
| 필드에 입력합니다 | 설명 


| 연결 유형 | HTTP(기본 포트 80) 또는 HTTPS(기본 포트 443)를 선택합니다. 기본값은 HTTPS입니다 


| 통신 포트를 재정의합니다 | 기본값을 사용하지 않으려면 다른 포트를 지정하십시오 


| 재고 폴링 간격(분) | 기본값은 60분입니다. 


| HTTPS용 TLS | HTTPS를 사용하는 경우에만 TLS를 프로토콜로 허용합니다 


| 자동으로 넷그룹을 조회합니다 | 엑스포트 정책 규칙에 대한 자동 넷그룹 조회를 설정합니다 


| 넷그룹 확장 | 넷그룹 확장 전략. file_or_shell_을 선택합니다. 기본값은 _shell_입니다. 


| HTTP 읽기 제한 시간(초 | 기본값은 30입니다 


| 응답을 UTF-8로 강제 적용합니다 | 데이터 수집기 코드가 CLI의 응답을 UTF-8로 해석하도록 합니다 


| 성능 폴링 간격(초) | 기본값은 900초입니다. 


| 고급 카운터 데이터 수집 | ONTAP 통합을 활성화합니다. ONTAP 고급 카운터 데이터를 폴에 포함하려면 이 옵션을 선택합니다. 목록에서 원하는 카운터를 선택합니다. 
|===


== 사용 권한에 대한 참고 사항

많은 Cloud Insights의 ONTAP 대시보드는 고급 ONTAP 카운터를 사용하기 때문에 데이터 수집기 고급 구성 섹션에서 * 고급 카운터 데이터 수집 * 을 활성화해야 합니다.

또한 ONTAP API에 대한 쓰기 권한이 활성화되어 있는지도 확인해야 합니다. 이 경우 일반적으로 필요한 권한이 있는 클러스터 수준의 계정이 필요합니다.

클러스터 수준에서 Cloud Insights에 대한 로컬 계정을 생성하려면 클러스터 관리 관리자 사용자 이름/암호를 사용하여 ONTAP에 로그인하고 ONTAP 서버에서 다음 명령을 실행합니다.

. 다음 명령을 사용하여 읽기 전용 역할을 만듭니다.
+
....
security login role create -role ci_readonly -cmddirname DEFAULT -access readonly
security login role create -role ci_readonly -cmddirname security -access readonly
security login role create -role ci_readonly -access all -cmddirname “cluster application-record create”
....
. 다음 명령을 사용하여 읽기 전용 사용자를 생성합니다. create 명령을 실행하면 이 사용자의 암호를 입력하라는 메시지가 표시됩니다.
+
 security login create -username ci_user -application ontapi -authentication-method password -role ci_readonly


AD/LDAP 계정을 사용하는 경우 명령은 여야 합니다

 security login create -user-or-group-name DOMAIN\aduser/adgroup -application ontapi -authentication-method domain -role ci_readonly
그 결과로 생성되는 역할 및 사용자 로그인은 다음과 같습니다.

....
Role Command/ Access
Vserver Name Directory Query Level
---------- ------------- --------- ------------------ --------
cluster1 ci_readonly DEFAULT read only
cluster1 ci_readonly security readonly
....
....
cluster1::security login> show
Vserver: cluster1
Authentication Acct
UserName    Application   Method      Role Name      Locked
---------   -------      ----------- -------------- --------
ci_user     ontapi      password    ci_readonly   no
....


== 문제 해결

이 데이터 수집기에서 문제가 발생할 경우 다음과 같은 방법을 시도해 보십시오.



==== 인벤토리

[cols="2*"]
|===
| 문제: | 다음을 시도해 보십시오. 


| 수신 401 HTTP 응답 또는 13003 ZAPI 오류 코드 및 ZAPI는 "불충분한 권한" 또는 "이 명령에 대해 인증되지 않음"을 반환합니다. | 사용자 이름과 암호, 사용자 권한/권한을 확인합니다. 


| 클러스터 버전이 8.1 미만임 | 클러스터 최소 지원 버전은 8.1입니다. 최소 지원 버전으로 업그레이드하십시오. 


| ZAPI는 "cluster role is not cluster_mgmt LIF" 를 반환합니다. | AU는 클러스터 관리 IP와 통신해야 합니다. IP를 확인하고 필요한 경우 다른 IP로 변경합니다 


| 오류: “7 모드 파일러는 지원되지 않습니다.” | 이 데이터 수집기를 사용하여 7 모드 파일러를 검색할 경우 이 문제가 발생할 수 있습니다. 대신 IP를 cDOT 클러스터를 가리키도록 변경합니다. 


| 재시도 후 ZAPI 명령이 실패합니다 | AU가 클러스터와 통신 문제를 겪고 있습니다. 네트워크, 포트 번호 및 IP 주소를 확인합니다. 또한 사용자는 AU 시스템의 명령줄에서 명령을 실행해야 합니다. 


| AU가 HTTP를 통해 ZAPI에 연결하지 못했습니다 | ZAPI 포트가 일반 텍스트를 허용하는지 확인합니다. AU가 SSL 소켓에 일반 텍스트를 보내려고 하면 통신이 실패합니다. 


| SSLException 과 통신이 실패합니다 | AU가 파일러의 일반 텍스트 포트로 SSL을 전송하려고 합니다. ZAPI 포트가 SSL을 허용하는지 또는 다른 포트를 사용하는지 확인합니다. 


| 추가 연결 오류: ZAPI 응답에는 오류 코드 13001, "데이터베이스가 열려 있지 않습니다." ZAPI 오류 코드가 60이고 응답에는 "API가 시간에 완료되지 않았습니다."가 포함되어 있습니다. ZAPI 응답에는 "initialize_session() returned NULL environment" ZAPI가 포함되어 있습니다. ZAPI 오류 코드는 14007이고 응답에는 "노드가 정상 상태가 아닙니다"가 포함되어 있습니다. | 네트워크, 포트 번호 및 IP 주소를 확인합니다. 또한 사용자는 AU 시스템의 명령줄에서 명령을 실행해야 합니다. 
|===


==== 성능

[cols="2*"]
|===
| 문제: | 다음을 시도해 보십시오. 


| “ZAPI에서 성능을 수집하지 못했습니다.” 오류 | 일반적으로 perf stat이 실행되지 않기 때문입니다. 각 노드에서 >_system node systemshell-node * -command “spmctl -h cmd –stop;spmctl -h cmd –exec” _ 명령을 실행합니다 
|===
추가 정보는 에서 찾을 수 있습니다 link:concept_requesting_support.html["지원"] 페이지 또는 에 있습니다 link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Data Collector 지원 매트릭스"].
