---
sidebar: sidebar 
permalink: task_dc_ibm_powervm.html 
keywords: IBM, powerVM, 
summary: IBM PowerVM 데이터 수집기 구성. 
---
= IBM PowerVM 데이터 수집기 구성
:allow-uri-read: 


[role="lead"]
IBM PowerVM(SSH) 데이터 수집기는 하드웨어 관리 콘솔(HMC)에서 관리하는 IBM POWER 하드웨어 인스턴스에서 실행되는 가상 파티션에 대한 정보를 수집하는 데 사용됩니다.



== 용어

Cloud Insights는 IBM POWER 하드웨어 인스턴스에서 실행되는 가상 파티션에서 인벤토리 정보를 가져옵니다. 획득한 각 자산 유형에 대해 자산에 가장 일반적으로 사용되는 용어가 표시됩니다. 이 데이터 수집기를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

[cols="2*"]
|===
| 공급업체/모델 기간 | Cloud Insights 용어입니다 


| hdisk | 가상 디스크 


| 관리 대상 시스템 | 호스트 


| LPAR, VIO 서버 | 가상 머신 


| 볼륨 그룹 | 데이터 저장소 


| 물리적 볼륨 | LUN을 클릭합니다 
|===
참고: 이러한 용어 매핑은 일반적인 용어 매핑일 뿐이며 이 데이터 수집기의 모든 경우를 나타내는 것은 아닙니다.



== 요구 사항

이 데이터 수집기를 구성하고 사용하려면 다음 요구 사항을 충족해야 합니다.

* HMC(Hardware Management Console)의 IP 주소
* SSH를 통해 HMC(Hardware Management Console)에 대한 액세스를 제공하는 사용자 이름 및 암호입니다
* 포트 요구 사항 SSH-22
* 모든 관리 시스템 및 논리 파티션 보안 도메인에 대한 권한을 봅니다
+
또한 HMC 구성에 대한 보기 권한과 HMC 콘솔 보안 그룹화를 위한 VPD 정보를 수집할 수 있는 기능도 있어야 합니다. 또한 사용자는 논리 파티션 보안 그룹화를 통해 가상 IO 서버 명령 액세스를 허용해야 합니다. 작업자의 역할에서 시작하여 모든 역할을 제거하는 것이 가장 좋습니다. HMC의 읽기 전용 사용자는 AIX 호스트에서 프록시 명령을 실행할 권한이 없습니다.

* IBM 모범 사례는 두 개 이상의 HMCS를 통해 디바이스를 모니터링하는 것입니다. 이렇게 하면 OnCommand Insight에서 중복된 디바이스를 보고할 수 있으므로 이 데이터 수집기의 고급 구성에 있는 "장치 제외" 목록에 중복 디바이스를 추가하는 것이 좋습니다.




== 구성

[cols="2*"]
|===
| 필드에 입력합니다 | 설명 


| HMC(Hardware Management Console) IP 주소입니다 | PowerVM 하드웨어 관리 콘솔의 IP 주소 또는 정규화된 도메인 이름입니다 


| HMC 사용자 | 하드웨어 관리 콘솔의 사용자 이름입니다 


| 암호 | 하드웨어 관리 콘솔에 사용되는 암호입니다 
|===


== 고급 구성

[cols="2*"]
|===
| 필드에 입력합니다 | 설명 


| 재고 폴링 간격(분) | 재고 조사 사이의 간격입니다. 기본값은 20분입니다. 


| SSH 포트 | SSH에서 PowerVM에 사용되는 포트입니다 


| 암호 | 하드웨어 관리 콘솔에 사용되는 암호입니다 


| 재시도 횟수 | 인벤토리 재시도 횟수입니다 


| 장치 제외 | 제외할 장치 ID 또는 표시 이름의 쉼표로 구분된 목록입니다 
|===


== 문제 해결

이 Data Collector에 대한 추가 정보는 에서 확인할 수 있습니다 link:concept_requesting_support.html["지원"] 페이지 또는 에 있습니다 link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Data Collector 지원 매트릭스"].
