---
sidebar: sidebar 
permalink: task_device_resolution_rules.html 
keywords: Automatic, AR, AHR, Host, automatic device resolution 
summary: 장치 해결 기능은 사용자 환경의 성능 및 인벤토리를 정확하게 추적하는 데 도움이 됩니다. 
---
= 장치 해상도 규칙
:allow-uri-read: 


[role="lead"]
디바이스 확인 규칙을 생성하여 현재 Cloud Insights에서 자동으로 식별되지 않는 호스트, 스토리지 및 테이프를 식별합니다. 생성하는 규칙은 현재 환경에 있는 디바이스를 식별하고 유사한 디바이스를 환경에 추가할 때 식별합니다.



== 장치 해상도 규칙을 만드는 중입니다

규칙을 만들 때는 먼저 규칙이 실행되는 정보의 소스, 정보를 추출하는 데 사용되는 메서드 및 DNS 조회가 규칙의 결과에 적용되는지 여부를 확인합니다.

[cols="2*"]
|===


| 장치를 식별하는 데 사용되는 소스입니다 | * 포함된 호스트 또는 테이프 이름이 포함된 스토리지 별칭 * 포함된 호스트 또는 테이프 이름이 포함된 스위치 별칭 * 포함된 호스트 이름이 포함된 영역 이름 


| 소스에서 디바이스 이름을 추출하는 데 사용되는 방법입니다 | 현재 상태 그대로 * (SRM에서 이름 추출) * 구분 기호 * 정규식 


| DNS 조회 | DNS를 사용하여 호스트 이름을 확인할지 여부를 지정합니다 
|===
자동 해결 규칙 탭에서 규칙을 만듭니다. 다음 단계에서는 규칙 생성 프로세스를 설명합니다.

.절차를 참조하십시오
. 관리 > 장치 해상도 * 를 클릭합니다
. 자동 해결 규칙 * 탭에서 * + 호스트 규칙 * 또는 * + 테이프 규칙 * 을 클릭합니다.
+
해상도 규칙 * 화면이 표시됩니다.

+

NOTE: 정규식 만들기에 대한 도움말과 예제를 보려면 _View Matching criteria_링크를 클릭하십시오.

. Type * 목록에서 식별하려는 장치를 선택합니다.
+
Host_or_Tape_를 선택할 수 있습니다.

. 소스 * 목록에서 호스트를 식별하는 데 사용할 소스를 선택합니다.
+
선택한 소스에 따라 Cloud Insights에 다음 응답이 표시됩니다.

+
.. * Zone * 은 Cloud Insights에서 식별해야 하는 영역 및 WWN을 나열합니다.
.. * SRM * 에는 Cloud Insights에서 식별해야 하는 식별되지 않은 별칭이 나열됩니다
.. 스토리지 별칭 * 에는 Cloud Insights에서 식별해야 하는 스토리지 별칭 및 WWN이 나열됩니다
.. * 스위치 별칭 * 은 Cloud Insights로 식별해야 하는 스위치 별칭을 나열합니다


. Method* 목록에서 호스트를 식별하기 위해 사용할 방법을 선택합니다.
+
|===


| 출처 | 방법 


| SRM | As As As - 구분 기호, 정규식 


| 스토리지 별칭입니다 | 구분 기호, 정규식 


| 별칭 전환 | 구분 기호, 정규식 


| 존 | 구분 기호, 정규식 
|===
+
** Delimiters를 사용하는 규칙에는 구분 기호 및 호스트 이름의 최소 길이가 필요합니다. 호스트 이름의 최소 길이는 Cloud Insights에서 호스트를 식별하는 데 사용해야 하는 문자 수입니다. Cloud Insights는 길이가 길거나 긴 호스트 이름에 대해서만 DNS 조회를 수행합니다.
+
Delimiters를 사용하는 규칙의 경우 입력 문자열은 구분 기호로 토큰화되며 인접한 토큰을 여러 개 조합하여 호스트 이름 후보 목록이 만들어집니다. 그런 다음 목록이 가장 큰 것부터 가장 작은 순서로 정렬됩니다. 예를 들어, _vipsnq03_hba3_emcp3_12ep0_의 입력 슬링에 대해 다음과 같은 결과가 나타납니다.

+
*** vipsnq03_hba3_emcp3_12ep0을 입력합니다
*** vipsnq03_hba3_emcp3
*** hba3 emc3_12ep0
*** vipsnq03_hba3
*** emc3_12ep0을 참조하십시오
*** hba3_emc3
*** vipsnq03
*** 12ep0
*** emc3
*** hba3


** 정규식을 사용하는 규칙에는 정규식, 형식 및 케이스 민감도 선택이 필요합니다.


. AR 실행 * 을 클릭하여 모든 규칙을 실행하거나, 버튼의 아래쪽 화살표를 클릭하여 생성한 규칙(그리고 AR의 마지막 전체 실행 이후 생성된 기타 규칙)을 실행합니다.
+
규칙 실행 결과는 * FC Identify * (FC 식별 *) 탭에 표시됩니다.





== 자동 장치 해상도 업데이트를 시작합니다

장치 해상도 업데이트는 마지막 전체 자동 장치 해상도 실행 이후 추가된 수동 변경 사항을 커밋합니다. 업데이트를 실행하면 장치 해상도 구성에 대한 새 수동 항목만 커밋하고 실행할 수 있습니다. 전체 장치 해상도 실행이 수행되지 않습니다.

.절차를 참조하십시오
. Cloud Insights 웹 UI에 로그인합니다.
. 관리 > 장치 해상도 * 를 클릭합니다
. 장치 해상도 * 화면에서 * AR 실행 * 버튼의 아래쪽 화살표를 클릭합니다.
. 업데이트를 시작하려면 * 업데이트 * 를 클릭합니다.




== 규칙 지원 수동 식별

이 기능은 특정 규칙 또는 규칙 목록(일회성 재정렬 포함 또는 제외)을 실행하여 알 수 없는 호스트, 스토리지 및 테이프 디바이스를 확인하려는 경우에 사용됩니다.

식별되지 않은 다수의 장치가 있고 다른 장치를 성공적으로 식별하는 여러 규칙이 있습니다.


NOTE: 소스에 호스트 또는 장치 이름의 일부만 포함되어 있는 경우 정규식 규칙을 사용하여 서식을 지정하여 누락된 텍스트를 추가합니다.

.절차를 참조하십시오
. Cloud Insights 웹 UI에 로그인합니다.
. 관리 > 장치 해상도 * 를 클릭합니다
. 파이버 채널 식별 * 탭을 클릭합니다.
+
시스템은 해상도 상태와 함께 장치를 표시합니다.

. 식별되지 않은 여러 장치를 선택합니다.
. Bulk Actions * 를 클릭하고 * Set host resolution * 또는 * Set tape resolution * 을 선택합니다.
+
성공적으로 식별된 장치의 모든 규칙 목록이 포함된 식별 화면이 표시됩니다.

. 규칙 순서를 필요에 맞는 순서로 변경합니다.
+
규칙 순서는 식별 화면에서 변경되지만 전역적으로 변경되지는 않습니다.

. 필요에 맞는 방법을 선택하십시오.


Cloud Insights는 메서드가 나타나는 순서대로 호스트 확인 프로세스를 실행하며, 맨 위에 있는 방법부터 시작합니다.

적용되는 규칙이 있으면 규칙 이름이 규칙 열에 표시되고 수동으로 식별됩니다.

관련:link:task_device_resolution_fibre_channel.html["파이버 채널 장치 해상도"]
link:task_device_resolution_ip.html["IP 장치 해상도"]
link:task_device_resolution_preferences.html["장치 해상도 기본 설정 지정"]
