---
sidebar: sidebar 
permalink: task_dc_na_amazon_fsx.html 
keywords: 'data collector, stout, fsx, fsx-netapp, Amazon, AWS, cluster, volume, share, LUN"' 
summary: NetApp ONTAP Data Collector용 Amazon FSx 
---
= NetApp ONTAP 데이터 수집기를 위한 Amazon FSx
:allow-uri-read: 


[role="lead"]
이 데이터 수집기는 NetApp ONTAP용 Amazon FSx에서 인벤토리 및 성능 데이터를 가져옵니다. 이 데이터 수집기는 Cloud Insights 서비스 지역 전체에서 점증적으로 사용할 수 있습니다. Cloud Insights 환경에서 이 수집기의 아이콘이 보이지 않으면 영업 담당자에게 문의하십시오.



== 용어

Cloud Insights는 FSx-NetApp 데이터 수집기에서 인벤토리 및 성능 데이터를 가져옵니다. 획득한 각 자산 유형에 대해 자산에 가장 일반적으로 사용되는 용어가 표시됩니다. 이 데이터 수집기를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

[cols="2*"]
|===
| 공급업체/모델 기간 | Cloud Insights 용어입니다 


| 클러스터 | 스토리지 


| LUN을 클릭합니다 | 볼륨 


| 볼륨 | 내부 볼륨 
|===


== FSX-NetApp 용어

다음 용어는 FSx-NetApp 스토리지 자산 랜딩 페이지에서 볼 수 있는 오브젝트 또는 참조에 적용됩니다. 이러한 용어 중 다수는 다른 데이터 수집기에도 적용됩니다.



=== 스토리지

* 모델 – 이 클러스터 내에서 고유한 개별 모델 이름을 쉼표로 구분한 목록입니다.
* 공급업체 – AWS
* 일련 번호 – 스토리지 일련 번호입니다.
* IP – 일반적으로 데이터 소스에 구성된 IP 또는 호스트 이름이 됩니다.
* 물리적 용량 – 역할에 관계없이 시스템의 모든 물리적 디스크에 대한 기본 2의 합계.
* 지연 시간 – 읽기 및 쓰기 모두에서 호스트에서 발생하는 워크로드를 나타냅니다. Cloud Insights는 이러한 가치를 직접 소싱하는 것이 가장 바람직하지만, 이는 종종 그렇지 않습니다. 이러한 기능을 제공하는 스토리지 대신 Cloud Insights는 일반적으로 개별 내부 볼륨의 통계에서 파생된 IOP 가중 계산을 수행합니다.
* 처리량 – 내부 볼륨에서 집계됩니다. 관리 - 장치의 관리 인터페이스에 대한 하이퍼링크가 포함될 수 있습니다. 인벤토리 보고의 일부로 Cloud Insights 데이터 소스에서 프로그래밍 방식으로 만듭니다.




=== 스토리지 풀

* 스토리지 – 이 풀이 상주하는 스토리지 시스템입니다. 필수입니다.
* 형식 - 가능성 목록 목록의 설명 값입니다. 일반적으로 "집계" 또는 "RAID 그룹"이 됩니다.
* Flash Pool 사용 – 예/아니요 가치 – 이 SATA/SAS 기반 풀에 캐싱 가속화에 SSD가 사용됩니까?
* 중복 – RAID 레벨 또는 보호 체계. RAID_DP는 이중 패리티이고, RAID_TP는 삼중 패리티입니다.
* 용량 – 이 값은 논리적 사용 용량, 가용 용량 및 총 논리적 용량, 그리고 이 용량 전체에서 사용된 비율입니다.
* 과도하게 커밋된 용량 – 효율성 기술을 사용하여 스토리지 풀의 논리적 용량보다 큰 볼륨 또는 내부 볼륨 용량의 합계를 할당한 경우 여기에 있는 백분율 값은 0%보다 큽니다.
* 스냅샷 – 스토리지 풀 아키텍처가 스냅샷 전용 영역에 해당 용량의 일부를 할당하는 경우 사용된 스냅샷 용량 및 총 용량입니다. MetroCluster 구성의 ONTAP는 이 문제를 나타낼 가능성이 높지만, 다른 ONTAP 구성은 더 적습니다.
* 사용률 – 이 스토리지 풀에 용량을 제공하는 모든 디스크의 사용 중 가장 높은 비율을 나타내는 백분율 값입니다. 디스크 사용률이 반드시 스토리지 성능과 강력한 상관 관계가 있는 것은 아닙니다. 호스트 기반 워크로드가 없을 경우 디스크 재구축, 중복 제거 작업 등으로 인해 사용률이 높을 수 있습니다. 또한 많은 스토리지의 복제 구현으로 인해 디스크 사용률이 높아지고 내부 볼륨 또는 볼륨 작업 부하로 표시되지 않을 수 있습니다.
* IOPS – 이 스토리지 풀에 용량을 제공하는 모든 디스크의 IOPS 합계입니다. 처리량 – 이 스토리지 풀에 용량을 제공하는 모든 디스크의 총 처리량입니다.




== 요구 사항

다음은 이 데이터 수집기를 구성하고 사용하기 위한 요구 사항입니다.

* 읽기 전용 API 호출에 대해 구성된 관리자 계정에 대한 액세스 권한이 있어야 합니다.
* 계정 세부 정보에는 사용자 이름 및 암호가 포함됩니다.
* 포트 요구 사항: 80 또는 443




== 구성

[cols="2*"]
|===
| 필드에 입력합니다 | 설명 


| NetApp 관리 IP | NetApp 클러스터의 IP 주소 또는 정규화된 도메인 이름입니다 


| 사용자 이름 | NetApp 클러스터의 사용자 이름입니다 


| 암호 | NetApp 클러스터의 암호입니다 
|===


== 문제 해결

이 데이터 수집기에서 문제가 발생할 경우 다음과 같은 방법을 시도해 보십시오.



==== 인벤토리

[cols="2*"]
|===
| 문제: | 다음을 시도해 보십시오. 


| 수신 401 HTTP 응답 또는 13003 ZAPI 오류 코드 및 ZAPI는 "불충분한 권한" 또는 "이 명령에 대해 인증되지 않음"을 반환합니다. | 사용자 이름과 암호, 사용자 권한/권한을 확인합니다. 


| ZAPI는 "cluster role is not cluster_mgmt LIF" 를 반환합니다. | AU는 클러스터 관리 IP와 통신해야 합니다. IP를 확인하고 필요한 경우 다른 IP로 변경합니다 


| 재시도 후 ZAPI 명령이 실패합니다 | AU가 클러스터와 통신 문제를 겪고 있습니다. 네트워크, 포트 번호 및 IP 주소를 확인합니다. 또한 사용자는 AU 시스템의 명령줄에서 명령을 실행해야 합니다. 


| AU가 HTTP를 통해 ZAPI에 연결하지 못했습니다 | ZAPI 포트가 일반 텍스트를 허용하는지 확인합니다. AU가 SSL 소켓에 일반 텍스트를 보내려고 하면 통신이 실패합니다. 


| SSLException 과 통신이 실패합니다 | AU가 파일러의 일반 텍스트 포트로 SSL을 전송하려고 합니다. ZAPI 포트가 SSL을 허용하는지 또는 다른 포트를 사용하는지 확인합니다. 


| 추가 연결 오류: ZAPI 응답에는 오류 코드 13001, "데이터베이스가 열려 있지 않습니다." ZAPI 오류 코드가 60이고 응답에는 "API가 시간에 완료되지 않았습니다."가 포함되어 있습니다. ZAPI 응답에는 "initialize_session() returned NULL environment" ZAPI가 포함되어 있습니다. ZAPI 오류 코드는 14007이고 응답에는 "노드가 정상 상태가 아닙니다"가 포함되어 있습니다. | 네트워크, 포트 번호 및 IP 주소를 확인합니다. 또한 사용자는 AU 시스템의 명령줄에서 명령을 실행해야 합니다. 
|===
추가 정보는 에서 찾을 수 있습니다 link:concept_requesting_support.html["지원"] 페이지 또는 에 있습니다 link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Data Collector 지원 매트릭스"].
