---
sidebar: sidebar 
permalink: task_dc_ms_hyperv.html 
keywords: data collector, Microsoft, Hyper-V 
summary: Microsoft Hyper-V 데이터 수집기 구성. 
---
= Microsoft Hyper-V 데이터 수집기


[role="lead"]
Microsoft Hyper-V 데이터 수집기는 가상화된 서버 컴퓨팅 환경에서 인벤토리 및 성능 데이터를 가져옵니다.



== 용어

Cloud Insights는 Microsoft Hyper-V(WMI)에서 다음 인벤토리 정보를 가져옵니다. Cloud Insights에서 획득한 각 자산 유형에 대해 이 자산에 가장 일반적으로 사용되는 용어가 표시됩니다. 이 데이터 수집기를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

[cols="2*"]
|===
| 공급업체/모델 기간 | Cloud Insights 용어입니다 


| 가상 하드 디스크 | 가상 디스크 


| 호스트 | 호스트 


| 가상 머신 | 가상 머신 


| CSV(Cluster Shared Volumes), 파티션 볼륨 | 데이터 저장소 


| 인터넷 SCSI 장치, 다중 경로 SCSI LUN | LUN을 클릭합니다 


| Fibre Channel 포트 | 포트 
|===
참고: 이러한 용어 매핑은 일반적인 용어 매핑일 뿐이며 이 데이터 수집기의 모든 경우를 나타내는 것은 아닙니다.



== 요구 사항

이 데이터 수집기를 구성하려면 다음이 필요합니다.

* Hyper-V를 사용하려면 데이터 수집 및 원격 액세스/관리를 위해 포트 5985를 열어야 합니다.
* 클러스터링 그룹 노드의 IP 주소입니다
* 하이퍼바이저의 로컬 관리자 사용자 및 암호
* 관리 수준 사용자 계정
* WMI(Windows Management Instrumentation) 명령(Windows에서 설치하는 기본값)
* 포트 요구 사항: Windows 2003 및 이전 버전의 경우 1024-65535로 할당된 WMI 및 동적 TCP 포트를 통해 135번 포트 및 Windows 2008의 경우 49152-65535번 포트.
* 데이터 수집기가 IP 주소만 가리키는 경우에도 DNS 확인이 성공해야 합니다
* 각 Hyper-V 하이퍼바이저에는 모든 호스트의 모든 VM에 대해 "리소스 계측"이 켜져 있어야 합니다. 따라서 각 하이퍼바이저마다 각 게스트에서 Cloud Insights에 사용할 수 있는 데이터가 더 많아집니다. 이 옵션을 설정하지 않으면 각 게스트에 대해 더 적은 성능 메트릭이 획득됩니다. 리소스 측정에 대한 자세한 내용은 Microsoft 설명서를 참조하십시오.
+
link:https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/hh831661(v=ws.11)["Hyper-V 리소스 측정 개요"]

+
link:https://docs.microsoft.com/en-us/powershell/module/hyper-v/enable-vmresourcemetering?view=win10-ps["활성화 - VMResourceMetering"]




NOTE: Hyper-V 데이터 수집기는 Windows 획득 장치가 필요합니다.



== 구성

[cols="2*"]
|===
| 필드에 입력합니다 | 설명 


| 물리적 호스트 IP 주소입니다 | 물리적 호스트(하이퍼바이저)의 IP 주소 또는 정규화된 도메인 이름 


| 사용자 이름 | 하이퍼바이저의 관리자 사용자 이름입니다 


| 암호 | 하이퍼바이저의 암호입니다 


| NT 도메인 | 클러스터의 노드에서 사용하는 DNS 이름입니다 
|===


== 고급 구성

[cols="2*"]
|===
| 필드에 입력합니다 | 설명 


| 재고 폴링 간격(분) | 기본값은 20분입니다. 
|===


== 문제 해결

이 Data Collector에 대한 추가 정보는 에서 확인할 수 있습니다 link:concept_requesting_support.html["지원"] 페이지 또는 에 있습니다 link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Data Collector 지원 매트릭스"].
