---
sidebar: sidebar 
permalink: task_view_configured_data_collectors.html 
keywords: acquisition, AU, data collector, collector, bulk edit, postpone polling, resume polling 
summary: 요약. 
---
= 구성된 데이터 수집기 관리
:allow-uri-read: 


[role="lead"]
설치된 데이터 수집기 페이지에서는 Cloud Insights용으로 구성된 데이터 수집기에 액세스할 수 있습니다. 이 페이지를 사용하여 기존 데이터 수집기를 수정할 수 있습니다.

.단계
. Cloud Insights 메뉴에서 * 관리자 > 데이터 수집기 * 를 클릭합니다
+
Available Data Collector 화면이 표시됩니다.

. 설치된 데이터 수집기 * 를 클릭합니다
+
설치된 모든 데이터 수집기 목록이 표시됩니다. 이 목록은 Collector 이름, 상태, 수집기가 액세스하는 IP 주소 및 장치에서 데이터를 마지막으로 획득한 시점을 제공합니다. 이 화면에서 수행할 수 있는 작업은 다음과 같습니다.

+
** 폴링 제어
** 데이터 수집기 자격 증명을 변경합니다
** 클론 데이터 수집기






== Data Collector 폴링 제어

데이터 수집기를 변경한 후 변경 내용을 확인하기 위해 즉시 폴링하거나, 문제 해결 중에 데이터 수집기의 데이터 수집을 1일, 3일 또는 5일 동안 연기할 수 있습니다.

.단계
. Cloud Insights 메뉴에서 * 관리자 > 데이터 수집기 * 를 클릭합니다
. 설치된 데이터 수집기 * 를 클릭합니다
. 변경할 Data Collector의 왼쪽에 있는 확인란을 선택합니다
. [벌크 작업]을 클릭하고 수행할 폴링 작업을 선택합니다.
+
대량 작업은 여러 Data Collector에서 동시에 수행할 수 있습니다. 데이터 수집기를 선택하고 * Bulk Action * 메뉴에서 수행할 작업을 선택합니다.





== 데이터 수집기 정보 편집

기존 데이터 수집기 설정 정보를 편집할 수 있습니다.

.단일 데이터 수집기를 편집하려면:
. Cloud Insights 메뉴에서 * 관리자 > 데이터 수집기 * 를 클릭하여 설치된 데이터 수집기 목록을 엽니다.
. 수정할 데이터 수집기 오른쪽에 있는 옵션 메뉴에서 * 편집 * 을 클릭합니다.
+
Collector 편집 대화 상자가 열립니다.

. 변경 사항을 입력하고 * Test Configuration * (구성 테스트 *)을 클릭하여 새 구성을 테스트하거나 * Save * (저장 *)를 클릭하여 구성을 저장합니다.


여러 데이터 수집기를 편집할 수도 있습니다.

. 변경할 각 데이터 수집기의 왼쪽에 있는 확인란을 선택합니다.
. [벌크 작업] * 버튼을 클릭하고 [편집]을 선택하여 [데이터 수집기 편집] 대화상자를 엽니다.
. 위와 같이 필드를 수정합니다.
+

NOTE: 선택한 데이터 수집기는 동일한 공급업체 및 모델이어야 하며 동일한 획득 장치에 있어야 합니다.

+
여러 데이터 수집기를 편집할 때 Data Collector Name(데이터 수집기 이름) 필드에 "Mixed(혼합)"가 표시되고 편집할 수 없습니다. 사용자 이름 및 암호와 같은 다른 필드는 "혼합"으로 표시되며 편집할 수 있습니다. 선택한 데이터 수집기에서 동일한 값을 공유하는 필드는 현재 값을 표시하고 편집할 수 있습니다.

+
여러 데이터 수집기를 편집할 때 * Test Configuration * 버튼을 사용할 수 없습니다.





== 데이터 수집기를 클론 중입니다

클론 기능을 사용하면 다른 데이터 소스와 동일한 자격 증명 및 속성을 가진 데이터 소스를 빠르게 추가할 수 있습니다. 클론 생성 기능을 사용하면 동일한 디바이스 유형의 여러 인스턴스를 쉽게 구성할 수 있습니다.

.단계
. Cloud Insights 메뉴에서 * 관리자 > 데이터 수집기 * 를 클릭합니다.
. 설치된 데이터 수집기 * 를 클릭합니다.
. 복사할 데이터 수집기 왼쪽에 있는 확인란을 클릭합니다.
. 선택한 데이터 수집기 오른쪽에 있는 옵션 메뉴에서 * 클론 * 을 클릭합니다.
+
Clone Data Collector 대화 상자가 표시됩니다.

. 필수 필드에 새 정보를 입력합니다.
. 저장 * 을 클릭합니다.


클론 작업은 다른 모든 속성 및 설정을 복사하여 새 데이터 수집기를 생성합니다.



== 데이터 수집기에 대한 대량 작업을 수행합니다

여러 데이터 수집기에 대한 일부 정보를 동시에 편집할 수 있습니다. 이 기능을 사용하면 폴링을 시작하고, 폴링을 연기하고, 여러 데이터 수집기에 대한 폴링을 다시 시작할 수 있습니다. 또한 여러 데이터 수집기를 삭제할 수 있습니다.

.단계
. Cloud Insights 메뉴에서 * 관리자 > 데이터 수집기 * 를 클릭합니다
. 설치된 데이터 수집기 * 를 클릭합니다
. 수정할 데이터 수집기 왼쪽에 있는 확인란을 클릭합니다.
. 오른쪽의 옵션 메뉴에서 수행할 옵션을 클릭합니다.


선택한 작업은 데이터 수집기에서 수행됩니다. 데이터 수집기를 삭제하도록 선택하면 작업을 준수해야 하는 대화 상자가 표시됩니다.
