---
sidebar: sidebar 
permalink: task_dc_hds_nas.html 
keywords: data collector, HDS HNAS, HDS NAS 
summary: 'HDS NAS(HNAS) 데이터 수집기 구성' 
---
= Hitachi Vantara NAS 데이터 수집기 구성


[role="lead"]
Hitachi Vantara NAS 데이터 수집기는 HDS NAS 클러스터 검색을 지원하는 인벤토리 및 구성 데이터 수집기입니다. Cloud Insights는 NFS 및 CIFS 공유, 파일 시스템(내부 볼륨) 및 스팬(스토리지 풀)의 검색을 지원합니다.



== 용어

Cloud Insights는 HNAS 데이터 수집기에서 다음과 같은 인벤토리 정보를 가져옵니다. Cloud Insights에서 획득한 각 자산 유형에 대해 이 자산에 가장 일반적으로 사용되는 용어가 표시됩니다. 이 데이터 수집기를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

[cols="2*"]
|===
| 공급업체/모델 기간 | Cloud Insights 용어입니다 


| 계층 | 디스크 그룹 


| 클러스터 | 스토리지 


| 노드 | 스토리지 노드 


| 스팬 | 스토리지 풀 


| 시스템 드라이브 | 백엔드 LUN 


| 파일 시스템 | 내부 볼륨 
|===
참고: 이러한 용어 매핑은 일반적인 용어 매핑일 뿐이며 이 데이터 수집기의 모든 경우를 나타내는 것은 아닙니다.



== 요구 사항

* 장치 IP 주소입니다
* 포트 22, SSH 프로토콜
* 사용자 이름 및 암호 권한 수준: 감독자
* 참고: 이 데이터 수집기는 SSH 기반이므로 HNAS 자체의 TCP 22 또는 클러스터가 연결된 시스템 관리 장치(SMU)에 대해 SSH 세션을 시작할 수 있어야 합니다.




== 구성

[cols="2*"]
|===
| 필드에 입력합니다 | 설명 


| HNAS 호스트 | HNAS 관리 호스트의 IP 주소 또는 정규화된 도메인 이름입니다 


| 사용자 이름 | HNAS CLI의 사용자 이름입니다 


| 암호 | HNAS CLI에 사용되는 암호입니다 
|===


== 고급 구성

[cols="2*"]
|===
| 필드에 입력합니다 | 설명 


| 재고 폴링 간격(분) | 재고 조사 사이의 간격입니다. 기본값은 30분입니다. 
|===


== 문제 해결

이 데이터 수집기에서 문제가 발생할 경우 다음과 같은 방법을 시도해 보십시오.



==== 인벤토리

[cols="2*"]
|===
| 문제: | 다음을 시도해 보십시오. 


| "연결 오류" 및 "셸 채널 설정 오류:" 또는 "쉘 채널 열기 오류" 오류 메시지 | 네트워크 연결 문제 또는 SSH가 잘못 구성되어 있을 수 있습니다. 대체 SSH 클라이언트와의 연결을 확인합니다 


| "Command: XXX has timed out" 오류 메시지와 함께 "Timeout" 또는 "Error Retrieving data"가 표시됩니다. | * 대체 SSH 클라이언트 * 증가 시간 초과로 명령을 시도하십시오 


| "연결 중 오류 발생" 또는 "잘못된 로그인 자격 증명"과 "장치와 통신할 수 없음:" 오류 메시지 | * IP 주소 확인 * 사용자 이름 및 암호 확인 * 대체 SSH 클라이언트와의 연결 확인 
|===
추가 정보는 에서 찾을 수 있습니다 link:concept_requesting_support.html["지원"] 페이지 또는 에 있습니다 link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Data Collector 지원 매트릭스"].
