---
sidebar: sidebar 
permalink: task_config_cs_data_collectors.html 
keywords: acquisition, AU, data collector, collector 
summary: 데이터 수집기를 구성합니다 
---
= 데이터 수집기 구성
:allow-uri-read: 


[role="lead"]
Cloud Insights 환경에서 데이터 센터에 있는 호스트, 서비스 또는 디바이스의 데이터를 수집하도록 데이터 Collector를 구성합니다.

.시작하기 전에
* 데이터 수집기를 구성하려면 계정 소유자 또는 관리자 권한이 있어야 합니다.
* 데이터 수집을 시작하려면 먼저 획득 장치(인프라트르의 경우) 또는 에이전트(서비스 또는 호스트의 경우)를 구성해야 합니다.
* 데이터를 수집하는 인프라스트럭처 디바이스에 대한 자격 증명이 필요합니다.
+
데이터를 수집하려는 모든 장치에는 장치 네트워크 주소, 계정 정보 및 암호가 필요합니다.





=== 자격 증명 보안

데이터 수집기 자격 증명은 Cloud Insights에 입력되면 암호화되며, AU의 공개 키에 의해 먼저 암호화된 획득 장치(AU)로 전송된 다음 HTTPS를 통해 암호화됩니다. 암호화된 값은 AU가 장치 및 소프트웨어와 통신하기 위해 이 값을 사용할 때 해독됩니다.



=== Data Collector 구성

* Cloud Insights 메뉴에서 * 관리자 > 데이터 수집기 * 를 클릭하고 * + 데이터 수집기 * 버튼을 클릭합니다. 모든 데이터 수집기를 표시하도록 선택하거나 구독에 따라 사용 가능한 데이터 수집기만 표시하도록 필터링할 수 있습니다.


* 선택한 데이터 수집기 유형에 따라 설치 단계가 달라집니다.




==== 운영 체제:

사용자 환경에서 운영 체제 또는 서비스 데이터 수집을 시작하려면 Cloud Insights 에이전트를 하나 이상 설치해야 합니다. 원하는 만큼 에이전트를 설치할 수 있습니다. 각 에이전트는 여러 서비스에서 데이터를 수집할 수 있습니다.

각 에이전트는 서비스에서 데이터를 수집하는 것 외에도 서비스가 설치된 VM/호스트의 데이터 수집기 역할도 합니다. 수집된 데이터는 대시보드 위젯 또는 쿼리에 "노드" 데이터로 표시됩니다.

. Cloud Insights에 액세스하는 VM 또는 호스트(예: 노드)의 플랫폼 유형 또는 운영 체제를 클릭합니다.
. 상담원 액세스 키를 선택합니다.
. 표시된 명령을 클립보드에 복사합니다. 클립보드 아이콘을 클릭하여 명령을 빠르게 복사할 수 있습니다.
. 에이전트 VM/호스트에서 터미널/명령 창을 열고 명령을 붙여 넣습니다. Enter 키를 눌러 명령을 실행합니다.
. 에이전트를 설치한 후 * 마침 * 을 클릭합니다. 에이전트가 데이터 수집을 시작합니다.
+
노드에 대한 데이터가 대시보드에 표시되거나 쿼리에 사용하기 전에 최대 2회의 폴링 기간이 소요될 수 있습니다.





==== 서비스:

서비스 데이터 수집기는 Docker 또는 Kibana와 같은 Telegraf 에이전트를 기반으로 합니다.

.시작하기 전에
* 사용자 환경에서 서비스 데이터를 수집하려면 Cloud Insights 에이전트가 하나 이상 있어야 합니다. 에이전트가 설치되지 않은 경우 서비스 데이터 수집기를 구성할 때 에이전트를 설치하라는 메시지가 표시됩니다.
* 데이터를 수집할 서비스가 사용자 환경에 설치되어 실행되고 있어야 합니다.
+
.. 서비스 데이터 수집기를 클릭합니다.
.. 에이전트 운영 체제 또는 플랫폼을 선택합니다. 플랫폼용 에이전트를 설치하지 않은 경우 지침에 따라 설치합니다.
.. 상담원 액세스 키를 선택합니다.
.. 계속 * 을 클릭합니다.
.. 데이터 수집기 구성에 대한 지침을 따릅니다. 클립보드 아이콘을 클릭하여 표시된 명령 또는 코드 조각을 빠르게 복사할 수 있습니다.
.. 데이터 수집기가 올바르게 구성되었으면 * Finish * 를 클릭합니다.
+
서비스의 데이터가 대시보드에 표시되거나 쿼리에 사용 가능하려면 폴링 기간을 최대 2회 정도 소요될 수 있습니다.







==== 인프라:

인프라 데이터 수집기는 스토리지 또는 스위치와 같은 항목을 포함합니다.

.시작하기 전에
* 인프라 데이터 수집을 시작하려면 하나 이상의 획득 장치가 구성되어 있어야 합니다.
+
.. 인프라 데이터 수집기를 클릭합니다.
.. 데이터 수집기의 이름을 입력합니다. 이름에는 다음 문자가 포함될 수 있습니다.


* 문자(a-z)
* 번호(0-9)
* 하이픈(-)
* 밑줄(_)
* 기간(.)
* 공백()
+
이름은 공백, 마침표 또는 하이픈으로 시작하거나 끝날 수 없습니다.

+
.. 이 데이터 수집기와 연결할 획득 장치를 입력합니다.
.. Configuration(구성) 화면에 필수 필드를 입력합니다.
.. 추가 구성 필드를 입력하려면 * 고급 구성 * 을 클릭합니다. 일부 데이터 수집기는 고급 구성이 필요하지 않습니다.
.. 구성 테스트 * 를 클릭하여 데이터 수집기가 올바르게 구성되었는지 확인합니다.
.. 완료되면 * 수집기 추가 * 를 클릭합니다.




새 획득 장치 추가에 대한 자세한 내용은 을 참조하십시오 link:task_configure_acquisition_unit.html["획득 장치 구성"]

+ 환경의 데이터가 대시보드에 표시되거나 쿼리에 사용하기 전에 폴링 기간을 최대 2개까지 소요될 수 있습니다.
