---
sidebar: sidebar 
permalink: task_dc_na_eseries.html 
keywords: data collector, ontap, clustered ontap 
summary: NetApp E-Series 데이터 수집기 구성 중. 
---
= NetApp E-Series 데이터 수집기


[role="lead"]
NetApp E-Series 데이터 수집기는 인벤토리 및 성능 데이터를 수집합니다. Collector는 동일한 구성을 사용하여 동일한 데이터를 보고하는 펌웨어 7.x+를 지원합니다.



== 용어

Cloud INSIGHT는 NetApp E-Series 데이터 수집기에서 다음 인벤토리 정보를 가져옵니다. 획득한 각 자산 유형에 대해 이 자산에 가장 일반적으로 사용되는 용어가 표시됩니다. 이 데이터 수집기를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

[cols="2*"]
|===
| 공급업체/모델 기간 | Cloud Insights 용어입니다 


| 디스크 | 디스크 


| 볼륨 그룹 | 디스크 그룹 


| 스토리지 | 스토리지 


| 컨트롤러 | 스토리지 노드 


| 볼륨 그룹 | 스토리지 풀 


| 볼륨 | 볼륨 
|===
참고: 이러한 용어 매핑은 일반적인 용어 매핑일 뿐이며 이 데이터 수집기의 모든 경우를 나타내는 것은 아닙니다.



== E-Series 용어(랜딩 페이지)

다음 용어는 NetApp E-Series 자산 랜딩 페이지에서 볼 수 있는 오브젝트 또는 참조에 적용됩니다. 이러한 용어 중 다수는 다른 데이터 수집기에도 적용됩니다.



=== 스토리지

* 모델 - 장치의 모델 이름입니다.
* Vendor – 새 데이터 소스를 구성할 때 표시되는 공급업체 이름입니다
* 일련 번호 – 스토리지 일련 번호입니다. NetApp Clustered Data ONTAP과 같은 클러스터 아키텍처 스토리지 시스템에서 이 일련 번호는 개별 “스토리지 노드” 일련 번호보다 덜 유용할 수 있습니다
* IP – 일반적으로 데이터 소스에 구성된 IP 또는 호스트 이름이 됩니다
* 마이크로코드 버전 – 펌웨어
* 물리적 용량 – 역할에 관계없이 시스템의 모든 물리적 디스크에 대한 기본 2의 합계
* 지연 시간 – 읽기 및 쓰기 모두에서 호스트에서 발생하는 워크로드를 나타냅니다. Cloud Insights는 이러한 가치를 직접 소싱하는 것이 가장 바람직하지만, 이는 종종 그렇지 않습니다. 이러한 기능을 제공하는 스토리지 대신 Cloud Insights는 일반적으로 개별 볼륨의 통계에서 파생된 IOP 가중 계산을 수행합니다.
* 처리량 – 처리량(throughput)을 보이는 스토리지의 총 호스트입니다. 스토리지에서 직접 소싱하는 것이 가장 이상적이며, 사용할 수 없는 경우 Cloud Insights는 이 값을 도출하기 위해 볼륨의 처리량을 합산하고 있습니다
* 관리 - 장치의 관리 인터페이스에 대한 하이퍼링크가 포함될 수 있습니다. 인벤토리 보고의 일부로 Cloud Insights 데이터 소스가 프로그래밍 방식으로 만듭니다




=== 스토리지 풀

* 스토리지 – 이 풀이 상주하는 스토리지 시스템입니다. 필수입니다
* 형식 - 가능성 목록 목록의 설명 값입니다. 가장 일반적인 것은 "씬 프로비저닝" 또는 "RAID 그룹"입니다.
* 노드 – 이 스토리지 배열의 아키텍처가 특정 스토리지 노드에 속해 있는 경우, 이 스토리지 배열의 이름은 해당 랜딩 페이지의 하이퍼링크로 표시됩니다
* Flash Pool을 사용합니다. 예/아니요 값입니다
* 중복 – RAID 레벨 또는 보호 체계. E-Series는 DDP 풀에 대해 “RAID 7”을 보고합니다
* 용량 – 이 값은 논리적 사용 용량, 가용 용량 및 총 논리적 용량, 그리고 이 용량 전체에서 사용된 비율입니다. 두 가지 가치 모두 E-Series의 "보존" 용량으로, E-Series의 자체 사용자 인터페이스에서 표시할 수 있는 것보다 더 많은 수와 비율을 제공합니다
* 과도하게 커밋된 용량 – 효율성 기술을 통해 스토리지 풀의 논리적 용량보다 큰 볼륨 또는 내부 볼륨 용량의 합계를 할당한 경우 여기에 있는 백분율 값은 0%보다 큽니다.
* 스냅샷 – 스토리지 풀 아키텍처가 스냅샷 전용 영역에 해당 용량의 일부를 할당하는 경우 사용된 스냅샷 용량 및 총 용량입니다
* 사용률 – 이 스토리지 풀에 용량을 제공하는 모든 디스크의 사용 중 가장 높은 비율을 나타내는 백분율 값입니다. 디스크 사용률이 반드시 스토리지 성능과 강력한 상관 관계가 있는 것은 아닙니다. 호스트 기반 워크로드가 없을 경우 디스크 재구축, 중복 제거 작업 등으로 인해 사용률이 높을 수 있습니다. 또한 많은 스토리지의 복제 구현으로 인해 디스크 사용률이 높아지고 볼륨 작업 부하로 표시되지 않을 수 있습니다.
* IOPS – 이 스토리지 풀에 용량을 제공하는 모든 디스크의 IOPS 합계입니다. 특정 플랫폼에서 디스크 IOP를 사용할 수 없는 경우 이 값은 이 스토리지 풀에 있는 모든 볼륨의 볼륨 IOPS 합에서 가져옵니다
* 처리량 – 이 스토리지 풀에 용량을 제공하는 모든 디스크의 총 처리량입니다. 특정 플랫폼에서 디스크 처리량을 사용할 수 없는 경우 이 값은 이 스토리지 풀에 있는 모든 볼륨의 전체 볼륨 합에서 구할 수 있습니다




=== 스토리지 노드

* 스토리지 – 이 노드가 속한 스토리지 시스템입니다. 필수입니다
* HA 파트너 – 노드가 1개 노드로 페일오버되고 다른 1개 노드만 페일오버되는 플랫폼에서는 일반적으로 이 노드에 표시됩니다
* 상태 - 노드의 상태입니다. 배열이 데이터 소스에 의해 인벤토리를 작성할 수 있을 만큼 양호한 경우에만 사용할 수 있습니다
* 모델 - 노드의 모델 이름입니다
* 버전 - 디바이스의 버전 이름입니다.
* 일련 번호 - 노드 일련 번호입니다
* 메모리 – 사용 가능한 경우 베이스 2 메모리
* 사용률 – 일반적으로 CPU 사용률 번호 또는 NetApp ONTAP의 경우 컨트롤러 스트레스 인덱스입니다. NetApp E-Series에서는 현재 활용률을 사용할 수 없습니다
* IOPS – 이 컨트롤러의 호스트 기반 IOP를 나타내는 숫자입니다. 이상적으로는 스토리지에서 직접 소싱하는 것이 이상적이며, 사용할 수 없는 경우 이 노드에 배타적으로 속하는 볼륨의 모든 IOP를 합산하여 계산됩니다.
* 지연 시간 – 이 컨트롤러의 일반적인 호스트 지연 시간 또는 응답 시간을 나타내는 숫자입니다. 이상적으로는 스토리지에서 직접 소싱하는 것이 이상적이며, 사용할 수 없는 경우 이 노드에 배타적으로 속하는 볼륨에서 IOPS 가중 계산을 수행하여 계산됩니다.
* 처리량 – 이 컨트롤러의 호스트 기반 처리량을 나타내는 숫자입니다. 이상적으로는 스토리지에서 직접 소싱하는 것이 이상적이며, 사용할 수 없는 경우 이 노드에 배타적으로 속하는 볼륨의 모든 처리량을 합산하여 계산됩니다.
* 프로세서 - CPU 수입니다




== 요구 사항

* 어레이에 있는 각 컨트롤러의 IP 주소입니다
* 포트 요구 사항 2463




== 구성

[cols="2*"]
|===
| 필드에 입력합니다 | 설명 


| 쉼표로 구분된 Array SANtricity 컨트롤러 IP 목록입니다 | 스토리지 컨트롤러의 IP 주소 및/또는 정규화된 도메인 이름입니다 
|===


== 고급 구성

[cols="2*"]
|===
| 필드에 입력합니다 | 설명 


| 재고 폴링 간격(분) | 기본값은 30분입니다 


| 성능 폴링 간격 최대 3600초 | 기본값은 300초입니다 
|===


== 문제 해결

이 데이터 수집기에 대한 추가 정보는 에서 찾을 수 있습니다 link:concept_requesting_support.html["지원"] 페이지 또는 에 있습니다 link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Data Collector 지원 매트릭스"].
