---
sidebar: sidebar 
permalink: task_dc_openstack.html 
keywords: data collector, openstack, OpenStack 
summary: OpenStack 데이터 수집기. 
---
= OpenStack 데이터 수집기
:allow-uri-read: 


[role="lead"]
OpenStack(REST API/KVM) 데이터 수집기는 모든 OpenStack 인스턴스에 대한 인벤토리 데이터를 수집하며 선택적으로 VM 성능 데이터를 가져옵니다.



== 요구 사항

* OpenStack 컨트롤러의 IP 주소입니다
* OpenStack 관리자 역할 자격 증명 및 Linux KVM 하이퍼바이저에 대한 sudo 액세스 admin 계정 또는 admin 등가 권한을 사용하지 않는 경우, 데이터 수집기 사용자 ID에 대해 휴식을 취할 기본 정책을 식별하기 위해 시행착오 및 오류를 사용해야 합니다.
* OpenStack Ceilometer 모듈을 설치하고 성능 수집을 위해 구성해야 합니다. Ceilometer 구성은 각 하이퍼바이저에 대한 nova.conf 파일을 편집한 다음 각 하이퍼바이저에서 Nova Compute 서비스를 다시 시작하여 수행됩니다. 옵션 이름이 OpenStack의 다양한 릴리즈에서 변경되었습니다.
+
** 아이스하우스
** 준오
** 킬로
** 리버티
** 미타카
** 뉴턴
** 옥타


* CPU 통계의 경우 컴퓨팅 노드의 /etc/nova/nova.conf에서 “compute_monitor=ComputeDriverCPUMonitor”를 켜야 합니다.
* 포트 요구 사항:
+
** http의 경우 5000, Keystone 서비스의 경우 13000
** 22 KVM SSH의 경우
** Nova 컴퓨팅 서비스: 8774
** 8776을 참조하십시오
** Ceilometer 성능 서비스용 8777
** Glance 이미지 서비스의 경우 9292 * 참고 * 포트는 특정 서비스에 바인딩되며, 대규모 환경의 컨트롤러 또는 다른 호스트에서 서비스가 실행될 수 있습니다.






== 구성

[cols="2*"]
|===
| 필드에 입력합니다 | 설명 


| OpenStack 컨트롤러 IP 주소입니다 | OpenStack 컨트롤러의 IP 주소 또는 정규화된 도메인 이름입니다 


| OpenStack 관리자 | OpenStack 관리자의 사용자 이름입니다 


| OpenStack 암호 | OpenStack Admin에 사용되는 암호입니다 


| OpenStack 관리자 테넌트 | OpenStack 관리자 테넌트 이름입니다 


| KVM Sudo 사용자 | KVM Sudo 사용자 이름입니다 


| 자격 증명 유형을 지정하려면 '암호' 또는 'OpenSSH 키 파일'을 선택하십시오 | SSH를 통해 장치에 연결하는 데 사용되는 자격 증명 유형입니다 


| 재고 개인 키에 대한 전체 경로 | 재고 개인 키에 대한 전체 경로 


| KVM Sudo 암호 | KVM Sudo 암호 
|===


== 고급 구성

[cols="2*"]
|===
| 필드에 입력합니다 | 설명 


| SSH를 통해 하이퍼바이저 인벤토리 검색을 설정합니다 | SSH를 통해 하이퍼바이저 인벤토리 검색을 설정하려면 이 확인란을 선택합니다 


| OpenStack 관리 URL 포트입니다 | OpenStack 관리 URL 포트입니다 


| HTTPS를 사용합니다 | 보안 HTTP를 사용하려면 선택합니다 


| SSH 포트 | SSH에 사용되는 포트입니다 


| SSH 프로세스 재시도 | 인벤토리 재시도 횟수입니다 


| 재고 폴링 간격(분) | 재고 조사 사이의 간격입니다. 기본값은 20분입니다. 
|===


== 문제 해결

이 데이터 수집기에서 문제가 발생할 경우 다음과 같은 방법을 시도해 보십시오.



==== 인벤토리

[cols="2*"]
|===
| 문제: | 다음을 시도해 보십시오. 


| "정책 허용 안 함" 또는 "권한이 없습니다"로 시작하는 오류 메시지와 함께 "구성 오류" | * IP 주소 확인 * 사용자 이름 및 암호 확인 
|===
추가 정보는 에서 찾을 수 있습니다 link:concept_requesting_support.html["지원"] 페이지 또는 에 있습니다 link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Data Collector 지원 매트릭스"].
