---
sidebar: sidebar 
permalink: task_dc_emc_unity.html 
keywords: data collector, VNXe, EMC, Unity 
summary: VNXe 데이터 수집기 구성 중 
---
= EMC Unity 데이터 수집기 구성


[role="lead"]
Dell EMC Unity(이전의 VNXe) 데이터 수집기는 VNXe 유니파이드 스토리지 시스템에 대한 인벤토리 지원을 제공합니다. Cloud Insights는 현재 iSCSI 및 NAS 프로토콜을 지원합니다.



== 요구 사항

* Unity 데이터 수집기는 CLI를 기반으로 하며, VNXe 데이터 수집기가 있는 획득 장치에 Unisphere for Unity CLI(uemcli.exe)를 설치해야 합니다.
* uemcli.exe 은 전송 프로토콜로 HTTPS를 사용하므로 획득 장치에서 Unity에 대한 HTTPS 연결을 시작할 수 있어야 합니다.
* Unity 장치의 IP 주소 또는 정규화된 도메인 이름입니다
* 데이터 수집기에서 사용할 수 있는 읽기 전용 사용자가 적어도 있어야 합니다.
* 포트 443의 HTTPS가 필요합니다
* EMC Unity 데이터 수집기는 인벤토리에 대한 NAS 및 iSCSI 지원을 제공합니다. Fibre Channel 볼륨이 검색되지만 Cloud Insights는 FC 매핑, 마스킹 또는 스토리지 포트에 대해 보고하지 않습니다.




== 용어

Cloud Insights는 Unity 데이터 수집기에서 다음 인벤토리 정보를 가져옵니다. Cloud Insights에서 획득한 각 자산 유형에 대해 이 자산에 가장 일반적으로 사용되는 용어가 표시됩니다. 이 데이터 수집기를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

[cols="2*"]
|===
| 공급업체/모델 기간 | Cloud Insights 용어입니다 


| 디스크 | 디스크 


| 스토리지 | 스토리지 


| 프로세서 | 스토리지 노드 


| 스토리지 풀 | 스토리지 풀 


| 일반 iSCSI 블록 정보, VMware VMFS | 공유 


| 복제 원격 시스템 | 동기화 


| iSCSI 노드 | iSCSI 타겟 노드 


| iSCSI 초기자 | iSCSI 대상 초기자 
|===
참고: 이러한 용어 매핑은 일반적인 용어 매핑일 뿐이며 이 데이터 소스의 모든 경우를 나타내는 것은 아닙니다.



== 구성

[cols="2*"]
|===
| 필드에 입력합니다 | 설명 


| Unity 스토리지 | Unity 장치의 IP 주소 또는 정규화된 도메인 이름입니다 


| 사용자 이름 | Unity 장치의 사용자 이름입니다 


| 암호 | Unity 장치의 암호입니다 


| 실행 가능한 UEMCLI에 대한 전체 경로 | uemcli.exe_executable이 포함된 폴더의 전체 경로입니다 
|===


== 고급 구성

[cols="2*"]
|===
| 필드에 입력합니다 | 설명 


| 재고 폴링 간격(분) | 재고 조사 사이의 간격입니다. 기본값은 40분입니다 


| Unity CLI 포트 | Unity CLI에 사용되는 포트입니다 


| 성능 폴링 간격(초) | 기본값은 300입니다. 
|===


== 문제 해결

이 데이터 수집기에서 문제가 발생할 경우 다음과 같은 방법을 시도해 보십시오.



==== 인벤토리

[cols="2*"]
|===
| 문제: | 다음을 시도해 보십시오. 


| "Failed to execute external utility"(외부 유틸리티 실행 실패) 및 "Failed to find Unisphere executable uemcli" 오류 메시지 | * 올바른 IP 주소, 사용자 이름 및 암호 확인 * Cloud Insights 획득 유닛에 Unisphere CLI가 설치되어 있는지 확인 * 데이터 소스 구성에서 Unisphere CLI 설치 디렉토리가 올바른지 확인 * 데이터 소스 구성에서 VNXe의 IP가 올바른지 확인 Cloud Insights 획득 장치에서 CMD를 열고 구성된 설치 디렉토리 ${INSTALLDIR로 변경합니다. uemcli -d <your IP> -u <your ID>/sys/general show 를 입력하여 VNXe 디바이스에 대한 접속을 시도합니다 
|===
추가 정보는 에서 찾을 수 있습니다 link:concept_requesting_support.html["지원"] 페이지 또는 에 있습니다 link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Data Collector 지원 매트릭스"].
