---
sidebar: sidebar 
permalink: task_defining_annotations.html 
keywords: annotations, monitor, notes, tags 
summary: 주석을 사용하여 데이터를 추적합니다. 
---
= 주석 정의


[role="lead"]
Cloud Insights를 사용자 지정하여 회사 요구 사항에 맞는 데이터를 추적할 때 주석이라는 특수 메모를 정의하여 자산에 할당할 수 있습니다.

자산 수명 종료, 데이터 센터, 건물 위치, 스토리지 계층 또는 볼륨 서비스 수준과 같은 정보를 사용하여 자산에 주석을 할당할 수 있습니다.

주석을 사용하여 환경을 모니터링하는 데 유용한 작업은 다음과 같습니다.

* 모든 주석 유형에 대한 정의를 만들거나 편집합니다.
* 자산 페이지를 표시하고 각 자산을 하나 이상의 주석과 연결합니다.
+
예를 들어, 자산이 임대되고 2개월 이내에 임대가 만료되는 경우 자산에 수명 종료 주석을 적용할 수 있습니다. 이렇게 하면 다른 사용자가 해당 자산을 장기간 사용하지 못하게 할 수 있습니다.

* 같은 유형의 여러 자산에 주석을 자동으로 적용하는 규칙을 작성합니다.
* 주석을 기준으로 자산을 필터링합니다.




== 기본 주석 유형

Cloud Insights는 몇 가지 기본 주석 유형을 제공합니다. 이러한 주석을 사용하여 데이터를 필터링하거나 그룹화할 수 있습니다.

다음과 같은 기본 주석 유형과 자산을 연결할 수 있습니다.

* 생일, 일몰 또는 수명 종료 등의 자산 수명 주기
* 데이터 센터, 건물 또는 바닥과 같은 장치에 대한 위치 정보
* 품질(계층), 연결된 장치(스위치 수준) 또는 서비스 수준별 자산 분류
* 핫(높은 활용도) 등의 상태


다음 표에는 Cloud Insights에서 제공하는 주석 유형이 나와 있습니다.

[cols="30,53, 16"]
|===


| 주석 유형 | 설명 | 유형 


| 별칭 | 리소스에 대한 사용자 친화적인 이름입니다 | 텍스트 


| 컴퓨팅 리소스 그룹 | 호스트 및 VM 파일 시스템 데이터 수집기에서 사용하는 그룹 할당 | 목록 


| 데이터 센터 | 물리적 위치 | 목록 


| 핫 | 사용량이 많은 디바이스를 정기적으로 또는 용량 임계값으로 사용합니다 | 부울 


| 참고 | 리소스와 연결된 메모입니다 | 테스트 


| 서비스 수준 | 리소스에 할당할 수 있는 지원되는 서비스 수준 집합입니다. 내부 볼륨, qtree, 볼륨에 대한 정렬 옵션 목록을 제공합니다. 서비스 수준을 편집하여 다양한 수준에 대한 성능 정책을 설정합니다. | 목록 


| 일몰 | 해당 디바이스에 새 할당을 수행할 수 없는 임계값을 설정합니다. 계획된 마이그레이션 및 기타 보류 중인 네트워크 변경에 유용합니다. | 날짜 


| 스위치 레벨 | 스위치에 대한 범주를 설정하기 위한 사전 정의된 옵션. 일반적으로 이러한 지정은 편집할 수 있지만 장치의 수명 동안 유지됩니다. 스위치에만 사용할 수 있습니다. | 목록 


| 계층 | 는 사용자 환경 내에서 서로 다른 서비스 수준을 정의하는 데 사용할 수 있습니다. 계층은 필요한 속도(예: 금 또는 은)와 같은 수준의 유형을 정의할 수 있습니다. 이 기능은 내부 볼륨, Qtree, 스토리지 어레이, 스토리지 풀 및 볼륨에서만 사용할 수 있습니다. | 목록 


| 위반 심각도입니다 | 중요도가 가장 높은 계층부터 가장 낮은 계층까지 위반 등급(예: 중요)의 순위를 지정합니다(예: 호스트 포트 누락 또는 이중화 누락). | 목록 
|===

NOTE: 별칭, 데이터 센터, 핫, 서비스 레벨, 일몰, 스위치 수준, 계층 및 위반 심각성 은 시스템 수준 주석으로, 삭제하거나 이름을 바꿀 수 없습니다. 할당된 값만 변경할 수 있습니다.



== 사용자 정의 주석 작성

주석을 사용하여 비즈니스 요구에 맞는 맞춤형 비즈니스 관련 데이터를 자산에 추가할 수 있습니다. Cloud Insights에서 기본 주석 집합을 제공하는 경우 다른 방법으로 데이터를 볼 수 있습니다. 사용자 지정 주석의 데이터는 스토리지 제조업체, 볼륨 수 및 성능 통계와 같이 이미 수집된 장치 데이터를 보완합니다. 주석을 사용하여 추가하는 데이터는 Cloud Insights에서 검색되지 않습니다.

.단계
. Cloud Insights 메뉴에서 * 관리 > 주석 * 을 클릭합니다.
+
주석 페이지에는 주석 목록이 표시됩니다.

. 추가 * 를 클릭합니다
. 주석의 * 이름 * 과 * 설명 * 을 입력합니다.
+
이 필드에는 최대 255자까지 입력할 수 있습니다.

. Type * 을 클릭한 다음 이 주석에 허용되는 데이터 유형을 나타내는 다음 옵션 중 하나를 선택합니다.


.주석 유형
부울:: yes 및 no를 선택할 수 있는 드롭다운 목록을 만듭니다 예를 들어 "직접 연결" 주석은 부울입니다.
날짜:: 이렇게 하면 날짜가 들어 있는 필드가 만들어집니다. 예를 들어, 주석이 날짜가 될 경우 이를 선택합니다.
목록::
+
--
* 드롭다운 고정 목록
+
다른 사용자가 장치에 이 주석 유형을 할당하는 경우 목록에 값을 더 추가할 수 없습니다.

* 드롭다운 유연한 목록
+
이 목록을 만들 때 즉시 새 값 추가 옵션을 선택하면 다른 사용자가 장치에 이 주석 유형을 할당할 때 목록에 값을 더 추가할 수 있습니다.



--
번호:: 주석을 지정하는 사용자가 숫자를 입력할 수 있는 필드를 만듭니다. 예를 들어, 주석 유형이 "바닥"인 경우 사용자는 "숫자"의 값 유형을 선택하고 바닥 번호를 입력할 수 있습니다.
텍스트:: 자유 형식 텍스트를 허용하는 필드를 만듭니다. 예를 들어, 주석 유형으로 "Language"를 입력하고 값 유형으로 "Text"를 선택한 다음 언어를 값으로 입력할 수 있습니다.



NOTE: 유형을 설정하고 변경 사항을 저장한 후에는 주석 유형을 변경할 수 없습니다. 유형을 변경해야 하는 경우 주석을 삭제하고 새 주석을 만들어야 합니다.

. 주석 유형으로 목록 을 선택한 경우 다음을 수행합니다.
+
.. 자산 페이지에서 주석에 더 많은 값을 추가할 수 있는 기능을 원하는 경우 * 즉시 새 값 추가 * 를 선택하여 유연한 목록을 만듭니다.
+
예를 들어 자산 페이지에 있고 자산에는 Detroit, Tampa 및 Boston 값이 있는 City 주석이 있다고 가정해 보겠습니다. 빠른 실행 시 새 값 추가 * 옵션을 선택한 경우 주석 페이지로 이동하여 추가할 필요 없이 자산 페이지에서 샌프란시스코 및 시카고와 같은 도시에 직접 추가 값을 추가할 수 있습니다. 이 옵션을 선택하지 않으면 주석을 적용할 때 새 주석 값을 추가할 수 없습니다. 그러면 고정 목록이 생성됩니다.

.. 값 * 및 * 설명 * 필드에 값과 설명을 입력합니다.
.. 추가 값을 추가하려면 * + 추가 + * 를 클릭합니다.
.. 휴지통 아이콘을 클릭하여 값을 삭제합니다.


. 저장 * 을 클릭합니다
+
주석이 주석 페이지의 목록에 나타납니다.



UI에서는 주석을 즉시 사용할 수 있습니다.
